### PR TITLE
update makefile to use sundials instead cvodes lib

### PR DESCRIPTION
**Pull request by yizhang-cae**
#### Submission Checklist

- [x] Run unit tests: `./runTests.py src/test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary
Per stan-dev/math#779 the cvodes and idas libs are replaced by sundials. PR stan-dev/math#832 makes this update for the makefile of math lib. Similar changes need to be made for the makefile of cmdstan, rstan, etc. It suffices to replace LIBCVODES in makefile with LIBSUNDIALS.

#### How to Verify
Successful make of projects utilizing sundials functionalities.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):
Metrum Research Group, LLC

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by wds15** [comment]
@yizhang-cae : I think you need to update in this PR the stan-math dependency to the latest one which now includes sundials. Then we can merge this PR. I think this PR causes some hickups for others if we wait with it more. Can you handle this this shortly?

@seantalts : I think this one needs to go in ASAP to make submodule bumping working again, but please confirm.

**Comment by bob-carpenter** [comment]
@wds15  The way to get PRs merged into Stan quickly is to review them, because nothing can be merged without a formal review using the GitHub interface.  

I don't understand this build process, but as soon as tests pass, I'm merging it anyway because we need to get Jenkins testing Stan again.

**Comment by yizhang-cae** [comment]
I've restarted the PR to trigger travis.

**Comment by mitzimorris** [comment]
> The only thing is that the Travis tests weren't passing for what on the
> surface seemed like legitimate reasons? So this might break develop Stan on
> Travis...

@seantalts please explain - I'd like to be able to help out here, but I don't see where Travis tests weren't passing - I'm logged into Travis and all I see pending build.  your comments suggest that there was a previous build that failed - what was this?

**Comment by seantalts** [comment]
Unfortunately the Travis UI doesn't let you see previous builds, from what I can tell, and I don't have the old one up on my screen anymore to take a screenshot of. It had some C compiler errors (not timeouts or anything).

**Comment by yizhang-cae** [comment]
My local build passed after rebasing. That's why I'm trigger another travis
test since this one has been sitting here for a while. Let's wait & see.

Regards,
Yi Zhang, Ph.D.
Metrum Research Group LLC
2 Tunxis Road, Tariffville, CT 06081
yiz@metrumrg.com
www.metrumrg.com

**Comment by mitzimorris** [comment]
I too am running a local build - so far so good.

**Pull request merged**
