### PR TITLE
Fix minor typo in reference manual.

### PR DESCRIPTION
**Pull request by n-s-f**
This corrects a minor typo in the introduction to chapter 27.

### CODE REVIEW

**Comment by bob-carpenter** [comment]
Thanks.  I'll merge when the travis build is done.

**Comment by syclik** [comment]
@n-s-f, you circumvented the pull request template. At the minimum, can you clarify the copyright holder? See https://github.com/stan-dev/stan/blob/develop/.github/PULL_REQUEST_TEMPLATE.md

**Comment by n-s-f** [comment]
@syclik Apologies.  The copyright holder is [Fast Forward Labs](http://www.fastforwardlabs.com/).  Our legal department has given this the green light.

Thanks.

**Comment by syclik** [comment]
Thanks! Sorry, forgot to mention license. Fast Forward Labs ok with CC-BY 4.0? Mind putting that down as a comment if it is?

**Comment by n-s-f** [comment]
Correct!  Fast Forward Labs is happy with the CC-BY 4.0. 

Thanks.

**Comment by syclik** [comment]
Thank you!

**Comment by bob-carpenter** [comment]
This is making me smile because it's literally a single-letter
change.  Not sure that could even be copyrighted, but I suppose
we'e better safe than sorry.

- Bob

**Pull request merged**
