### PR TITLE
Bugfix/issue 1937 ios base

### PR DESCRIPTION
**Pull request by bgoodri**
#### Submisison Checklist

- [ ] Run unit tests: `./runTests.py src/test/unit` gtest is broken locally
- [ ] Run cpplint: `make cpplint` `python: can't open file '/cpplint.py': [Errno 2] No such file or directory`
- [X] Declare copyright holder and open-source license: see below

#### Summary

Deletes the specialized `ios-base::failure` exception

#### Intended Effect

Allow clang++ to compile rstan

#### How to Verify

`R CMD build rstan` once the fix makes it into StanHeaders

#### Side Effects

Exception message is more generic

#### Documentation

None

#### Reviewer Suggestions

@bob-carpenter 

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Trustees of Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by bgoodri** [comment]
The one failing Travis run actually says that it passed after 6+ hours

**Comment by syclik** [comment]
Travis has been acting up lately. I just restarted that one job that failed
-- you should have been able to do so yourself.

I'll take a look at the actual pull request now.

**Comment by syclik** [comment]
btw, what do you mean gtest is broken locally? Can you show me at the meeting?

**Comment by syclik** [comment]
Looks good to me.

**Comment by bob-carpenter** [comment]
Thanks much.  I mistakenly thought I'd already made this fix for 2.10.

**Pull request merged**
