### PR TITLE
Compile models are fixed. They will now try to instantiate models with the types we need.

### PR DESCRIPTION
**Pull request by syclik**
#### Submisison Checklist

- [x] Run unit tests: `./runTests.py src/test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary
The integration tests were broken before. We had thought that adding `-fsyntax-only` was sufficient for code to compile, but we found out that it didn't instantiate enough.

This pull request will now instantiate the Stan program with the correct template instantiations.

This currently passes on develop now, but should fail:
```
make src/test/test-models/good/validate_conditional_op_good.hpp-test
```
or
```
./runTests.py src/test/integration/compile_models_test.cpp 
```

With this pull request, it fails now. We'll need to make sure everything else passes.

#### Intended Effect
Makes sure our Stan programs are compilable in C++.

#### How to Verify
Run this for one file:
```
make src/test/test-models/good/validate_conditional_op_good.hpp-test
```

or to run all files:
```
./runTests.py src/test/integration/compile_models_test.cpp 
```

Here's what's used as a test file just to make sure we're instantiating enough (generated in `test/test-model-main.cpp` by make):
```c++
nt main() {
  stan::io::var_context *data = NULL;
  stan_model model(*data);

  std::vector<stan::math::var> params;
  std::vector<double> x_r;
  std::vector<int> x_i;

  model.log_prob<false, false>(params, x_i);
  model.log_prob<false, true>(params, x_i);
  model.log_prob<true, false>(params, x_i);
  model.log_prob<true, true>(params, x_i);
  model.log_prob<false, false>(x_r, x_i);
  model.log_prob<false, true>(x_r, x_i);
  model.log_prob<true, false>(x_r, x_i);
  model.log_prob<true, true>(x_r, x_i);

  return 0;
}
```

#### Side Effects
This might break some things we thought were ok. We'll need to fix them.

#### Documentation
I added a few notes to the makefile.

#### Reviewer Suggestions
Anyone.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by syclik** [comment]
@bob-carpenter, the failure is right: it fails on the tenary operator.

**Comment by mitzimorris** [comment]
Code changes from branch bugfix/issue-2044-ternary-op-result-for-mismatched-types
will pick up version of stan translater that generate a model.hpp file that compiles.
The console log errors report that build failed on the following line of c++ code:

```
 stan::math::assign(tpy, (logical_lt(y,100) ? double(x) : double(py) ));
```

for the following statement in the transformed parameters block of the model:

```
  tpy = y < 100 ? y : py;   // t,f : real,var
```

where tpy is a transformed parameter, y is type real, and py is type var.

In branch bugfix/issue-2044-ternary-op-result-for-mismatched-types, the above statement
is translated as:

```
stan::math::assign(tpy, (logical_lt(y,100) ? stan::math::promote_scalar<T__>(y) : stan::math::promote_scalar<T__>(py) ));
```

**Comment by bob-carpenter** [comment]
I don't really understand the makefile, but this is going to fail the integration tests at least until the ternary op gets in.  That's the correct behavior for this particular commit, though, so you can just merge it as is if you want.

**Comment by syclik** [comment]
Woo hoo! The other models we have don't fail to compile! That's a relief.

**Comment by bob-carpenter** [comment]
Indeed.  Thanks for getting this working.  I was really
relying on it to catch errors.

- Bob

**Pull request merged**
