### PR TITLE
Fix typo in quality gate filter

### PR DESCRIPTION
**Pull request by serban-nicusor-toptal**
#### Submission Checklist

- [ ] Run unit tests: `./runTests.py src/test/unit`
- [ ] Run cpplint: `make cpplint`
- [ ] Declare copyright holder and open-source license: see below

#### Summary

Fix a typo in the quality gate filter, this fails downstream tests in Math by being unstable, see [pipeline](https://jenkins.flatironinstitute.org/blue/organizations/jenkins/Stan%2FMath/detail/PR-2822/85/pipeline/).

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Toptal

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Review by WardBrian — APPROVED** [review]
Does CmdStan need the same change?

**Comment by serban-nicusor-toptal** [comment]
In `cmdstan` we only have warnings from 
```
clang: warning: -Wl,-L,/Users/jenkins/workspace/Stan_CmdStan_develop/stan/lib/stan_math/lib/tbb: 'linker' input unused [-Wunused-command-line-argument]
```
So the following filter does the trick:
```
excludeFile('stan/lib/stan_math/lib/*')
```

**Comment by WardBrian** [comment]
https://github.com/stan-dev/cmdstan/pull/1143 has the quality gate complaining

**Comment by serban-nicusor-toptal** [comment]
Oh, that's weird, it comes from the MacOS SDK
```
stan/lib/stan_math/lib/boost_1.78.0/boost/assert/source_location.hpp:80:18: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
            std::sprintf( buffer, ":%ld", static_cast<long>( column() ) );
                 ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here
__deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:215:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                      ^
```
And the Jenkins plugin sees it as a different warning/path. I'll run a new build on your PR to try and filter it.

**Pull request merged**
