### PR TITLE
Adding test for multiple translation units and inlining remaining functions

### PR DESCRIPTION
**Pull request by syclik**
#### Submisison Checklist
- [x] Run unit tests: `./runTests.py src/test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below
#### Summary

Add test for multiple translation unit. Running it on the current `develop` branch would fail.
Fixed the behavior by inlining a few more functions.
#### Intended Effect

Allows Stan programs to be included in multiple translation units.
#### How to Verify

Run the new test:

```
./runTests.py src/test/unit/multiple_translation_units_test.cpp
```
#### Side Effects

There should be no runtime side effects.
#### Documentation

None.
#### Reviewer Suggestions

Anyone.
#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Columbia University.

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by syclik** [comment]
I haven't figured out how to make this work under windows. Hopefully I can figure that out this week.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
@bob-carpenter: it failed with the `-m64` flag with g++ in RTools 3.3. With the `-m32` flag, it works. I updated the Jenkins config to reflect that.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
Jenkins, restart this please.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by bob-carpenter** [comment]
Any idea why it would fail with -m64?  Is it that g++ doesn't know
the flag or is it something with multiple translation units?

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
It looks like the linker (ld.exe) might be 32-bit while the compiler is
64-bit for Rtools 3.3. I don't even know how that's possible.

If you look at this output (
http://d1m1s1b1.stat.columbia.edu:8080/job/Stan%20Pull%20Request%20-%20Windows%20-%20Tests%20-%20Unit/892/consoleFull),
you'll see:
c:/rtools/gcc-4.6.3/bin/../lib/gcc/i686-w64-mingw32/4.6.3/../../../../i686-w64-mingw32/bin/ld.exe:
i386:x86-64 architecture of input file
`test/unit/multiple_translation_units1.o' is incompatible with i386 output
c:/rtools/gcc-4.6.3/bin/../lib/gcc/i686-w64-mingw32/4.6.3/../../../../i686-w64-mingw32/bin/ld.exe:
i386:x86-64 architecture of input file
`test/unit/multiple_translation_units2.o' is incompatible with i386 output
Error: 64-bit reloc in dll
Error: 64-bit reloc in dll
Error: 64-bit reloc in dll
Error: 64-bit reloc in dll
Error: 64-bit reloc in dll
Error: 64-bit reloc in dll
Error: 64-bit reloc in dll
Error: 64-bit reloc in dll
Error: 64-bit reloc in dll
Error: 64-bit reloc in dll
Error: 64-bit reloc in dll
Error: 64-bit reloc in dll
Error: 64-bit reloc in dll
Error: 64-bit reloc in dll
...

**Comment by bob-carpenter** [comment]
@sycklik  This is another one that's been hanging for a long time, so I'm going to close until it's fixed and ready for submission.

**Comment by syclik** [comment]
Thanks. We can revisit this when the compiler is upgraded in RTools.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
I'm reopening this pull request. Hopefully it kicks off tests. If it fails under Windows again, I'll see if I can conditionally disable the test for Windows.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Pull request merged**
