### PR TITLE
Fixes #2051 --- manual for 2.13

### LINKED ISSUE #2051: next manual, 2.12.0++
#### Summary:

This is where updates for the 2.12 manual should go.

v2.12.0

### PR DESCRIPTION
**Pull request by bob-carpenter**
#### Submisison Checklist

- [ ] Run unit tests: `./runTests.py src/test/unit`
- [ ] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary

Update manual for all comments brought up in #2051 (feature is numbered 2050, but should've been 2051).

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by bob-carpenter** [comment]
@mitzimorris The review needs to go into the GitHub interface before I can merge without pulling admin rank.

**Comment by mitzimorris** [comment]
done.

**Comment by alvaro1101** [comment]
There is a line too long in the file stan/src/docs/stan-reference/examples.tex in the line 4669. I don't know if report this here or pull a request.

**Comment by bob-carpenter** [comment]
What do you mean by a line too long?  Are you
compiling it with our fonts or the Times Roman
that things default to?

In any case, this isn't the right place to report
this, because this is a pull request and the branch
has already been merged.

- Bob

**Pull request merged**
