### PR TITLE
to_vector, to_row_vector, to_matrix functions

### PR DESCRIPTION
**Pull request by randommm**
#### Summary:

Implement features of issue #575: functions to convert from one container to another: to_vector, to_row_vector, to_matrix, to_array_1d, to_array_2d
#### Intended Effect:

Help with vectorization, etc.
#### How to Verify:

Test were added trying to cover all aspects.
#### Side Effects:

None that I know. Backward-compatibility with the already existent to_vector is preserved.
#### Documentation:

I judged that it was better to create a new chapter for mixed operations.
#### Reviewer Suggestions:

Bob Carpenter

### CODE REVIEW

**Comment by ziyuang** [comment]
Has this been reflected in the documentation? For example I don't see 
```
matrix to_matrix(vector, int, int);
matrix to_matrix(row_vector, int, int);
matrix to_matrix(real[], int, int);
```
in [Stan Reference 2.10.0, page 576](https://github.com/stan-dev/stan/releases/download/v2.10.0/stan-reference-2.10.0.pdf):

to_matrix

**Comment by bob-carpenter** [comment]
Are you saying there are functions that are available and not in the doc or the other way around?  If so, or if there are more functions you want, would you mind clarifying and ideally, opening a new issue?  Thanks.

**Comment by ziyuang** [comment]
@bob-carpenter I meant the functions discussed here (`matrix to_matrix(vector, int, int)`, `matrix to_matrix(row_vector, int, int)`, and `matrix to_matrix(real[], int, int)`), which seem already added to Stan, are not available, and cannot be found in the documentation.

**Comment by bob-carpenter** [comment]
OK, I moved the disucssion of the issue @ziyuang brings up to its own open issue:  https://github.com/stan-dev/stan/issues/1956

**Pull request merged**
