### PR TITLE
Feature/issue 1441 math namespace

### PR DESCRIPTION
**Pull request by syclik**
#### Summary:

Merges `stan::prob` and `stan::agrad` namespaces into the `stan::math` namespace.

#### Intended Effect:

Makes it easier to use the Stan Math library. It's now just one namespace.

#### How to Verify:

There should be no `namespace prob` or `namespace agrad` in the code base.

All tests pass.

#### Side Effects:

N/A.

#### Documentation:

I'll update the agrad paper appropriately. I'll also update the wiki page when this is merged.

#### Reviewer Suggestions:

Anyone. This is going to be hard to inspect due to the volume, but it was straightforward.

Personally, I think this should be merged as soon as it passes.

### CODE REVIEW

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by bob-carpenter** [comment]
Looks great.

Moving forward, we'll probably want to simplify the code by getting rid of all the explicit `stan::math::` and using statements that are no longer necessary now that everything's in the same namespace.

**Comment by syclik** [comment]
Thanks. I just merged. Yes, we'll do that at some point.

**Pull request merged**
