### PR TITLE
Feature/2418 manual ref html

### PR DESCRIPTION
**Pull request by bob-carpenter**
#### Submission Checklist

- [x] Declare copyright holder and open-source license: see below

#### Summary

Defines a bookdown document for the reference manual.  

Remove the reference manual from the user's guide and reference manual, renaming it.  Included reference from user's guide to new reference manual.

#### Intended Effect

Make it easy to edit and search our manuals.  The rest of the manual will get broken out in the same way.

#### How to Verify

Generate the new manual using the included R script.

#### Side Effects

The manual is no longer self-contained as a reference and user's guide.

#### Code

Nope, just doc.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by jgabry** [comment]
Thanks Bob! This is going to be really helpful.

**Comment by bob-carpenter** [comment]
This is just step 1.  It's just pulling the reference manual out.  When we pull the function reference out, we'll coordinate to make sure it's useful for R/RStudio.

**Comment by mitzimorris** [comment]
script depends on package "bookdown".
changed Rscript command:

```
Rscript --default-packages=bookdown -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
```
this works.

similarly, if building via RStudio, you must first load the bookdown library before knitting gitbook.

**Comment by mitzimorris** [comment]
gitbook version of manual also depends on pandoc-citeproc

on my mac (High Sierra, osx 10.13), I used homebrew and installed latest pandoc as well as pandoc-citeproc.  not sure, but I think homebrew messed up local fonts for latex - I had to reinstall lucida fonts, also did a total reinstall of MacTeX.

**Comment by bob-carpenter** [comment]
I'll re-open this when all the doc's split apart.

**Pull request closed without merging**
