### PR TITLE
Bugfix/issue 2576 Address segfault in optimize exponential model

### PR DESCRIPTION
**Pull request by roualdes**
#### Submission Checklist

- [x] Run unit tests: `./runTests.py src/test/unit/optimization`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary

Provide a fix to the segfault found in optimizing a simple exponential model, issue https://github.com/stan-dev/stan/issues/2576.

The line https://github.com/stan-dev/stan/blob/cf5a69f2bb0ac4def33792d582b7ee417cf95ab7/src/stan/optimization/bfgs_linesearch.hpp#L243 can have a non-zero return, inducing an infinite loop between the while loop condition and `continue`.  My solution provides two conditions to exit this while loop.  

1) A maximum number of line search iterations, which defaults to 20 (per outer lbfgs iteration).  The number 20 was chosen to match the Python package [Scipy](https://docs.scipy.org/doc/scipy-0.18.1/reference/optimize.minimize-lbfgsb.html#optimize-minimize-lbfgsb)'s `scipy.optimize.minimize(..., method="L-BFGS-B")` maximum number of line search iterations argument `maxls`. 

2) A maximum number of line search restarts, as I've called them, which defaults to 10 (per line search iteration).  When `func` is evaluated and it fails (`ret != 0`), `alpha1` is updated, a restart is incremented, and then `func` is evaluated at a new `x1`, hence a line search iteration is restarted at a new `x1`.  My thinking is that we shouldn't put up with `func` if it can't evaluate correctly for 10 calls in a row.  Such restarts should not count as a proper line search iteration.  Nor should the restarts carry forward to future line search iterations, hence the restart incrementer is set to 0 upon a successful evaluation of `func`.

#### Intended Effect

Make Stan's lbfgs algorithm more robust to ill specified models.

#### How to Verify

Issue https://github.com/stan-dev/stan/issues/2576 provides an example that previously made Stan segfault.  Stan now exits with the error message
```
Optimization terminated with error: 
  Line search failed to achieve a sufficient decrease, no more progress can be made
``` 
which matches `scipy.optimize.minimize`'s error message for the equivalent model.  Hence, Stan and `scipy.optimize.minimize` now have the same behavior on the proposed model.

Should I add a test for the model provided in issue https://github.com/stan-dev/stan/issues/2576 as a bad model, for which Stan should appropriately fail?

#### Side Effects

None intended.

#### Documentation

Add inline documentation for the new argument to `src/stan/optimization/bfgs_linesearch.hpp
:WolfeLineSearch`, which is handed down from `/src/stan/optimization/bfgs.hpp`.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): California State University, Chico

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by mitzimorris** [comment]
> Should I add a test for the model provided in issue #2576 as a bad model, for which Stan should appropriately fail?

yes, please.

**Comment by roualdes** [comment]
@mitzimorris When you get a minute, would you mind opining about the failures I'm seeing on travis?  None of the errors seem related to my changes, and I can't reproduce the errors.  

Builds 2808.1 - 2808.8 offer "c++/4.8/cstdio:120:11: error: no member named 'gets' in the global namespace", and builds 2808.11 - 2808.16 fail with "test-models/good/X.hpp: No such file or directory" for various files X.  

I didn't see any obvious comments about such issues on discourse or in the issues/pulls tabs.  Maybe it's a spill over from the latest efforts on Make files?  Maybe a simple restart will help?  That's all I could come up with.  Thanks for your time.

**Comment by mitzimorris** [comment]
I checked out your branch and merged w/ develop, make tests are running locally no problem.
can't push to your repo - perhaps you could see if this does anything?

**Comment by syclik** [comment]
@roulades: that does sound like something that could have been trigger by
the make stuff.

First, can we see if merging the latest develop fixes it? If it doesn't,
please ping me again and I'll see if the Travis yml file wasn't correct.

**Comment by syclik** [comment]
It definitely is part of the make stuff. I'll work on fixing it today.

**Comment by roualdes** [comment]
Thanks to you both for looking into this.  Once PR https://github.com/stan-dev/stan/pull/2649 goes through, I'll merge and push updates.

**Comment by roualdes** [comment]
Please note that I've updated (edited) the original post to better describe my latest updates to this PR.  Thanks.

**Comment by mitzimorris** [comment]
@roualdes please let us know when this is ready for code review.

**Comment by bob-carpenter** [comment]
Unless a PR is flagged as a work-in-progress, we should review and merge as soon as tests pass.

**Comment by roualdes** [comment]
Thanks @mitzimorris

**Pull request merged**
