### PR TITLE
adds serializer headers to model header

### PR DESCRIPTION
**Pull request by SteveBronder**
#### Submission Checklist

- [x] Run unit tests: `./runTests.py src/test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary

We forgot to add the header includes for the serializer/deserializer in the `model_header.hpp`

#### Intended Effect

Have the model know it can use these two classes

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
This changes the math submodule. The actual change is good.

**Review by rok-cesnovar — APPROVED** [review]

**Comment by SteveBronder** [comment]
Ty!

**Comment by SteveBronder** [comment]
@bbbales2 @rok-cesnovar I need an adult to click the button

**Comment by rok-cesnovar** [comment]
image

I dont get it ...

**Comment by SteveBronder** [comment]
Yeah like at one point I know I was able to click the button, maybe some gamma rays from the sun keep flipping the bits on the github servers and not giving me access.

**Comment by rok-cesnovar** [comment]
I gave you read permissions and then put write permissions back. Maybe we tricked those gamma rays.

**Pull request merged**
