### PR TITLE
Remove stanc2

### PR DESCRIPTION
**Pull request by rok-cesnovar**
#### Summary

Removes stanc2 and all its makefile logic

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Rok Češnovar

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
The only remaining file in src/stan/lang is `rethrow_located.hpp` which was not really a part of stanc2 and should 
have been in the model namespace in the first place (see https://github.com/stan-dev/stan/issues/1448). Its used in the generated code so we should not remove it.

Moving that file to /model is still something we will need to do at some point but that needs to be 
coordinated with rstan, maybe pystan as well but I dont think so.

**Review by syclik — COMMENTED** [review]
I looked through the makefile parts and it looks good. Should I approve? Or does someone else want to look at the rest?

**Comment by hsbadr** [comment]
> The only remaining file in src/stan/lang is `rethrow_located.hpp` which was not really a part of stanc2 and should
> have been in the model namespace in the first place (see #1448). Its used in the generated code so we should not remove it.
> 
> Moving that file to /model is still something we will need to do at some point but that needs to be
> coordinated with rstan, maybe pystan as well but I dont think so.

This affects [a single line](https://github.com/hsbadr/rstan/blob/df5b9ecce5973368a2a02aea9d7f90a3c88690eb/rstan/rstan/R/doctor_cppcode.R#L237) in `rstan`.

**Comment by rok-cesnovar** [comment]
> I looked through the makefile parts and it looks good. 

Thanks!

> This affects a single line in rstan.

Yes the code fix is simple, the larger issue there is CRAN and the fact that rstan is split in 2 packages and when upgrading stanheaders we would come to the situation:

`old rstan - old location, new stan headers - new location`

I dont want to give more issues to rstan right now, we can fix this once once rstan is up to date on CRAN.

**Comment by rok-cesnovar** [comment]
> Should I approve? Or does someone else want to look at the rest?

The makefile changes are the tricky part that needs review, if there were problems with other changes it would be caught by tests.

**Comment by syclik** [comment]
Something that you can do is leave the header where it is and `#include` to the correct location for backwards compatibility. Then in future versions, we can remove the couple-line file completely after RStan and pystan are caught up.

**Comment by rok-cesnovar** [comment]
@syclik see https://github.com/stan-dev/stan/pull/3000/commits/00cf6a614f7925e926094c97c114006f226601ca for the changes.

Also, funny that this PR is number 3000 :)

**Comment by syclik** [comment]
Awesome! Just checked it. We need to let the devs know it’ll be removed eventually. Hopefully within a version or two, but at least it’s backwards compatible for now.

**Review by syclik — APPROVED** [review]
Thank you! 🙏🙏🙏

**Comment by rok-cesnovar** [comment]
Thank you for reviewing!

**Pull request merged**
