### PR TITLE
Bugfix/issue 2146 compound declare define matrix

### PR DESCRIPTION
**Pull request by mitzimorris**
#### Submisison Checklist

- [x] Run unit tests: `./runTests.py src/test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary

Fixed Stan lang grammar rules so that compound declaration/definition statements for matrix variables record variable definition during parsing.

#### Intended Effect

Compount declaration/definition statements work for matrix types.

#### How to Verify

Run the Stan compiler over test model src/test/test-models/good/declare-define-var-matrix-2.stan, which contains the following 2 matrix definition statements:

> transformed data {
>   matrix[2,3] m23;
>   matrix[2,3] yam23 = m23;
> }

Verify that the compiled model includes variable assignment statement as well as variable declaration:

>         // initialize undefined transformed variables to avoid seg fault on val access
>         stan::math::fill(m23,DUMMY_VAR__);
>         stan::math::fill(yam23,DUMMY_VAR__);
>         // assign variable definitions
>         stan::math::assign(yam23,m23);

#### Reviewer Suggestions

Daniel Lee

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Mitzi Morris

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
@mitzimorris, I'm finding some more odd behavior. If you look at the generated code by running this:
```
 make src/test/test-models/good/declare-define-conditional-op.hpp
```

you'll see duplication of the assignment when using the conditional.

**Comment by mitzimorris** [comment]
fixed logic for generator so that:

-  assignments with conditional op compile cleanly.
-  assignment happens once for each defined variable
- indentation in generated code is correct
- generated code is free of spurious comments

**Comment by syclik** [comment]
@mitzimorris, the local blocks are generating an extra set of curly braces.

**Comment by bob-carpenter** [comment]
@syclik Are the extra curly braces a new problem that needs to be fixed for this release?

**Comment by syclik** [comment]
I had the same thought. No, this is not something you introduced here.

**Comment by syclik** [comment]
We're just waiting on Travis.

**Pull request merged**
