### PR TITLE
Bump the development version

### PR DESCRIPTION
**Pull request by hsbadr**
#### Submission Checklist

- [X] Run unit tests: `./runTests.py src/test/unit`
- [X] Run cpplint: `make cpplint`
- [X] Declare copyright holder and open-source license: see below

#### Summary

Make sure that the development version is higher than the current stable release.

#### Intended Effect

N/A

#### How to Verify

N/A

#### Side Effects

N/A

#### Documentation

N/A

#### Copyright and Licensing

Hamada S. Badr <hamada.s.badr@gmail.com>

### CODE REVIEW

**Comment by bbbales2** [comment]
@hsbadr we're discussing the version bump thing over here: https://discourse.mc-stan.org/t/minor-versioning-after-release/19803

**Comment by hsbadr** [comment]
Thanks @bbbales2! Sorry, I haven't noticed that thread before, but I'll check it out. It's just inconsistent to have the development version lower the the stable release.

**Review by mitzimorris — COMMENTED** [review]
strongly object to the idea of putting dev version at 2.25.999
I don't see that it's going to hurt anything, but it's not standard practice anywhere else and I don't think versioning is the kind of thing that we should be innovating on.

**Comment by hsbadr** [comment]
> strongly object to the idea of putting dev version at 2.25.999
> I don't see that it's going to hurt anything, but it's not standard practice anywhere else and I don't think versioning is the kind of thing that we should be innovating on.

There's a discussion on this [here](https://discourse.mc-stan.org/t/minor-versioning-after-release/19803). I agree that we should use a standard versioning convention. But, the current loose versioning is inconsistent (the development version is at `2.24.0` after the stable release `2.25.0`).

We could append a 4th level `2.25.0.9000` like  in R or a suffix `-dev`, `-git`, or `-<commit_hash>`. What do you think?

**Review by rok-cesnovar — APPROVED** [review]
Looks good. Lets merge the fix we all agree on for now because the minor version currently is just wrong. For any other changes we need to have a broader agreement first.

**Comment by hsbadr** [comment]
JFYI. @rok-cesnovar @bbbales2 I expected any version bump (now, this https://github.com/stan-dev/stan/commit/3c51ea169f426cba92b069d2309051e84969c3bb from `release/v2.26.0-rc1`) to get automatically merged into `develop`.

**Comment by rok-cesnovar** [comment]
That is going to happen once the RC is accepted which will hopefully be next Tuesday.

**Comment by hsbadr** [comment]
> That is going to happen once the RC is accepted which will hopefully be next Tuesday.

Good luck and congratulations on the new release!

**Pull request merged**
