### PR TITLE
attempt at multi-normal-sufficient-log

### PR DESCRIPTION
**Pull request by jpritikin**
This compiles but explodes with a run-time error in boost::math::tools::promote_args. I guess I don't really understand the purpose of promote_args. What is the purpose of promote_args? How am I using it wrong? See any other obvious problems?

### CODE REVIEW

**Comment by bob-carpenter** [comment]
Your code's a bit of an outlier for our probability functions
because it's not using any vectorization.

promote_args is a template metaprogram --- it can't go wrong at runtime
because it doesn't do anything at runtime.

I can't find the boost doc for it other than its header, but the idea
is that the unit

  typename promote_args<T1,...,TN>::type

refers to the largest type of T1,...,TN.  For Stan, that'll be 
either double or a class type (such as agrad::var or agrad::fvar<T> for
some T).  For example,

  promote_args<var,double>::type =def= var
  promote_args<int,double,double>::type =def= double

I see you're also using our traits-based metaprogram 

  typename scalar_type<T_loc>::type

This pulls out the scalar type from a container (or just returns the type
if it's not a container).  For example,

  scalar_type<double>::type =def= double
  scalar_type<vector<double> >::type =def= double

I believe Daniel's about to pull the rug out from under you by
completely refactoring all the error handling, so you won't need that
"function" variable as of Stan 2.6.  If you can get this working
vs. 2.5, we can upgrade error handling for you.

I'd recommend "sampleMu" and "sampleSigma" over "dataMu" and "dataSigma"
for consistency.

You need to declare the size of y_minus_mu before trying to fill it or you'll
get a runtime error:

+                     Eigen::Matrix<typename 
+		      boost::math::tools::promote_args<typename scalar_type<T_d_loc>::type,
+						       typename scalar_type<T_loc>::type>::type,
+		      Eigen::Dynamic, 1> y_minus_mu;

My advice would be to get it working for double-based values then
generalize the types.

- Bob

**Comment by syclik** [comment]
The `function` variable will still be required. 

@jpritikin do you know which `promote_args` is blowing up? And can you verify that it's a compile-time error and not a run-time error as Bob's mentioned?

**Comment by jpritikin** [comment]
Alright, I got it working for doubles. When I try to use autodiff, it fails to compile. I commented out a bunch of code in the test file that demonstrates the problem. I suspect I'm doing something wrong with

    ss = ldlt_Sigma.solve(sampleSigma);

More hints please?

**Comment by syclik** [comment]
What's the error message?

**Comment by jpritikin** [comment]
```
In file included from lib/eigen_3.2.2/Eigen/Core:331:0,
                 from lib/eigen_3.2.2/Eigen/Dense:1,
                 from src/stan/math/matrix/Eigen.hpp:4,
                 from src/stan/agrad/rev/matrix/Eigen_NumTraits.hpp:6,
                 from src/stan/agrad/rev/matrix.hpp:4,
                 from src/test/unit/prob/distributions/multivariate/continuous/multi_normal_sufficient_test.cpp:2:
lib/eigen_3.2.2/Eigen/src/Core/SolveTriangular.h: In instantiation of ‘static void Eigen::internal::triangular_solver_selector<Lhs, Rhs, Side, Mode, 0, -1>::run(const Lhs&, Rhs&) [with Lhs = const Eigen::Matrix<double, -1, -1>; Rhs = Eigen::Matrix<stan::agrad::var, -1, -1>; int Side = 1; int Mode = 5]’:
lib/eigen_3.2.2/Eigen/src/Core/SolveTriangular.h:186:51:   required from ‘void Eigen::TriangularView<MatrixType, Mode>::solveInPlace(const Eigen::MatrixBase<OtherDerived>&) const [with int Side = 1; OtherDerived = Eigen::Matrix<stan::agrad::var, -1, -1>; _MatrixType = const Eigen::Matrix<double, -1, -1>; unsigned int _Mode = 5u]’
lib/eigen_3.2.2/Eigen/src/Core/TriangularMatrix.h:342:26:   required from ‘void Eigen::TriangularView<MatrixType, Mode>::solveInPlace(const Eigen::MatrixBase<OtherDerived>&) const [with OtherDerived = Eigen::Matrix<stan::agrad::var, -1, -1>; _MatrixType = const Eigen::Matrix<double, -1, -1>; unsigned int _Mode = 5u]’
lib/eigen_3.2.2/Eigen/src/Cholesky/LDLT.h:498:5:   required from ‘void Eigen::internal::solve_retval<Eigen::LDLT<MatrixType, _UpLo>, Rhs>::evalTo(Dest&) const [with Dest = Eigen::Matrix<stan::agrad::var, -1, -1>; _MatrixType = Eigen::Matrix<double, -1, -1>; int _UpLo = 1; Rhs = Eigen::Matrix<stan::agrad::var, -1, -1>]’
lib/eigen_3.2.2/Eigen/src/misc/Solve.h:51:5:   required from ‘void Eigen::internal::solve_retval_base<DecompositionType, Rhs>::evalTo(Dest&) const [with Dest = Eigen::Matrix<stan::agrad::var, -1, -1>; _DecompositionType = Eigen::LDLT<Eigen::Matrix<double, -1, -1>, 1>; Rhs = Eigen::Matrix<stan::agrad::var, -1, -1>]’
lib/eigen_3.2.2/Eigen/src/Core/ReturnByValue.h:61:7:   required from ‘void Eigen::ReturnByValue<Derived>::evalTo(Dest&) const [with Dest = Eigen::Matrix<stan::agrad::var, -1, -1>; Derived = Eigen::internal::solve_retval_base<Eigen::LDLT<Eigen::Matrix<double, -1, -1>, 1>, Eigen::Matrix<stan::agrad::var, -1, -1> >]’
lib/eigen_3.2.2/Eigen/src/Core/Assign.h:522:101:   [ skipping 3 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
lib/eigen_3.2.2/Eigen/src/Core/Matrix.h:190:34:   required from ‘Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>& Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::operator=(const Eigen::ReturnByValue<OtherDerived>&) [with OtherDerived = Eigen::internal::solve_retval_base<Eigen::LDLT<Eigen::Matrix<double, -1, -1>, 1>, Eigen::Matrix<stan::agrad::var, -1, -1> >; _Scalar = stan::agrad::var; int _Rows = -1; int _Cols = -1; int _Options = 0; int _MaxRows = -1; int _MaxCols = -1]’
src/stan/prob/distributions/multivariate/continuous/multi_normal_sufficient.hpp:64:10:   required from ‘T_covar stan::prob::multi_normal_sufficient_log(int, const T_d_loc&, const Eigen::Matrix<LhsScalar, -1, -1, 0>&, const T_loc&, const Eigen::Matrix<T_covar, -1, -1>&) [with bool propto = true; T_d_loc = Eigen::Matrix<stan::agrad::var, -1, 1>; T_d_covar = stan::agrad::var; T_loc = Eigen::Matrix<stan::agrad::var, -1, 1>; T_covar = stan::agrad::var]’
src/stan/prob/distributions/multivariate/continuous/multi_normal_sufficient.hpp:89:92:   required from ‘T_covar stan::prob::multi_normal_sufficient_log(int, const T_d_loc&, const Eigen::Matrix<T_d_covar, -1, -1>&, const T_loc&, const Eigen::Matrix<T_covar, -1, -1>&) [with T_d_loc = Eigen::Matrix<stan::agrad::var, -1, 1>; T_d_covar = stan::agrad::var; T_loc = Eigen::Matrix<stan::agrad::var, -1, 1>; T_covar = stan::agrad::var]’
src/test/unit/prob/distributions/multivariate/continuous/multi_normal_sufficient_test.cpp:52:96:   required from ‘test_model<T>::valueType test_model<T>::operator()(Eigen::Matrix<Scalar, -1, 1>&) const [with T = stan::agrad::var; test_model<T>::valueType = stan::agrad::var]’
src/stan/agrad/autodiff.hpp:103:29:   required from ‘void stan::agrad::gradient(const F&, const Eigen::Matrix<double, -1, 1>&, double&, Eigen::Matrix<double, -1, 1>&) [with F = test_model<stan::agrad::var>]’
src/test/unit/prob/distributions/multivariate/continuous/multi_normal_sufficient_test.cpp:65:37:   required from here
lib/eigen_3.2.2/Eigen/src/Core/SolveTriangular.h:103:128: error: no matching function for call to ‘Eigen::internal::triangular_solve_matrix<stan::agrad::var, long int, 1, 5, false, 0, 0>::run(const Index&, const Index&, const Scalar*, Eigen::Matrix<double, -1, -1>::Index, Eigen::PlainObjectBase<Eigen::Matrix<stan::agrad::var, -1, -1> >::Scalar*, Eigen::Matrix<stan::agrad::var, -1, -1>::Index, BlockingType&)’
       ::run(size, othersize, &actualLhs.coeffRef(0,0), actualLhs.outerStride(), &rhs.coeffRef(0,0), rhs.outerStride(), blocking);
                                                                                                                                ^
lib/eigen_3.2.2/Eigen/src/Core/SolveTriangular.h:103:128: note: candidate is:
In file included from lib/eigen_3.2.2/Eigen/Core:339:0,
                 from lib/eigen_3.2.2/Eigen/Dense:1,
                 from src/stan/math/matrix/Eigen.hpp:4,
                 from src/stan/agrad/rev/matrix/Eigen_NumTraits.hpp:6,
                 from src/stan/agrad/rev/matrix.hpp:4,
                 from src/test/unit/prob/distributions/multivariate/continuous/multi_normal_sufficient_test.cpp:2:
lib/eigen_3.2.2/Eigen/src/Core/products/TriangularSolverMatrix.h:48:24: note: static void Eigen::internal::triangular_solve_matrix<Scalar, Index, 1, Mode, Conjugate, TriStorageOrder, 0>::run(Index, Index, const Scalar*, Index, Scalar*, Index, Eigen::internal::level3_blocking<Scalar, Scalar>&) [with Scalar = stan::agrad::var; Index = long int; int Mode = 5; bool Conjugate = false; int TriStorageOrder = 0]
 EIGEN_DONT_INLINE void triangular_solve_matrix<Scalar,Index,OnTheLeft,Mode,Conjugate,TriStorageOrder,ColMajor>::run(
                        ^
lib/eigen_3.2.2/Eigen/src/Core/products/TriangularSolverMatrix.h:48:24: note:   no known conversion for argument 3 from ‘const Scalar* {aka const double*}’ to ‘const stan::agrad::var*’
In file included from lib/eigen_3.2.2/Eigen/Core:331:0,
                 from lib/eigen_3.2.2/Eigen/Dense:1,
                 from src/stan/math/matrix/Eigen.hpp:4,
                 from src/stan/agrad/rev/matrix/Eigen_NumTraits.hpp:6,
                 from src/stan/agrad/rev/matrix.hpp:4,
                 from src/test/unit/prob/distributions/multivariate/continuous/multi_normal_sufficient_test.cpp:2:
lib/eigen_3.2.2/Eigen/src/Core/SolveTriangular.h: In instantiation of ‘static void Eigen::internal::triangular_solver_selector<Lhs, Rhs, Side, Mode, 0, -1>::run(const Lhs&, Rhs&) [with Lhs = const Eigen::Transpose<const Eigen::Matrix<double, -1, -1> >; Rhs = Eigen::Matrix<stan::agrad::var, -1, -1>; int Side = 1; int Mode = 6]’:
lib/eigen_3.2.2/Eigen/src/Core/SolveTriangular.h:186:51:   required from ‘void Eigen::TriangularView<MatrixType, Mode>::solveInPlace(const Eigen::MatrixBase<OtherDerived>&) const [with int Side = 1; OtherDerived = Eigen::Matrix<stan::agrad::var, -1, -1>; _MatrixType = const Eigen::Transpose<const Eigen::Matrix<double, -1, -1> >; unsigned int _Mode = 6u]’
lib/eigen_3.2.2/Eigen/src/Core/TriangularMatrix.h:342:26:   required from ‘void Eigen::TriangularView<MatrixType, Mode>::solveInPlace(const Eigen::MatrixBase<OtherDerived>&) const [with OtherDerived = Eigen::Matrix<stan::agrad::var, -1, -1>; _MatrixType = const Eigen::Transpose<const Eigen::Matrix<double, -1, -1> >; unsigned int _Mode = 6u]’
lib/eigen_3.2.2/Eigen/src/Cholesky/LDLT.h:524:5:   required from ‘void Eigen::internal::solve_retval<Eigen::LDLT<MatrixType, _UpLo>, Rhs>::evalTo(Dest&) const [with Dest = Eigen::Matrix<stan::agrad::var, -1, -1>; _MatrixType = Eigen::Matrix<double, -1, -1>; int _UpLo = 1; Rhs = Eigen::Matrix<stan::agrad::var, -1, -1>]’
lib/eigen_3.2.2/Eigen/src/misc/Solve.h:51:5:   required from ‘void Eigen::internal::solve_retval_base<DecompositionType, Rhs>::evalTo(Dest&) const [with Dest = Eigen::Matrix<stan::agrad::var, -1, -1>; _DecompositionType = Eigen::LDLT<Eigen::Matrix<double, -1, -1>, 1>; Rhs = Eigen::Matrix<stan::agrad::var, -1, -1>]’
lib/eigen_3.2.2/Eigen/src/Core/ReturnByValue.h:61:7:   required from ‘void Eigen::ReturnByValue<Derived>::evalTo(Dest&) const [with Dest = Eigen::Matrix<stan::agrad::var, -1, -1>; Derived = Eigen::internal::solve_retval_base<Eigen::LDLT<Eigen::Matrix<double, -1, -1>, 1>, Eigen::Matrix<stan::agrad::var, -1, -1> >]’
lib/eigen_3.2.2/Eigen/src/Core/Assign.h:522:101:   [ skipping 3 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
lib/eigen_3.2.2/Eigen/src/Core/Matrix.h:190:34:   required from ‘Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>& Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::operator=(const Eigen::ReturnByValue<OtherDerived>&) [with OtherDerived = Eigen::internal::solve_retval_base<Eigen::LDLT<Eigen::Matrix<double, -1, -1>, 1>, Eigen::Matrix<stan::agrad::var, -1, -1> >; _Scalar = stan::agrad::var; int _Rows = -1; int _Cols = -1; int _Options = 0; int _MaxRows = -1; int _MaxCols = -1]’
src/stan/prob/distributions/multivariate/continuous/multi_normal_sufficient.hpp:64:10:   required from ‘T_covar stan::prob::multi_normal_sufficient_log(int, const T_d_loc&, const Eigen::Matrix<LhsScalar, -1, -1, 0>&, const T_loc&, const Eigen::Matrix<T_covar, -1, -1>&) [with bool propto = true; T_d_loc = Eigen::Matrix<stan::agrad::var, -1, 1>; T_d_covar = stan::agrad::var; T_loc = Eigen::Matrix<stan::agrad::var, -1, 1>; T_covar = stan::agrad::var]’
src/stan/prob/distributions/multivariate/continuous/multi_normal_sufficient.hpp:89:92:   required from ‘T_covar stan::prob::multi_normal_sufficient_log(int, const T_d_loc&, const Eigen::Matrix<T_d_covar, -1, -1>&, const T_loc&, const Eigen::Matrix<T_covar, -1, -1>&) [with T_d_loc = Eigen::Matrix<stan::agrad::var, -1, 1>; T_d_covar = stan::agrad::var; T_loc = Eigen::Matrix<stan::agrad::var, -1, 1>; T_covar = stan::agrad::var]’
src/test/unit/prob/distributions/multivariate/continuous/multi_normal_sufficient_test.cpp:52:96:   required from ‘test_model<T>::valueType test_model<T>::operator()(Eigen::Matrix<Scalar, -1, 1>&) const [with T = stan::agrad::var; test_model<T>::valueType = stan::agrad::var]’
src/stan/agrad/autodiff.hpp:103:29:   required from ‘void stan::agrad::gradient(const F&, const Eigen::Matrix<double, -1, 1>&, double&, Eigen::Matrix<double, -1, 1>&) [with F = test_model<stan::agrad::var>]’
src/test/unit/prob/distributions/multivariate/continuous/multi_normal_sufficient_test.cpp:65:37:   required from here
lib/eigen_3.2.2/Eigen/src/Core/SolveTriangular.h:103:128: error: no matching function for call to ‘Eigen::internal::triangular_solve_matrix<stan::agrad::var, long int, 1, 6, false, 1, 0>::run(const Index&, const Index&, const Scalar*, Eigen::TransposeImpl<const Eigen::Matrix<double, -1, -1>, Eigen::Dense>::Index, Eigen::PlainObjectBase<Eigen::Matrix<stan::agrad::var, -1, -1> >::Scalar*, Eigen::Matrix<stan::agrad::var, -1, -1>::Index, BlockingType&)’
       ::run(size, othersize, &actualLhs.coeffRef(0,0), actualLhs.outerStride(), &rhs.coeffRef(0,0), rhs.outerStride(), blocking);
                                                                                                                                ^
lib/eigen_3.2.2/Eigen/src/Core/SolveTriangular.h:103:128: note: candidate is:
In file included from lib/eigen_3.2.2/Eigen/Core:339:0,
                 from lib/eigen_3.2.2/Eigen/Dense:1,
                 from src/stan/math/matrix/Eigen.hpp:4,
                 from src/stan/agrad/rev/matrix/Eigen_NumTraits.hpp:6,
                 from src/stan/agrad/rev/matrix.hpp:4,
                 from src/test/unit/prob/distributions/multivariate/continuous/multi_normal_sufficient_test.cpp:2:
lib/eigen_3.2.2/Eigen/src/Core/products/TriangularSolverMatrix.h:48:24: note: static void Eigen::internal::triangular_solve_matrix<Scalar, Index, 1, Mode, Conjugate, TriStorageOrder, 0>::run(Index, Index, const Scalar*, Index, Scalar*, Index, Eigen::internal::level3_blocking<Scalar, Scalar>&) [with Scalar = stan::agrad::var; Index = long int; int Mode = 6; bool Conjugate = false; int TriStorageOrder = 1]
 EIGEN_DONT_INLINE void triangular_solve_matrix<Scalar,Index,OnTheLeft,Mode,Conjugate,TriStorageOrder,ColMajor>::run(
                        ^
lib/eigen_3.2.2/Eigen/src/Core/products/TriangularSolverMatrix.h:48:24: note:   no known conversion for argument 3 from ‘const Scalar* {aka const double*}’ to ‘const stan::agrad::var*’
In file included from src/stan/prob/distributions/multivariate/continuous/multi_normal_sufficient.hpp:15:0,
                 from src/test/unit/prob/distributions/multivariate/continuous/multi_normal_sufficient_test.cpp:4:
```

**Comment by syclik** [comment]
Check the LDLT_factor_test for how we were able to use solve. It doesn't
look like the solve in place works for that.

The other thing to check for is the use of *'s. I'm not sure anything
should be 'const double*' as opposed to 'const double'.

Good luck. You're getting into Eigen template messages -- I don't think
I've got much more time to help you on this. My only suggestion: build up
from something that works.

**Comment by mbrubake** [comment]
I suspect this is due to mixed types, if not as it is the code won't work for mixed types.  Try using ```mdivide_left_ldlt(ldlt_sigma,sampleSigma)``` instead of ```ldlt_sigma.solve(sampleSigma)```.  You'll also need to use a type promotion for the type of ss since it could be either T_cover or T_d_covar.

**Comment by jpritikin** [comment]
sampleSigma has type T_d_covar but this is a covariance of data which is constant. Is there an API to do this division without considering sampleSigma's derivatives?

**Comment by mbrubake** [comment]
sampleSigma's derivatives won't be considered, the autodiff code for ldlt knows how to handle solving a system with a constant right hand side.  The result (ie, what goes in ss) still needs to be promoted though.

**Comment by jpritikin** [comment]
Wow, it's working now. Why even allow different types of sampleSigma and Sigma?

**Comment by bob-carpenter** [comment]
In Stan, data becomes a double type and parameters become 
autodiff types.  Allowing flexible typing in arguments is
more efficient than just promoting everything to an autodiff
type.  We used to just do matrix math by autodiffing the
algorithms and promoting everything, but it's much faster
the way it is now.

- Bob

**Comment by jpritikin** [comment]
OK, what's the next step? Do I need to add more tests?

**Comment by bob-carpenter** [comment]
Yes, it needs thorough tests as well as doc in the manual (though
I can add that for you given defs).  Daniel wrote a testing
framework and you should coordinate with him on how to use it.

When it's tested, you probably want to use some of our traits-based
tricks to drop any terms that are constant.  For instance, ss
in your code only needs to be computed if Sigma or sampleSigma is
an autodiff variable.

I don't think it's worth worrying about general vector arguments.

The main problem with this density is that it's not going to
be usable with the sampling statements.  You'll be able to write

  size ~ multi_normal_sufficient(sample_mu, sample_Sigma, mu, Sigma);

What we'd really want is something like:

  (sample_mu, sample_Sigma) ~ multi_normal_sufficient(mu, Sigma, size);

but Stan's not expressive enough to let you do that.

I also don't see how you could write an RNG for this density --- it'd
need to generate (sample_mu, sample_Sigma) pairs.

- Bob

**Comment by bob-carpenter** [comment]
Joshua:  If you still want to go ahead with this, you can coordinate with Daniel on getting the tests in.  I think it would be good to have for a number of applications.

**Comment by jpritikin** [comment]
@bob-carpenter The urgency is a bit less because I got it working and we're using it. What exactly do you need from me to get it merged with the main repo?

**Comment by bob-carpenter** [comment]
Testing and doc, though if you can coordinate with Daniel
on testing I can write the doc for the manual.

- Bob

**Comment by syclik** [comment]
Moved to https://github.com/stan-dev/math/pull/40

**Comment by syclik** [comment]
@jpritikin, I'm really sorry -- I didn't realize this was an open PR when we split out Math from Stan.

Would you mind letting me know who owns the copyright and that it's ok licensing it as Stan's license (BSD 3-clause)? If so, I'll copy this over to the math repo and figure out what's left to do on the PR.

**Comment by jpritikin** [comment]
@syclik I own the copyright. Yes, it's fine to license it as BSD 3-clause. That would be great if you can salvage the PR. Thanks.

**Comment by syclik** [comment]
Alright, I'm working on a branch in stan-dev/math called feature/issue-38-multi_normal_sufficient. It's not working yet, but we'll get it up and running.

**Pull request closed without merging**
