### PR TITLE
Removes the prob_grad base class for model_base

### PR DESCRIPTION
**Pull request by SteveBronder**
#### Submission Checklist

- [x] Run unit tests: `./runTests.py src/test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary

This just removes `prob_grad` as a base class for `model_base` which I think we've been meaning to do and cleans things up a little bit.

#### Intended Effect

Just tidying

#### How to Verify

The test models should run successfully

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Steve Bronder

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by wds15** [comment]
Pinging @hsbadr and @bgoodri for their attention. Changing these base classes will possibly cause hiccups with rstan given that on a binary levels things brake.

**Comment by hsbadr** [comment]
> Changing these base classes will possibly cause hiccups with rstan given that on a binary levels things brake.

Yes, I remember that the installation of `rstan`/`rstanarm` failed when I merged this PR into my testing workflow. I didn't post the error(s) because it's already failing here, not ready yet.

**Comment by bob-carpenter** [comment]
Let me know if you need me to review this one.

**Comment by bgoodri** [comment]
Can someone explain a bit more as to why we want to do this? If Stan is going to be backward incompatible with the previous point release, we should at least be gaining something like performance or extensibility. These changes where someone renames something because they don't like the old name or otherwise alters something that has been working fine for more than a decade just means I have to figure out how to restore the original convention.

**Comment by bob-carpenter** [comment]
@bgoodri makes a good point.  We don't want to be cleaning things up a little bit if it's going to induce headaches for our interface devs.  What is the reason to get rid of the base class here?

**Comment by bob-carpenter** [comment]
Also, @SteveBronder, is there an issue that goes with this PR?

P.S.  It's `prob_grad`, not `prog_grad`.  I edited the issue.

**Comment by SteveBronder** [comment]
Oh if it's going to make issues for backwards compatability then no I don't really see a reason to do this

**Pull request closed without merging**
