### PR TITLE
Bugfix/2529 map rect disallow rng

### PR DESCRIPTION
**Pull request by mitzimorris**
#### Submission Checklist

- [x] Run unit tests: `./runTests.py src/test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary
Added check to parser to check that map_rect doesn't call _rng or _lp functions.

#### Intended Effect
Prevent generation of code that can't compile.

#### How to Verify
Added test models and unit tests to `src/test/unit/lang/parser/map_rect_test.cpp`

#### Side Effects
Added EOL to map_rect error messages.

#### Documentation
Didn't change existing documentation.  Should we call attention to things you can't do?

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):
Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by seantalts** [comment]
Looks like we might need to edit the CmdStan makefiles for sundials too? @yizhang-cae @syclik http://d1m1s1b1.stat.columbia.edu:8080/blue/organizations/jenkins/CmdStan/detail/develop/135/pipeline

**Comment by yizhang-cae** [comment]
@seantalts, yes
https://github.com/stan-dev/cmdstan/pull/609

**Comment by syclik** [comment]
@mitzimorris, was this the pull request that was failing upstream? If so, I won't dig into it until everything gets resolved.

**Comment by mitzimorris** [comment]
@syclik yes.

**Comment by seantalts** [comment]
passing now

**Comment by mitzimorris** [comment]
@VMatthijs - another PR hanging out waiting for code review.   this one has minimal changes - added one new check,  more unit tests.  also cleaned up a stray typo, added end-of-line to error message.

**Comment by mitzimorris** [comment]
you are correct - given rules for written language, it should be "a".  however, when spoken aloud, native speakers would probably say "an" rather than "a" because "_rng" is pronounced "arr-en-gee".   will correct error message.  many thanks for reviewing this.

**Comment by bob-carpenter** [comment]
"a" vs. "an" is by pronunciation, not by spelling.  So the original "an" is correct here.

**Comment by mitzimorris** [comment]
Bob is correct.  ;-)

**Pull request merged**
