### PR TITLE
Update Boost to 1.55.0; remove Eigen 3.2.0 (unused -- we have 3.2.2)

### PR DESCRIPTION
**Pull request by syclik**
#### Summary:

Update Boost to 1.55.0.
Remove unused Eigen 3.2.0.
Update makefile to point to Boost 1.55.0.

#### Intended Effect:

See summary. No code changes.

#### How to Verify:

Run tests.

#### Side Effects:

Only things brought on by the upgrade to Boost.

#### Documentation:

None.

#### Reviewer Suggestions: 

Anyone.

### CODE REVIEW

**Comment by syclik** [comment]
I stopped everything. Jenkins was acting up. I'll get it back on the
testing queue soon.

**Comment by syclik** [comment]
This also fixes #404.

**Comment by bob-carpenter** [comment]
This is another one that's impossible to view on the web, but assuming it's just some make tweaks and a boost lib update, I'm fine with it if it passes tests.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Pull request merged**
