### PR TITLE
Add virtual function model_compile_info to the model_base.hpp

### PR DESCRIPTION
**Pull request by rok-cesnovar**
#### Submission Checklist

- [x] Run unit tests: `./runTests.py src/test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary

Adds the virtual function model_compile_info to the model_base, which will be used to retrieve the info about the compiler version and flags used.

Related Cmdstan PR https://github.com/stan-dev/cmdstan/pull/896 and issue https://github.com/stan-dev/cmdstan/issues/887

Stanc3 now adds this function to the model:

```cpp
  std::vector<std::string> model_compile_info() const {
    std::vector<std::string> stanc_info;
    stanc_info.push_back("stanc_version = stanc3 e010e06c");
    stanc_info.push_back("stancflags = --warn-pedantic");
    return stanc_info;
  }
```
This PR adds a virtual function `model_compile_info()`  and the generation of the same function (sans flags) in order to still support compiling models with `STANC2=true`. As compiling with STANC2 is only for debugging purpose, I did not implement the stancflags functionality for stanc2 as well.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):
Rok Češnovar, Univ. of Ljubljana

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by mitzimorris** [comment]
@rok-cesnovar - branch names should include issue number

**Comment by rok-cesnovar** [comment]
I keep forgetting on the branch names, sorry. I made the branches before the issues and then forgot to rename them.
I also got really used to the Github CLI, where you can just do `gh pr checkout 2932`.

Anyhow this should be ready for review. I added the generation of the model_compile_info to stanc2 for 2 reasons:
- the tests still work with stanc2
- compiling with STANC2=true would break

The relevant issue is https://github.com/stan-dev/cmdstan/issues/887

**Comment by bob-carpenter** [comment]
Is there a reason this can't be a regular function instead of a virtual one?  It just seems like something that would fit into the basic CRTP structure of the generated model class.

**Comment by rok-cesnovar** [comment]
> Is there a reason this can't be a regular function instead of a virtual one? It just seems like something that would fit into the basic CRTP structure of the generated model class.

If I dont put the virtual method in model_base I get the following error

```
In file included from src/cmdstan/main.cpp:1:0:
src/cmdstan/command.hpp: In function ‘int cmdstan::command(int, const char**)’:
src/cmdstan/command.hpp:131:51: error: ‘class stan::model::model_base’ has no member named ‘model_compile_info’
     std::vector<std::string> compile_info = model.model_compile_info();
                                                   ^~~~~~~~~~~~~~~~~~
```

@bob-carpenter would you mind reviewing this? I updated the top-level comment with more details.

**Comment by rok-cesnovar** [comment]
Anyone up for reviewing this?

**Review by mitzimorris — APPROVED** [review]
LGTM!

**Pull request merged**
