### PR TITLE
Feature/n tests

### PR DESCRIPTION
**Pull request by bgoodri**
This PR makes it possible to configure (via make/local) the value of N_TESTS, which was formerly a global constant in src/test/unit-distribution/generate_tests.cpp . By setting N_TESTS to a value higher than the default (75), you can get more distribution tests per file and thus have to compile fewer files, although each file is more intensive on the compiler and may overload g++-4.6 on Windows. By setting N_TESTS <= 0, then 1 - N_TESTS is interpreted as the number of files to create for that distribution and scalar type, so setting N_TESTS = 0 will put all the tests into one file. This appears to be feasible for most (but not all distributions) with clang++-3.6

### CODE REVIEW

**Comment by syclik** [comment]
@bgoodri, sorry for being so pedantic, but can you open up an issue for this pull request?

Since there's so much index fiddling, I want to spot check the output to verify that every case is generated. But other than that, it looks ok.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by bgoodri** [comment]
This is now #1287 but the PR does not yet do a good job of making equally sized files when N_TESTS <= 0.

**Comment by syclik** [comment]
@bgoodri, it looks like bumping that number to 150 doesn't work properly on
the Jenkins machine (Mac OS X box). It got into a weird state that I
haven't seen before.

**Comment by syclik** [comment]
I'm still bothered by Jenkins failing with N_TESTS bumped up to 150. Before merging, I'm going to try that again.... if it fails, maybe there's a problem somewhere.

**Comment by syclik** [comment]
@bgoodri, I'm not sure how safe this pull request is. Jenkins gets into
some sort of weird state with this pull request. I can't even check the
output, it's gotten so large:
http://d1m1s1b1.stat.columbia.edu:8080/job/Stan%20Pull%20Request%20-%20Distribution%20Tests/151/console

Thoughts? I honestly don't know what's going on.

**Comment by syclik** [comment]
Here's part of the output:

...

clang++ -I src -isystem lib/eigen_3.2.2 -isystem lib/boost_1.55.0
-Wall -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE
-DBOOST_DISABLE_ASSERTS -pipe -Wno-unused-function
-Wno-tautological-compare -Wno-c++11-long-long -Wsign-compare
-ftemplate-depth=256    -O0 lib/gtest_1.7.0/src/gtest_main.cc
test/prob/bernoulli/bernoulli_logit_00000_generated_v.o
-DGTEST_USE_OWN_TR1_TUPLE -Wc++11-extensions -Wno-c++11-long-long
-isystem lib/gtest_1.7.0/include -isystem lib/gtest_1.7.0 -o
test/prob/bernoulli/bernoulli_logit_00000_generated_v test/libgtest.a
rm test/prob/bernoulli/bernoulli_00000_generated_ffd.o
test/prob/bernoulli/bernoulli_cdf_00000_generated_fv.o
test/prob/bernoulli/bernoulli_00000_generated_v.o
test/prob/bernoulli/bernoulli_cdf_log_00000_generated_ffd.o
test/prob/bernoulli/bernoulli_cdf_log_00000_generated_ffv.o
test/prob/bernoulli/bernoulli_cdf_00000_generated_ffd.o
test/prob/bernoulli/bernoulli_cdf_00000_generated_v.o
test/prob/bernoulli/bernoulli_logit_00000_generated_v.o
test/prob/bernoulli/bernoulli_00000_generated_ffv.o
test/prob/bernoulli/bernoulli_00000_generated_fd.o
test/prob/bernoulli/bernoulli_ccdf_log_00000_generated_ffd.o
test/prob/bernoulli/bernoulli_ccdf_log_00000_generated_ffv.o
test/prob/bernoulli/bernoulli_cdf_00000_generated_fd.o
test/prob/bernoulli/bernoulli_cdf_log_00000_generated_v.o
test/prob/bernoulli/bernoulli_ccdf_log_00000_generated_v.o
test/prob/bernoulli/bernoulli_logit_00000_generated_ffd.o
test/prob/bernoulli/bernoulli_cdf_00000_generated_ffv.o
test/prob/bernoulli/bernoulli_cdf_log_00000_generated_fd.o
test/prob/bernoulli/bernoulli_logit_00000_generated_ffv.o
test/prob/bernoulli/bernoulli_ccdf_log_00000_generated_fd.o
test/prob/bernoulli/bernoulli_logit_00000_generated_fv.o
test/prob/bernoulli/bernoulli_ccdf_log_00000_generated_fv.o
test/prob/bernoulli/bernoulli_cdf_log_00000_generated_fv.o
test/prob/bernoulli/bernoulli_logit_00000_generated_fd.o
test/prob/bernoulli/bernoulli_00000_generated_fv.o
test/prob/generate_tests src/test/prob/beta/beta_test.hpp 150
test/prob/generate_tests src/test/prob/beta/beta_test.hpp 150
test/prob/generate_tests src/test/prob/beta/beta_test.hpp 150
test/prob/generate_tests src/test/prob/beta/beta_test.hpp 150
test/prob/generate_tests src/test/prob/beta/beta_test.hpp 150
test/prob/generate_tests src/test/prob/beta/beta_test.hpp 150
test/prob/generate_tests src/test/prob/beta/beta_test.hpp 150
test/prob/generate_tests src/test/prob/beta/beta_test.hpp 150
test/prob/generate_tests src/test/prob/beta/beta_test.hpp 150
test/prob/generate_tests src/test/prob/beta/beta_test.hpp 150
warning: null character ignored [-Wnull-character]
warning: null character ignored [-Wnull-character]
<scratch space>:1:1: warning: null character ignored [-Wnull-character]
0
^
<scratch space>:1:2: warning: null character ignored [-Wnull-character]
0
 ^
<scratch space>:2:1: warning: null character ignored [-Wnull-character]
1
^
<scratch space>:2:2: warning: null character ignored [-Wnull-character]
1
 ^
<scratch space>:2:3: warning: null character ignored [-Wnull-character]
1<U+0000>
         ^
<scratch space>:3:1: warning: null character ignored [-Wnull-character]
0
^
<scratch space>:3:2: warning: null character ignored [-Wnull-character]
0
 ^
<scratch space>:3:3: warning: null character ignored [-Wnull-character]
0<U+0000>
         ^
<scratch space>:4:1: warning: null character ignored [-Wnull-character]
0
^
<scratch space>:4:2: warning: null character ignored [-Wnull-character]
0
 ^
<scratch space>:4:3: warning: null character ignored [-Wnull-character]
0<U+0000>
         ^
<scratch space>:5:1: warning: null character ignored [-Wnull-character]
1
^
<scratch space>:5:2: warning: null character ignored [-Wnull-character]
1
 ^
...

The last bit about 'warning: null character ignored' continues forever.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Pull request merged**
