### PR TITLE
Update submodule for the Stan Math Library

### PR DESCRIPTION
**Pull request by stan-buildbot**
#### Summary:

Updates the Math submodule to the current develop version, d544624.

#### Intended Effect:

The Stan Math Library `develop` branch has been updated.
This pull request updates the submodule for the Stan Math Library submodule to d544624.

#### Side Effects:

None.

#### Documentation:

None.

#### Reviewer Suggestions: 

None.

### CODE REVIEW

**Comment by bob-carpenter** [comment]
This one is unfortunately a real problem with `to_matrix`.  Anyone have time to take a look?

**Comment by bob-carpenter** [comment]
Also, a bunch of syntax warnings in the new `to_matrix` code:

http://d1m1s1b1.stat.columbia.edu:8080/job/Stan%20Pull%20Request%20-%20Tests%20-%20Integration/1219/warnings22Result/new/

The first actual error is here:

```
clang++ -I src -isystem lib/stan_math/lib/eigen_3.2.9 -isystem lib/stan_math/lib/boost_1.62.0 -isystem lib/stan_math/lib/cvodes_2.9.0/include -isystem lib/stan_math/ -Wall -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DFUSION_MAX_VECTOR_SIZE=12 -DNO_FPRINTF_OUTPUT -pipe  -Wno-unknown-warning-option -Wno-unused-function -Wno-tautological-compare -Wno-c++11-long-long -Wsign-compare -Wno-unused-local-typedef -ftemplate-depth=256   -c -O0 -include src/test/test-models/good/function-signatures/math/matrix/trace.hpp -o /dev/null test/test-model-main.cpp
In file included from <built-in>:175:
In file included from <command line>:6:
src/test/test-models/good/function-signatures/math/matrix/to_matrix.hpp:103:57: error: no matching function for call to 'to_matrix'
            stan::math::assign(transformed_data_matrix, to_matrix(d_array,2,3));
                                                        ^~~~~~~~~
lib/stan_math/stan/math/prim/mat/fun/to_matrix.hpp:16:5: note: candidate function template not viable: requires single argument 'matrix', but 3 arguments were provided
    to_matrix(Eigen::Matrix<T, R, C> matrix) {
    ^
lib/stan_math/stan/math/prim/mat/fun/to_matrix.hpp:23:5: note: candidate function template not viable: requires single argument 'vec', but 3 arguments were provided
    to_matrix(const std::vector< std::vector<T> > & vec) {
    ^
lib/stan_math/stan/math/prim/mat/fun/to_matrix.hpp:40:5: note: candidate function not viable: requires single argument 'vec', but 3 arguments were provided
    to_matrix(const std::vector< std::vector<int> > & vec) {
    ^
```

Looks like it may just be a missing include.

**Comment by seantalts** [comment]
jenkins, retest this please

**Comment by seantalts** [comment]
Update: It seems like the Stan Integration Tests pass when run on gelman-group-mac and fail when run on the iMac master. I'm digging into why that is so I can fix it.

**Comment by seantalts** [comment]
The problem seems to have been that some part of the release process left the `Stan Pull Request - Tests - Integration` Jenkins job in a bad state, just on the iMac master machine, and the job was failing whenever it ran there. The problem seemed to be a stan_math_2.14.0 directory left in stan/lib, which would have been perhaps okay except that that was registered as the working directory for the stan_math submodule in `.git/modules/lib/stan_math/config`, and so it was the one getting updated. Meanwhile, `lib/stan_math` was being used for compiles and had a ton of changes to the working directory. Some lessons here:
1. `git clean -x -d  -f` doesn't remove directories if they are repositories
1. the release process checks out submodules with a version # appended, and cleanup afterwards is non-trivial.

Things are back to a good state for this job. Once I learn the release process, I'll figure out the best way to prevent this kind of thing from happening in the future.

**Comment by syclik** [comment]
bah. Sorry about that.

**Pull request merged**
