### PR TITLE
Update performance test

### PR DESCRIPTION
**Pull request by syclik**
#### Summary:

Cleaned up performance test. Added documentation.

#### Intended Effect:

Added documentation for the performance test.
Replaced `Eigen::Matrix` with `std::vector`.
Hopefully this will be clearer to the next person that sees the test.

#### How to Verify:

Look at `src/test/performance/logistic_test.cpp`.
Run: `> ./runTests.py src/test/performance/logistic_test.cpp`

#### Side Effects:

None.

#### Documentation:

Updated documentation in code.

#### Reviewer Suggestions: 

@bob-carpenter

### CODE REVIEW

**Comment by syclik** [comment]
@bob-carpenter, mind reviewing this one? It doesn't need to test everything -- it's a change to our performance testing script. I also added an R plot script.

Once it's merged, I'll update Jenkins to do the right thing with regards to plotting.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by bob-carpenter** [comment]
This looks much better.  Thanks for updating.

**Comment by syclik** [comment]
I'm not sure why the distribution tests aren't working, but I just verified that it does work. I'll try to figure out why Jenkins isn't working as expected.

**Pull request merged**
