### PR TITLE
Bugfix/issue 2268 fix nuts classic comp err

### PR DESCRIPTION
**Pull request by betanalpha**
#### Submisison Checklist

- [x] Run unit tests: `./runTests.py src/test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary

Fixes some variants of `nuts_classic` addressing #2268 and added some tests that tries to instantiate each variant to avoid missing these errors in the future.

#### Intended Effect

Fix non-user-facing code that wouldn't compile.

#### How to Verify

./runTests.py src/test/unit/mcmc/hmc/nuts_classic/instantiation_test.cpp

#### Side Effects

None.

#### Documentation

None.

#### Reviewer Suggestions

Anyone.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by betanalpha** [comment]
Jenkins retest this please.

**Comment by betanalpha** [comment]
Am I interpreting this error log correctly?  Is Jenkins failing on some compiler warning, a warning that it is just interested in telling me? 

```
 [WARNINGS] Parsing warnings in console log with parser GNU C Compiler 4 (gcc)
[WARNINGS] Computing warning deltas based on reference build #1261
[WARNINGS] Ignore new warnings since this is the first valid build
[WARNINGS] Plug-in Result: Failed - <a href="warningsResult">1 warning</a> exceeds the threshold of 0 by 1
Build step 'Scan for compiler warnings' changed build result to FAILURE
Recording test results
Finished: FAILURE
```

**Comment by syclik** [comment]
File not found? 

d1m1s1b1.stat.columbia.edu:8080/job/Stan%20Pull%20Request%20-%20Tests%20-%20Unit/1263/warnings22Result/new/

**Comment by betanalpha** [comment]
Ah, thanks.  Didn't realize that compiler errors were reported outside of the console log.  Forgot to update the test makefile.

**Pull request merged**
