### PR TITLE
Feature/stan reference reorder

### PR DESCRIPTION
**Pull request by avehtari**
#### Summary
Reorder material in "Stan Modeling Language and Reference Manual"
Remove repetition.

New contents:
I Introduction
1. Overview

II Stan Modeling Language
2. Statements
3. Data Types and Variable Declarations
4. Expressions
5. Program Blocks
6. User-Defined Functions
7. Execution of a Stan Program

III Example Models and Programming Techniques
8. Regression Models
9. Time-Series Models
10. Missing Data & Partially Known Parameters
11. Truncated or Censored Data
12. Finite Mixtures
13. Measurement Error and Meta-Analysis
14. Latent Discrete Parameters
15. Sparse and Ragged Data Structures
16. Clustering Models
17. Gaussian Processes
18. Directions, Rotations, and Hyperspheres
19. Reparameterization & Change of Variables
20. Custom Probability Functions
21. User-Defined Functions
22. Solving Differential Equations
23. Problematic Posteriors
24. Optimizing Stan Code for Efficiency
25. Reproducibility
26. Model Building as Software Development

IV Inference
27. Bayesian Data Analysis
28. Markov Chain Monte Carlo Sampling
29. Penalized Maximum Likelihood Point Estimation
30. Bayesian Point Estimation
31. Variational Inference

V Algorithms & Implementations
32. Hamiltonian Monte Carlo Sampling
33. Transformations of Constrained Variables
34. Optimization Algorithms
35. Variational Inference
36. Diagnostic Mode

VI Built-In Functions
37. Void Functions
38. Integer-Valued Basic Functions
39. Real-Valued Basic Functions
40. Array Operations
41. Matrix Operations
42. Sparse Matrix Operations
43. Mixed Operations
44. Ordinary Differential Equation Solvers

VII Discrete Distributions
45. Conventions for Probability Functions
46. Binary Distributions
47. Bounded Discrete Distributions
48. Unbounded Discrete Distributions
49. Multivariate Discrete Distributions

VIII Continuous Distributions
50. Unbounded Continuous Distributions
51. Positive Continuous Distributions
52. Non-negative Continuous Distributions
53. Positive Lower-Bounded Probabilities
54. Continuous Distributions on [0, 1]
55. Circular Distributions
56. Bounded Continuous Probabilities
57. Distributions over Unbounded Vectors
58. Simplex Distributions
59. Correlation Matrix Distributions
60. Covariance Matrix Distributions

IX Stan Software Development
61. Software Development Lifecycle
62. Contributed Modules
63. Stan Program Style Guide

Appendices
A. Licensing
B. Stan for Users of BUGS
C. Modeling Language Syntax
D. Warning and Error Messages
E. Deprecated Features
F. Mathematical Functions

#### Intended Effect
Users will find more easily the relevant material.

#### How to Verify
Test with users.

#### Side Effects
Users used to the old order may need more time to find what they are looking for.

#### Documentation
Yes

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Aki Vehtari (copyright for work without external funding belongs to me).

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by bob-carpenter** [comment]
I like the new organization.  It'll set us up nicely for https://github.com/stan-dev/stan/issues/2103

Now that you've cleaned up the ordering, I'd like to go further and break "Example Models and Programming Techniques" into two parts, the first being chapters 8--18 and the second being 19--26.  I'd be inclined to put the programming techniques first and lead with modeling as software chapter, but I'm not that picky if you think it should go the other way.

**Comment by bob-carpenter** [comment]
We like to have an issue created first then include the issue number in the name of the branch.  That way, we can tell what feature gets implemented with each pull request.  No need to change this now, just a heads up for the future.

**Comment by bob-carpenter** [comment]
I'll clean this up.  I added the new part and will fix the broken references.

**Comment by bob-carpenter** [comment]
I started this task and am now very confused.   I'd like to set up a hangout or something to try to understand the bigger picture in this reorganization so that I can track where the content in the old manual landed in the new one.

* I like that it went from 585 to 506 pages, but I want to make sure nothing (that I think is) important got lost.  

* In tracking down missing references, I realized the problem is that there are whole missing chapters;  did the content get rolled in elsewhere?
    - Containers: Arrays, Vectors, and Matrices
    - Multiple Indexing and Range Indexing (some [all?] of this is now in the Optimizing Stan Code for Efficiency chapter, which seems like an odd choice to me as the indexing isn't any more efficient than looping)

* The natural order is to have the Expressions and Data Types chapter before the Statements chapter because statements depend on expressions and involve typing.  I'd very much like to order that back the way I have it if the internal changes weren't too dramatic.

* There is junk inserted at the end of chapters like
```
%%% Local Variables:
%%% mode: latex
%%% TeX-master: "stan-reference"
%%% End:
```
Did this come from some kind of LaTeX IDE or editor mode?  I'd rather not leave this stuff in our docs.

I would strongly suggest in the future creating an issue we can discuss before doing this much work.  I'm happy you did it here, I just want to do a bit of reordering and make sure nothing got dropped in the process.

**Comment by avehtari** [comment]
I'm not certain whether I should continue discussion here in the pull request, 
but since Bob wrote here, I'll answer to his comments here.

> I would strongly suggest in the future creating an issue we can discuss
> before doing this much work. I'm happy you did it here, I just want to do a
> bit of reordering and make sure nothing got dropped in the process.

I tried to initiate the discussion in Discourse, and then Bob wrote
 > We do take pull requests!
which I interpreted to mean that the discussion is not going to happen without 
the pull request. I'm sorry that I misunderstood this.

> I started this task and am now very confused. I'd like to set up a hangout or
> something to try to understand the bigger picture in this reorganization

When?

>     In tracking down missing references, I realized the problem is that there
>     are whole missing chapters; did the content get rolled in elsewhere?

Yes.

>       o Containers: Arrays, Vectors, and Matrices

Combined to "Data Types and Variable Declarations". This was the part with the 
most repetition.

>       o Multiple Indexing and Range Indexing (some [all?] of this is now in the
>         Optimizing Stan Code for Efficiency chapter, which seems like an odd
>         choice to me as the indexing isn't any more efficient than looping)

"Expressions" has the basics of the indexing.
When I read "Multiple Indexing and Range Indexing", it felt more like 
additional programming tips as it includes many examples which are more clear 
after other examples, so it didn't fit well in "Expressions" chapter. 
Furthermore "Multiple Indexing and Range Indexing" section starts:
---clip---
Stan allows multiple indexes to be provided for containers (i.e.,
arrays, vectors, and matrices) in a single position, using either an
array of integer indexes or range bounds.  This allows many models to
be vectorized.  For instance, consider the likelihood for a varying-slope,
varying-intercept hierarchical linear regression, which could be coded
as
%
\begin{stancode}
for (n in 1:N)
   y[n] ~ normal(alpha[ii[n]] + beta[ii[n]] * x[n], sigma);
\end{stancode}
%
With multiple indexing, this can be coded in one line, leading to more
efficient vectorized code.
---clip---

I thought "more efficient vectorized code" would mean it is more efficient.

>     The natural order is to have the Expressions and Data Types chapter before
>     the Statements chapter because statements depend on expressions and involve
>     typing. I'd very much like to order that back the way I have it if the
>     internal changes weren't too dramatic.

I guessed you would think that. I put the Statements first, because the most 
important part of the language how to build log density (target += and ~) are 
described there. At least I like to first read what I can do with a new 
language and only after that I'm interested in reading additional details. If 
you want to move expression to be before statements, then there is need to 
describe += and ~ in the introduction.

>     There is junk inserted at the end of chapters like
>
> |%%% Local Variables: %%% mode: latex %%% TeX-master: "stan-reference" %%% End: |
>
> Did this come from some kind of LaTeX IDE or editor mode? I'd rather not leave
> this stuff in our docs.

Emacs AUCTeX mode. I thought they would not do harm, but I can remove them.

I have additional comments about splitting and models chapter, but I continue 
that discussion in discourse,

Aki

**Comment by avehtari** [comment]
Bob> I like that it went from 585 to 506 pages

Hmm... I have 568 pages. 

I thought I had fixed all missing references. Fixed now.

Aki

**Comment by bob-carpenter** [comment]
OK, I'll take a longer read over the whole thing
as you checked it in.  I may have cut things out
in trying to break into two parts, which may also
account for why I thought things went missing.

- Bob

**Comment by bob-carpenter** [comment]
Overall, this looks great and should make it easier to split the docs apart.

I furtherd some of your changes:

* broke the Examples and Programming Techniques into two parts
* moved reproducibility and stan as software chapters into the new software part you created

And I reverted a couple things to how they were before:

* pulled the multi indexing and the matrix vs. arrays out into their own chapters (we get lots of questions on these)

* moved statement chapter back to after data types and expression chapters (this is the traditional order due to dependencies)

**Comment by bob-carpenter** [comment]
@avehtari If you could review this, I'm OK with it if you are.

**Comment by avehtari** [comment]
When I compile stan-reference.tex I don't get chapter and section numbers (the latest released manual has them). I couldn't figure out why this happens. Otherwise it seems ok.

**Comment by bob-carpenter** [comment]
Chapter and section numbers work fine for me, so I'm going to go ahead and merge and assume it's something on your side out of sync.  Do you have the Lucida fonts?  If not, then nothing's going to look right anyway (but it shouldn't cause a problem with section numbering).

**Pull request merged**
