### PR TITLE
Change PATH for TBB in Jenkinsfile

### PR DESCRIPTION
**Pull request by serban-nicusor-toptal**
This PR changes the PATH variable from unix path to windows path in Jenkinsfile avoid random pipeline failures because of TBB in PATH.

Changed from
```
./lib/stan_math/lib/tbb
```
to
```
${WORKSPACE}\\lib\\stan_math\\lib\\tbb
```

`${WORKSPACE}` will default to current working directory on the pipeline.
This change was done also in CmdStan with success.

### CODE REVIEW

**Comment by serban-nicusor-toptal** [comment]
@rok-cesnovar Any clue why this PR fails ? Don't see any TBB errors :(

**Comment by rok-cesnovar** [comment]
That is really weird. Will have a look.

**Comment by rok-cesnovar** [comment]
I merged #2879 in, lets see if that fixes it.

**Comment by rok-cesnovar** [comment]
I am going to close this one @serban-nicusor-toptal 
The windows unit tests in Stan are now working fine.

**Pull request closed without merging**
