### PR TITLE
Bugfix/issue 2174

### PR DESCRIPTION
**Pull request by bgoodri**
#### Submisison Checklist

- [X] Run unit tests: `./runTests.py src/test/unit` but does not change any C++
- [X] Run cpplint: `make cpplint` but does not change any C++
- [X] Declare copyright holder and open-source license: see below

#### Summary

Eliminates the \nobreakspace from doc/stan-functions*.txt

#### Intended Effect

Not seeing any \nobreakspace

#### How to Verify

```
make manual
grep -F "nobreakspace" doc/stan-functions*.txt
```

#### Side Effects

None

#### Documentation

None

#### Reviewer Suggestions

No one

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Trustees of Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by bob-carpenter** [comment]
Are you sure you want to replace them with zero spaces rather than a single space?  Can you replace with a single space, then collapse multiple spaces down to one?  Anyway, I don't even know what this stuff's for, so it doesn't matter to me how it looks.

**Comment by bgoodri** [comment]
It has too much space already, so it comes out looking like

real[  ,  ]

rather than

real[,]

If someone searches by output for "real[,]" they will miss "real[  ,  ]".

**Comment by bob-carpenter** [comment]
Comes out where?  What I'm missing is why you want real[,] and where someone would be searching for it.

**Comment by bgoodri** [comment]
> rstan::lookup(ReturnType = "real[,]")
    StanFunction  Arguments ReturnType Page
584  to_array_2d (matrix m)    real[,]  377

**Pull request merged**
