### PR TITLE
Use StanHeaders_2.26 branch for math submodule

### PR DESCRIPTION
**Pull request by hsbadr**
Use and update `math` submodule for `StanHeaders_2.26`.

- [X] Update the submodule when https://github.com/stan-dev/math/pull/2359 is merged.

@bgoodri

### CODE REVIEW

**Comment by SteveBronder** [comment]
I think if you merge to latest this should be good. is this just a branch for testing? Or should we put up a 2.26.1 for stanheaders?

**Comment by hsbadr** [comment]
> I think if you merge to latest this should be good. is this just a branch for testing? Or should we put up a 2.26.1 for stanheaders?

This is for backward compatibility of `StanHeaders 2.26` not to break CRAN dependencies. It's likely a temporary intermediate release until we get both `StanHeaders` and `rstan` with `Stan 2.26` on CRAN.

**Comment by hsbadr** [comment]
Or should we put up a 2.26.1 for stanheaders?

To elaborate, https://github.com/stan-dev/rstan/pull/887 works fine with the latest Stan development, but unfortunately, we should update both `rstan` and `StanHeaders` together which seems to be impossible without breaking all dependencies during CRAN submission. So, @bgoodri decided to release `StanHeaders 2.26` that works `rstan 2.21`. The `StanHeaders_2.26` branches are for this purpose.

**Comment by hsbadr** [comment]
I'll close this because the `math` submodule needs more patches. I'll reopen after fixing all dependencies.

**Comment by hsbadr** [comment]
@bgoodri This is ready to go.

**Pull request closed without merging**
