### PR TITLE
Bugfix/2748 matrix indexing

### PR DESCRIPTION
**Pull request by mitzimorris**
#### Submission Checklist

- [x] Run unit tests: `./runTests.py src/test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary
Fixed generator so that matrix indexing uses most efficient access strategy - generated code should call `stan::math::get_base1()` on matrix using 5-arg function which specifies matrix row, column.

#### Intended Effect
Speeds up matrix access by factor of 10x for models which do a lot of matrix indexing.

#### How to Verify
Need performance test benchmarks.

#### Side Effects
None

#### Documentation
N/A
#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by mitzimorris** [comment]
submitting PR now.  need to work with @seantalts to add performance tests to test suite.

**Comment by mitzimorris** [comment]
we also need tests consisting of models and data and checks that multi-dim indexing operations behave according to spec.

**Comment by seantalts** [comment]
I don't think I'm the right person to review this - does Bob or someone else familiar with the Stan 2 compiler have time?

**Comment by mitzimorris** [comment]
a) no one has time
b) it's just one file changed and I can walk you through the logic
c) we need to talk about adding a performance test, and you are the one to do this.

**Comment by seantalts** [comment]
I mean I don't know the code at all, regardless of my time commitments, so
my approval wouldn't mean much. I'm happy to work on adding the test
because I know how to test performance. Did you ask Bob and Matthijs?

**Comment by mitzimorris** [comment]
OK, you're right.
Bob says he'll do the code review.
let's talk about the testing.

**Comment by bob-carpenter** [comment]
Where was the test case?  I see `model2.stan` checked in, but nothing uses it (so it's just cause a generic parsability test).  Is there data somewhere?  I'd like to verify that the performance regression is fixed.

**Comment by seantalts** [comment]
@mitzimorris was talking about also adding unit tests, but I'm not sure how to best to that. From the performance testing perspective this will get run as part of the "Shotgun" model test suite in performance-tests-cmdstan repo. That job is running here: http://d1m1s1b1.stat.columbia.edu:8080/blue/organizations/jenkins/CmdStan%20Performance%20Tests/detail/master/591/pipeline

It should eventually run that model (it actually didn't with my first link, I had to fix something). 

As of today (https://github.com/stan-dev/cmdstan/pull/690) we will run the performance test suite on every commit to CmdStan develop (and while we're still without monorepo, a commit happens there on every merge to develop for Stan and Math as well). @serban-nicusor-toptal is working on figuring out how to get that job to email us when a regression occurs - it was supposed to be set up that way but I don't think it was working correctly. 

For the next step, @serban-nicusor-toptal will work on adding some subset of those performance tests to pull requests as well via the CmdStan "downstream_tests" job, but that will probably just be the `stat_comp_benchmarks` models, though we could reasonably also add this new performance regression test directory to that list. I just don't want to add TOO much time to a PR, and I'll be pretty happy if we get the first step above working and emailing out correctly.

**Comment by seantalts** [comment]
Seeing a large trend in the performance tests for this, so looks like we're now measuring it. Still, the email alerting and auto PR perf testing are new, so keep an eye out and please check [the Cmdstan Performance Tests master build's Performance Trend](http://d1m1s1b1.stat.columbia.edu:8080/job/CmdStan%20Performance%20Tests/job/master/performance/) some hours after merging to develop.

image

**Comment by bob-carpenter** [comment]
I don't get the throughput plot..  Looks like the 0 value at #593 is an artifact.

**Comment by seantalts** [comment]
You mean the point at 593 for response time for the matrix test? That is an artifact of that test not existing at 593.

**Comment by bob-carpenter** [comment]
> On Apr 30, 2019, at 10:56 AM, seantalts <notifications@github.com> wrote:
> 
> You mean the point at 593 for response time for the matrix test? That is an artifact of that test not existing at 593.

Yes.  [I guess if I gloat that I finally produced a one-word
answer, it's not a one-word answer anymore.]

**Comment by seantalts** [comment]
:D haha. To be clear, I added this matrix_indexing test because of the bug and PR. So I don't think we were testing this element-wise matrix indexing situation before in any of the model tests I had running nightly. My plan is to keep adding models whenever they come up to this regressions directory.

**Pull request merged**
