### PR TITLE
Feature/issue 1936 print

### LINKED ISSUE #1936: print() is broken when there is a rejection/exception in the model block
#### Summary:

see title

#### Description:

see summary;  we can't debug models with print with this broken.

#### Reproducible Steps:

```
parameters {
  real y;
}
model {
  y ~ normal(0, 1);
  if (y < 0) {
    print("foo"); 
    reject("bar");
  }
}
```

#### Current Output:

When I run in CmdStan, I get:

```
...
Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Exception thrown at line 8: bar
If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,

but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.

Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Exception thrown at line 8: bar
If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,

but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
Iteration: 2000 / 2000 [100%]  (Sampling)

Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Exception thrown at line 8: bar
If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,

but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.

 Elapsed Time: 0.095294 seconds (Warm-up)
               0.134391 seconds (Sampling)
               0.229685 seconds (Total)
```

#### Expected Output:

I expected to see "foo" being printed.  

#### Additional Information:

I believe this is a problem origininating in Stan itself as it shows up in all the interfaces.

#### Current Version:
v2.9.0

I think we need to fix this and can't wait for a refactoring to do it for us.

### PR DESCRIPTION
**Pull request by syclik**
#### Submisison Checklist

- [x] Run unit tests: `./runTests.py src/test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary
`print()` within a Stan program currently does not print if there's an exception in the model block. With this fix, Stan programs will print the message as expected.

#### Intended Effect

Fixes #1936. 

#### How to Verify

Run the new unit test in `src/test/unit/services/init/initialize_state_test.cpp`.
You can also verify using the Stan program in #1936.

#### Side Effects

None.

#### Documentation

None.

#### Reviewer Suggestions

Anyone.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Columbia University.

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by betanalpha** [comment]
Under a rejection a print statement is emitted, but I'm not sure if it's correct.  For example, consider the program

    parameters {
      real x;
    }
    
    transformed parameters {
      print("Begin... ", x);
    }
    
    model {
      x ~ normal(0, 1);
      if (x > 2) reject("");
      print("End...");
    }

Under a rejection ```x``` is not the current value but the previous value, and the second print statement is not executed.  I can see the latter behavior being okay if it is expected, but why isn't the value of ```x``` updated?

**Comment by bob-carpenter** [comment]
It only has access to the current iteration, so
you're probably seeing the print from the previous
iteration.

It'd be good to print iteration numbers
and chain IDs with the print statements.  Maybe that
wouldn't be too hard.

- Bob

**Comment by betanalpha** [comment]
I counted to make sure — but in none of the statements
was x greater than 2, despite the rejection.

**Comment by bob-carpenter** [comment]
print() only gets access to current values in the
statement.  I have no idea what's going on with the
output lag if it's one behind.

- Bob

**Comment by syclik** [comment]
I'll take a look. I don't see how that's happening, but I'll verify. 


Daniel

**Comment by syclik** [comment]
@betanalpha, thanks for keeping me honest. I didn't catch all the places where it could have printed. I'm searching for it.

**Comment by syclik** [comment]
I reimplemented the fix. This should work better.

**Comment by betanalpha** [comment]
That fixes the problem.

Final question — before there was a newline after the rejection output
(and two unnecessary newlines within the body of the rejection output
but we can address these later), if you inadvertently removed it can
you return the new line after the rejection output?  If it was a weird
side effect I’m also fine addressing it later.

**Comment by syclik** [comment]
Cool.

I can set the behavior back to what it was -- it was super-odd having the
rejection message being closer to the next iteration rather than closer to
the current iteration's output.

**Comment by betanalpha** [comment]
Two newlines after the rejection message?  I agree that having
some association with the current iteration is good, but some
white space to separate it out also helps to isolate the rejection
behavior from the usual behavior.

**Comment by syclik** [comment]
Hmm... did I accidentally remove the space after the rejection? I thought I
added more space after the rejection. I'll take a look this weekend. You'd
be ok with two newlines after rejection?

**Comment by syclik** [comment]
(I might have also not checked after implementing it differently...)

**Comment by betanalpha** [comment]
This is what I see, with annotations:

    [Last message from previous iteration] End model... 
    [First message from current iteration] Begin... 3.35729 
    [Newline followed by reject output]
    Informational Message: The current Metropolis proposal is about to be rejected because of the   following issue:
    Exception thrown at line 11: 
    If this warning occurs sporadically, such as for highly constrained variable types like covariance    matrices, then the sampler is fine,
    [Awkward newline]
    [Rest of reject output] but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
    [First message from next iteration, no newline] Begin... -1.86339

Without annotations,

    End model...
    Begin... 3.35729
    
    Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
    Exception thrown at line 11: 
    If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
    
    but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
    Begin... -1.86339

Ideally we'd get rid of that awkward newline between the two parts of the reject output, but that might not be within the scope of this PR.  But I think we really want a new line between the reject output and the next iteration.

**Comment by syclik** [comment]
I'll fix it here. That squashing of output was unintentional and I think I know where it's from. We definitely want space between iterations.

**Comment by syclik** [comment]
@betanalpha, I've changed it. Let me know if this looks ok:

```
Begin... 0.114479
End...

Begin... 2.07213

Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Exception thrown at line 12: 
If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.

Begin... 0.114479

Begin... 0.114479
End...
```

With annotation:
```
[First message from previous iteration] Begin... 0.114479
[Last message from previous iteration] End...
[Newline (only occurs when there is print output within an iteration)]
[First message from current iteration] Begin... 2.07213
[Newline followed by reject output -- awkward newline gone]
Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Exception thrown at line 12: 
If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
[Newline after rejection output]
[First message from next iteration: this is being printed through the write_array method] Begin... 0.114479
[Newline]
[First message from next iteration] Begin... 0.114479
[Last message from next iteration] End...
```

**Comment by syclik** [comment]
I just convinced myself of how to get rid of the output from `write_array`, which is going to reduce confusion. I'll update that on this branch now.

**Comment by syclik** [comment]
Now it looks like:
```
Begin... -1.46467
End...

Begin... 2.95645

Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Exception thrown at line 11: 
If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.

Begin... -1.46467
End...
```

That good enough to get in?

**Comment by betanalpha** [comment]
Ship it.

**Comment by syclik** [comment]
Didn't work the way I expected. The CmdStan tests caught an error -- now
the generated quantities don't print.

I'm going to undo my last commit and it'll have the same behavior as
before. We can think about how to fix that more generally on a different
issue.


On Wed, Jul 6, 2016 at 4:31 AM, Michael Betancourt <notifications@github.com

**Pull request merged**
