### PR TITLE
Feature/issue 1457 boost 1.58

### PR DESCRIPTION
**Pull request by bob-carpenter**
#### Summary:

Update Stan to use Boost 1.58.

#### Intended Effect:

Allow use of RStan with the latest release of R package BH (Boost headers), which is Boost 1.58.

#### How to Verify:

Run tests. 

Note the updated Wishart RNG tests that now include a seed.  They weren't passing by a small numerical margin, but look to be OK.

#### Side Effects: 

Will no longer run with Boost versions lower than 1.56

#### Documentation:

Nothing user facing. (the license doc in the language manual no longer mentions versions)

#### Reviewer Suggestions:

Anyone.

### CODE REVIEW

**Comment by bob-carpenter** [comment]
Hint:  other than Wishart tests, the changes are all in `lang/grammars/*_def.hpp` and are all the same

**Comment by bgoodri** [comment]
This is a FAIL for me too on Linux

src/test/unit/io/dump_test.cpp:73: Failure

**Comment by bob-carpenter** [comment]
I'm trying to get a patch for Boost 1.58 ASAP so that
we can upgrade RStan so that everyone's installs will start
working again.  This is my only priority at the moment and
I've spent the better part of three days on this already.

The last commit but one worked on Mac.  The most recent
commit breaks everything and needs to be backed out --- I
inadvertently brought in a C++11 dependency for expm1.  

Windows is still broken.

Linux is uncertain.

So far, I've fixed the semantic actions in the parser due
to changes in Boost's lazy evaluation, fixed the dump parser 
due to changes in Boost's underflow exception handling just on
Windows, and now need to figure out why Boost's expm1() is
failing on Windows --- I think it's boundary conditions
again on overflow/underflow, which we're carefully testing
and hence failing on when things change.

- Bob

**Comment by bgoodri** [comment]
The expm1 error is happening on Linux when C++11=false. If true, it seems
to be okay.

**Comment by syclik** [comment]
Ben, how do I turn off C++11 in clang++? I've searched for the flag for the
last hour and I can't find it.

**Comment by bgoodri** [comment]
Is C++11 the default for clang++ on a Mac these days? If so, you would
probably have to put -std=g++99 or something into make/os_mac.

**Comment by syclik** [comment]
I can't get the -std flag to prevent C++11 features. I've tried all the
standards I can find, which is really tough to do, btw:
http://stackoverflow.com/questions/21870283/how-to-get-list-of-supported-standards-in-clang

**Comment by syclik** [comment]
Do you know of any other flags that will force clang++ to fail to compile
if C++11 is used?

**Comment by betanalpha** [comment]
Which feature are you trying to remove?  Remember that there
is the standard (-std) and then the standard library (-stdlib).
Even if you force, say, -std=c++03, you might still call the
implementations in the newer standard library.

**Comment by syclik** [comment]
I'm trying to compile with strict C++98 compliance. Windows doesn't have
std::expm1, that's been introduced as of C++11. It's a lot easier testing
locally than it is getting to the Windows machine and back for compliance.

**Comment by betanalpha** [comment]
Have you tried forcing the older standard library implementation, -stdlib=libstdc++?

**Comment by syclik** [comment]
there's no -stdlib option specified in the compilation

**Comment by betanalpha** [comment]
Sure, which should then resort to the default which will be -stdlib=libc++
on new versions of clang.  Explicitly setting -stdlib=libstdc++ should force
the compiler to link to the older (pre C++11) implementation of the
standard library that doesn’t include the C++11 functions.

**Comment by syclik** [comment]
Thanks, Bob. I walked through the changes and they look good. We'll merge once it passes tests.

**Comment by syclik** [comment]
This is fine. I fixed the performance test.

**Pull request merged**
