### PR TITLE
Bugfix/2383 boost lib 1.64.0

### PR DESCRIPTION
**Pull request by mitzimorris**
#### Submission Checklist

- [x] Run unit tests: `./runTests.py src/test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary
make Stan compatible with lib/stan_math which uses Boost 1.64.0 as well as current lib/stan_math which users Boost 1.62.0.

#### Intended Effect
ran all Stan unit tests against math lib built on Boost 1.64.0 (see https://github.com/stan-dev/math/issues/599).
the unit test `src/test/unit/variational/eta_adapt_small_test.cpp` failed - it seems that under Boost 1.64.0 more iterations are required in order to achieve the desired eta.

#### How to Verify
run all unit tests against `lib/stan_math` built with Boost 1.62.0, then run all unit tests against `lib/stan_math` built with Boost 1.64.0.

#### Side Effects
none

#### Documentation
n/a

#### Reviewer Suggestions
Daniel Lee, Bob Carpenter

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):  Mitzi Morris

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by bgoodri** [comment]
I am still getting a compiler error from the parser in RStan when using `g++` (but not `clang++`):
```
In file included from /usr/local/lib/R/site-library/BH/include/boost/phoenix/function/detail/cpp03/preprocessed/function_operator.hpp:12:0,
                 from /usr/local/lib/R/site-library/BH/include/boost/phoenix/function/detail/cpp03/function_operator.hpp:6,
                 from /usr/local/lib/R/site-library/BH/include/boost/phoenix/function/function.hpp:58,
                 from /usr/local/lib/R/site-library/BH/include/boost/phoenix/function.hpp:11,
                 from /usr/local/lib/R/site-library/BH/include/boost/spirit/include/phoenix_function.hpp:11,
                 from /usr/local/lib/R/site-library/BH/include/boost/spirit/home/support/terminal.hpp:18,
                 from /usr/local/lib/R/site-library/BH/include/boost/spirit/home/support/common_terminals.hpp:15,
                 from /usr/local/lib/R/site-library/BH/include/boost/spirit/home/qi/auto/auto.hpp:13,
                 from /usr/local/lib/R/site-library/BH/include/boost/spirit/home/qi/auto.hpp:15,
                 from /usr/local/lib/R/site-library/BH/include/boost/spirit/home/qi.hpp:15,
                 from /usr/local/lib/R/site-library/BH/include/boost/spirit/include/qi.hpp:16,
                 from /usr/local/lib/R/site-library/StanHeaders/include/src/stan/lang/grammars/expression07_grammar.hpp:4,
                 from /usr/local/lib/R/site-library/StanHeaders/include/src/stan/lang/grammars/expression_grammar.hpp:5,
                 from /usr/local/lib/R/site-library/StanHeaders/include/src/stan/lang/grammars/expression_grammar_def.hpp:4,
                 from /usr/local/lib/R/site-library/StanHeaders/include/src/stan/lang/grammars/expression_grammar_inst.cpp:1,
                 from lang__grammars__expression_grammar_inst.cpp:18:
/usr/local/lib/R/site-library/BH/include/boost/phoenix/function/detail/cpp03/preprocessed/function_operator_10.hpp: In instantiation of ‘const typename boost::phoenix::detail::expression::function_eval<F, A0, A1, A2, A3, A4>::type boost::phoenix::function<F>::operator()(const A0&, const A1&, const A2&, const A3&, const A4&) const [with A0 = boost::phoenix::actor<boost::spirit::attribute<0> >; A1 = boost::phoenix::actor<boost::spirit::argument<0> >; A2 = char [3]; A3 = char [11]; A4 = boost::phoenix::actor<boost::proto::exprns_::basic_expr<boost::proto::tagns_::tag::terminal, boost::proto::argsns_::term<boost::reference_wrapper<std::__cxx11::basic_stringstream<char> > >, 0> >; F = stan::lang::binary_op_expr; typename boost::phoenix::detail::expression::function_eval<F, A0, A1, A2, A3, A4>::type = boost::phoenix::actor<boost::proto::exprns_::basic_expr<boost::phoenix::detail::tag::function_eval, boost::proto::argsns_::list6<boost::proto::exprns_::basic_expr<boost::proto::tagns_::tag::terminal, boost::proto::argsns_::term<stan::lang::binary_op_expr>, 0>, boost::phoenix::actor<boost::spirit::attribute<0> >, boost::phoenix::actor<boost::spirit::argument<0> >, boost::proto::exprns_::basic_expr<boost::proto::tagns_::tag::terminal, boost::proto::argsns_::term<char*>, 0>, boost::proto::exprns_::basic_expr<boost::proto::tagns_::tag::terminal, boost::proto::argsns_::term<char*>, 0>, boost::phoenix::actor<boost::proto::exprns_::basic_expr<boost::proto::tagns_::tag::terminal, boost::proto::argsns_::term<boost::reference_wrapper<std::__cxx11::basic_stringstream<char> > >, 0> > >, 6> >]’:
/usr/local/lib/R/site-library/StanHeaders/include/src/stan/lang/grammars/expression_grammar_def.hpp:57:27:   required from ‘stan::lang::expression_grammar<Iterator>::expression_grammar(stan::lang::variable_map&, std::stringstream&) [with Iterator = boost::spirit::line_pos_iterator<__gnu_cxx::__normal_iterator<const char*, std::__cxx11::basic_string<char> > >; std::stringstream = std::__cxx11::basic_stringstream<char>]’
/usr/local/lib/R/site-library/StanHeaders/include/src/stan/lang/grammars/expression_grammar_inst.cpp:6:21:   required from here
/usr/local/lib/R/site-library/BH/include/boost/phoenix/function/detail/cpp03/preprocessed/function_operator_10.hpp:91:86: error: invalid conversion from ‘const char*’ to ‘param_type {aka char*}’ [-fpermissive]
             return detail::expression::function_eval<F, A0 , A1 , A2 , A3 , A4>::make(f, a0 , a1 , a2 , a3 , a4);
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by bgoodri** [comment]
I fixed it in RStan by adding `-DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION` in Makevars. Probably have to do that in all interfaces.

**Comment by mitzimorris** [comment]
@bgoodri  - is there anything needed to do in the Stan makefiles?

**Comment by bgoodri** [comment]
No, but it would be good if there could be something done in Stan to define
that globally.

**Comment by bgoodri** [comment]
@bob-carpenter would know better than I would but probably expression_grammar.hpp or expression_grammar_def.hpp or expression_grammar_inst.hpp or parser.hpp.

**Comment by mitzimorris** [comment]
the Stan grammar files which include file `boost/phoenix/phoenix.hpp` are:

- `src/stan/lang/grammars/statement_grammar_def.hpp`
-  `src/stan/lang/grammars/var_decls_grammar_def.hpp`

added explicit includes into `statement_grammar_def.hpp`.


added explicit includes to the above 2 files to

**Comment by mitzimorris** [comment]
@bgoodri would you like to try again to build rstan using this branch?

**Comment by bgoodri** [comment]
Same error

**Comment by bgoodri** [comment]
Here are the files where that define (that fixes it) kicks in
```
goodrich@T540p:/opt/rstan/StanHeaders/inst/include/mathlib/lib/boost_1.64.0$ git grep -F -n "BOOST_PHOENIX_NO_VARIADIC_EXPRESSION" | cat
boost/phoenix/core/detail/expression.hpp:218:#ifndef BOOST_PHOENIX_NO_VARIADIC_EXPRESSION
boost/phoenix/core/detail/expression.hpp:230:#else // BOOST_PHOENIX_NO_VARIADIC_EXPRESSION
boost/phoenix/core/detail/expression.hpp:278:#endif // BOOST_PHOENIX_NO_VARIADIC_EXPRESSION
boost/phoenix/core/detail/expression.hpp:301:#ifndef BOOST_PHOENIX_NO_VARIADIC_EXPRESSION
boost/phoenix/core/detail/expression.hpp:314:#else // BOOST_PHOENIX_NO_VARIADIC_EXPRESSION
boost/phoenix/core/detail/expression.hpp:340:#endif // BOOST_PHOENIX_NO_VARIADIC_EXPRESSION
boost/phoenix/core/detail/expression.hpp:342:#ifndef BOOST_PHOENIX_NO_VARIADIC_EXPRESSION
boost/phoenix/core/detail/expression.hpp:357:#else // BOOST_PHOENIX_NO_VARIADIC_EXPRESSION
boost/phoenix/core/detail/expression.hpp:380:#endif // BOOST_PHOENIX_NO_VARIADIC_EXPRESSION
boost/phoenix/core/detail/function_eval.hpp:25:#ifdef BOOST_PHOENIX_NO_VARIADIC_EXPRESSION
boost/phoenix/core/expression.hpp:24:#ifdef BOOST_PHOENIX_NO_VARIADIC_EXPRESSION
boost/phoenix/core/limits.hpp:44:# define BOOST_PHOENIX_NO_VARIADIC_EXPRESSION
boost/phoenix/core/limits.hpp:64:# define BOOST_PHOENIX_NO_VARIADIC_EXPRESSION
boost/phoenix/object/construct.hpp:19:#ifdef BOOST_PHOENIX_NO_VARIADIC_EXPRESSION
boost/phoenix/object/new.hpp:19:#ifdef BOOST_PHOENIX_NO_VARIADIC_EXPRESSION
boost/phoenix/operator/member.hpp:24:#ifdef BOOST_PHOENIX_NO_VARIADIC_EXPRESSION
```

**Comment by mitzimorris** [comment]
found the right file to include the right way.  this time for sure?

**Comment by bgoodri** [comment]
Same error

**Comment by bgoodri** [comment]
We may have to wrap the offending chars in phoenix::val() as in

https://github.com/emweb/wt/pull/102/commits/b944cdc0961f683cd12fc6e60db3d0b328cd46dd

**Comment by mitzimorris** [comment]
just tried adding the boost/phoenix header to all grammar def files.
checking out  @bgoodri latest suggestion....

**Comment by mitzimorris** [comment]
@syclik - fix to logistic test for math lib now breaking core stan tests?

@bgoodri - still same error?

**Comment by bgoodri** [comment]
Yes

**Comment by syclik** [comment]
@mitzimorris, yes. These tests won't pass until the math library branch is merged.

**Comment by seantalts** [comment]
@bob-carpenter or @bgoodri do you guys know if we use variadic expressions in our parser code? i.e. can we just turn them off with the `-DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION` flag in all makefiles / for all stan code?

**Comment by syclik** [comment]
I just compared the quantiles of the old boost rng and the new one and it looks ok. With 100 million draws, quantiles are no different than ~1e-5 for the 3--97% range.

**Comment by bob-carpenter** [comment]
Not as far as I know.  I also thought @bgoodri had already turned them off with no ill effects.  There are extensive unit tests that will catch if the parser's broken.

**Comment by seantalts** [comment]
So this same error under g++ is a warning with clang, at least here: http://d1m1s1b1.stat.columbia.edu:8080/job/Stan%20-%20Tests%20-%20Unit/506/warnings10Result/new/

I think it might be best to go ahead and add `-DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION` to the default compiler options in the math repo (which will trickle up). Anyone opposed? I'll submit a PR.

**Pull request merged**
