### PR TITLE
Revert "Revert "Opencl indexing""

### PR DESCRIPTION
**Pull request by SteveBronder**
Revert revert of #3048

### CODE REVIEW

**Comment by SteveBronder** [comment]
Now that's odd, the same tests pass here but failed on develop

PR passing test
https://jenkins.mc-stan.org/blue/organizations/jenkins/Stan/detail/PR-3053/1/pipeline/112#step-161-log-2747

develop failing:
https://jenkins.mc-stan.org/blue/organizations/jenkins/Stan/detail/develop/917/pipeline#step-169-log-2814

@t4c1 was there some change in the underlying Stan impl that would do this?

**Comment by t4c1** [comment]
I don't think so. Odd indeed.

**Comment by hsbadr** [comment]
> Now that's odd, the same tests pass here but failed on develop

Could you check the order and included headers in `src/stan/model/indexing.hpp`?
```diff
- #include <stan/model/indexing/access_helpers.hpp>
```

**Comment by rok-cesnovar** [comment]
This one has conflicts that need resolving, then lets see if the tests pass.

**Review by rok-cesnovar — APPROVED** [review]

**Comment by rok-cesnovar** [comment]
Thanks @SteveBronder !

**Comment by SteveBronder** [comment]
Np! But if you wouldn't mind waiting on this I am working on another PR to fix #3076 that I'd like to merge before this one so I don't have to do a big remerge and have a bunch of merge conflicts

**Comment by SteveBronder** [comment]
@serban-nicusor-toptal could you checkout the Jenkins file in this PR and check that the GPU setup is correct?

**Comment by serban-nicusor-toptal** [comment]
Hey @SteveBronder I've checked it out and it looks good! ( I've cross-checked with [math ](https://github.com/stan-dev/math/blob/develop/Jenkinsfile) to be sure )
Just one small note: 
Recently we've pushed a new image for math with cpp17 `stanorg/ci:gpu-cpp17` just in case you might need a newer version.

**Pull request merged**
