### PR TITLE
missing semicolon in manual

### PR DESCRIPTION
**Pull request by tjmahr**
#### Submisison Checklist

- [ ] Run unit tests: `./runTests.py src/test/unit`
- [ ] Run cpplint: `make cpplint`

Not needed because this is just a doc change?

- [x] Declare copyright holder and open-source license: see below

#### Summary

Typo fix.

#### Intended Effect

Make example code from manual compile.

#### How to Verify

I was trying the example from the manual and editing the Stan file in RStudio which checks the syntax whenever I save. Here's before the edit.

```r
rstan:::rstudio_stanc("center-param.stan")
#> SYNTAX ERROR, MESSAGE(S) FROM PARSER:
#>   
#>   
#>   ERROR at line 33
#> 
#> 31:        for (n in 1:N)
#>   32:          x_beta_jj[n] = x[n] * beta[jj[n]]
#> 33:        y ~ normal(x_beta_jj, sigma);
#> ^
#>   34:      }
#> 
#> PARSER EXPECTED: ";"
#> Error in stanc(model_code = paste(program, collapse = "\n"), model_name = model_cppname,  : 
#>   failed to parse Stan model 'center-param' due to the above error.
```

Here's after.

```r
rstan:::rstudio_stanc("center-param.stan")
#> center-param.stan is syntactically correct.
```

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Tristan Mahr

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by bob-carpenter** [comment]
@tjmahr  Thanks for the pull request.  It may be easier in the future to just report the typos to us in the issue open for typos on the manual.  I make a pass before each release and fix all the reported errors.  The problem with all these little pull requests is that we now have a heavy review and integration testing process in place.  The current "next manual" issue is https://github.com/stan-dev/stan/issues/2265

@seantalts  What do we want to do with these one-character pull requests?  Is there some way not to do a compute day's worth of integration testing for manual-only changes?

@seantalts  Although this is off issue, should we think about moving the manual to a new repo to solve this ongoing problem?  I hate to discourage pull requests, but then I also hate the idea that this kicks off a compute day's worth of integration testing and ties up our servers and those we get from Travis.

**Comment by tjmahr** [comment]
Oops, I didn't know about the updates-to-manual issue :sweat_smile:

**Comment by seantalts** [comment]
@tjmahr Don't worry! We appreciate it a lot and we'll figure something out.

@bob-carpenter Do you have an existing manual-edits branch somewhere? If so, I would just pull @tjmahr's commits from his branch into that one:
```
git checkout manual-edits-2.16.0
git pull git@github.com:tjmahr/stan.git patch-1
# optional: see what commits are now in your branch that aren't in origin/develop.
git log origin/develop..manual-edits-2.16.0 #just commit messages, or
git log --stat origin/develop..manual-edits-2.16.0 #with files changed, or
git log -p origin/develop..manual-edits-2.16.0 # with actual code diffs as well
```

I like pulling his commit because it keeps his commit message and author tag, vs us just applying the diff manually.

Let me know if you get stuck or I can help you through it; feel free to call my cell.

RE: Should we move the manual to a new repo? - I typically like fewer repos in general, but here I'm a bit ambivalent since it isn't really code. I'd say for now we do the above and I can look around and see if there's a way to only test when certain directories change.

**Comment by bob-carpenter** [comment]
Now there's a solution---I usually just do it all at once, but no
reason I can't create the matching branch at the same time.

The branch on `stan-dev/stan` is `feature/2265-manual-2.16`:

* https://github.com/stan-dev/stan/issues/2265

I tried typing what you sent as a command, but it didn't work.

```
~/cmdstan/stan(feature/2265-manual-2.16)$ git pull git@github.com:tjmahr/stan.git patch-1
The authenticity of host 'github.com (192.30.253.113)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? y
Please type 'yes' or 'no': yes
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by seantalts** [comment]
Woops, missed this notification, sorry. It seems like you haven't set up SSH keys with github? If you want to do that, you can see how here: https://help.github.com/articles/connecting-to-github-with-ssh/

But if you want to keep using https you can change all of those `git@github.com urls to `https://github.com/` like so:
```
git pull https://github.com/tjmahr/stan.git patch-1
```

**Pull request merged**
