### PR TITLE
Bugfix/issue 1731 argument configuration advi

### PR DESCRIPTION
**Pull request by akucukelbir**
#### Summary:

This gives reasonable values for variational input arguments. 

#### Intended Effect:

It should make sure that the arguments tests don't fail.

#### How to Verify:

Run tests.

#### Documentation:

None.

#### Reviewer Suggestions: 

@syclik

### CODE REVIEW

**Comment by syclik** [comment]
it's not quite right... I think you touched the submodule in some weird way. Mind backing out the change to the math submodule?

**Comment by akucukelbir** [comment]
@syclik i did as you said, but i'm not sure it helped :(

**Comment by bob-carpenter** [comment]
Currently this pull request has merge conflicts, so you're going to need to resolve those before anything's going to pass.

**Comment by akucukelbir** [comment]
that's odd. it was fine when i submitted it last week?

daniel said that this was blocking you guys. this pull request is all
standard stan/argument stuff; nothing specific to ADVI. so feel free to
hack at it, if you prefer.

**Comment by syclik** [comment]
Unfortunately, it was never fine. It might have merged in the past, but it
definitely doesn't now. It never passed tests. (you can see the red x's for
when it was run and failed)

This is blocking Stan. Tests like should never fail and I've already seen
it fail a handful of times.

If you look back at the merge problem, I think it's due to the stan_math
submodule being in a conflicting state. Can you merge develop into the
branch locally and fix the conflict?

**Comment by akucukelbir** [comment]
@syclik looking okay now, i hope?

**Pull request merged**
