### PR TITLE
Feature/issue 1795 semantic action header

### PR DESCRIPTION
**Pull request by bob-carpenter**
#### Submisison Checklist

- [x] Run unit tests: `./runTests.py src/test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary

Moves semantic actions for grammars to their own header and definition file.  Remove unused includes and using statements.

#### Intended Effect

Remove the clutter from the grammar files and allow sharing of semantic actions across grammars.

#### How to Verify

Unit tests still pass.

#### Side Effects

Builds an extra .o file.

#### Documentation

Not user facing.

#### Reviewer Suggestions

Anyone.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):  

Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by bob-carpenter** [comment]
I'll need help to figure out why this failed on Windows --- I can't see what caused the build to fail from the console output.

**Comment by syclik** [comment]
I'll have to log in and see what's going on. I'll take a look Monday.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
@bob-carpenter, the error was due to RTools 33 being installed. It doesn't seem to work at all.

@bgoodri, I moved the old RTools up in the system path. Perhaps change your personal user's path if you want to do testing with new RTools 33?

**Comment by syclik** [comment]
Looks good to me.

@maverickg or @bgoodri, this introduces one more file to compile for stanc. It has the same convention as the other files. Do you list the files by hand or use some sort of wildcard search?

**Comment by bgoodri** [comment]
By hand. Wildcards are specific to GNU make.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
@bgoodri, thanks for the info.

**Pull request merged**
