### PR TITLE
Bugfix/issue 1506 intel 14 parser

### PR DESCRIPTION
**Pull request by bob-carpenter**
#### Summary:

* Remove all uses of lazy evaluation of assignment (operator=) from semantic actions in the grammar

* ifdef out the offending bit of code in the Boost lib for the Intel compiler (yes, this involved changing Boost);  see  https://software.intel.com/en-us/articles/boost-compiler-error-class-has-no-member-type

* remove all the remaining lint from the grammars

#### Intended Effect:

Allow Stan to be compiled with Intel 14 compiler.

#### How to Verify:

Verifying the intended effect requires an Intel compiler, but it should be enough to verify that it passes unit tests.  No behavior should have changed --- this is purely refactoring.

#### Side Effects:

That definition of `operator=` is now invisible for clients using our copy of Boost.  This is very unlikely to be a problem.

#### Documentation:

Nothing user facing.

#### Reviewer Suggestions:

Anyone.

### CODE REVIEW

**Comment by bob-carpenter** [comment]
That failure looks unrelated --- it looks more like an issue about output streams in CmdStan.

**Comment by syclik** [comment]
yeah -- sorry, I was trying to fix it, but haven't had time. I'll get it
working again.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
@bob-carpenter, everything looks good, but the change made to the boost library won't help Intel compile users with RStan, right? That will still rely on the BH package, which hasn't been patched.

**Comment by bob-carpenter** [comment]
Correct.  

Ben's going to patch RStan so that it uses the same Boost
header.  As long as we make sure to search ours first, the header
guard will silence the one from Boost.  At least I think that's
Ben's plan.

- Bob

**Comment by bgoodri** [comment]
I now have an icpc version 15. I am getting a test failure on this branch at
```
[ RUN      ] io_dump.reader_big_doubles
unknown file: Failure
C++ exception with description "data b value 2.22507e-308 beyond numeric range" thrown in the test body.
```
The rstan package installs but when you try to run a model, you get
```
/usr/local/lib/R/site-library/rstan/include/rstan/stan_fit.hpp(947): error: no default constructor exists for class "stan::mcmc::fixed_param_sampler"
          stan::mcmc::fixed_param_sampler sampler;
```
followed by an error novel. This is without doing the fixed_param algorithm, which is weird.

**Comment by bgoodri** [comment]
Never mind. After another git pull and a reinstall of rstan, it works with icpc. But the bignumbers unit test failure is still there.

**Comment by bob-carpenter** [comment]
You mean the failure above of `reader_big_doubles`?   With the most recent Intel compiler?

If that's not working, it looks like the Intel compiler messed up either its `std::numeric_limits` or its I/O.  

I wonder if it's an issue with normalization?  It looks like `min()` is normalized but not `max()`:

http://www.cplusplus.com/reference/limits/numeric_limits/

**Comment by bgoodri** [comment]
Yes, changing dmin to lowest() passes in C++11 mode, as does changing dmin
to -dmax without C++11.

**Comment by bob-carpenter** [comment]
I'm confused --- where did you get dmin and dmax?

- Bob

**Comment by bob-carpenter** [comment]
Ben --- can you go ahead and make those fixes so we test the normalized min and max?  Or give us a hint as to where to find dmin and dmax so we can do it?

**Comment by bgoodri** [comment]
Right now, it is
```
  double dmax = std::numeric_limits<double>::max();
  double dmin = std::numeric_limits<double>::min();
```
which fails, but changing dmin to either
```
  double dmin = std::numeric_limits<double>::lower();
```
or
```
  double dmin = -dmax;
```
passes. So, I think it does have something to do with the normalization.

**Comment by bgoodri** [comment]
OK. This passes:
```
double dmin = 2.225075e-308;
```
whereas
```
double dmin = std::numeric_limits<double>::min(); // about 2.22507_4_e-308
```
fails. So, it looks as if icpc can't handle that edge case.

**Comment by bob-carpenter** [comment]
Thanks for tracking this down.  

I think it's my fault for not understanding the tests 
I put in there to begin with.  I just have a habit of trying
to test boundary conditions.

- Bob

**Pull request merged**
