### PR TITLE
Move src/stan/interface to src/stan/interface_callbacks

### PR DESCRIPTION
**Pull request by syclik**
#### Summary:

Move folder and namespaces. Renamed a few of the classes. This is part of @betanalpha's writer refactor branch.

#### Intended Effect:

Breaking apart the writer refactor branch into smaller chunks that are easier to review.

#### How to Verify:

Look at the changed files. All tests still pass.

#### Side Effects:

I (@syclik) will create pull requests on CmdStan, RStan, and PyStan which will be compatible with these changes to Stan. 

#### Documentation:

None.

#### Reviewer Suggestions: 

@betanalpha: this was just a refactor. No behavior changes. I didn't move all of `src/stan/interface_callbacks/writer/*` to their final class names.

### CODE REVIEW

**Comment by syclik** [comment]
btw, I think github's diff mechanism is broken: it isn't tracking moved files. Most of these files have moved. A couple of them have been renamed. The namespaces have changed.

**Comment by syclik** [comment]
The key is, there are no code behavior changes with this pull request.

**Comment by syclik** [comment]
@betanalpha, any problems with this pull request getting into develop? If so, better to know now before I branch from here and start making the other fixes you have on the writer refactor branch.

**Comment by betanalpha** [comment]
It’s just awkward renames and incorporates none of the
actual implementation changes.  No obvious problems,
but no guarantees given that the implementations aren’t
touched.

**Comment by syclik** [comment]
Yup. So I can merge?

**Comment by betanalpha** [comment]
I’d rather all this going into Stan3 so that the interfaces
can do one big update, but it’s fine.

**Comment by syclik** [comment]
I take the other stance. I don't want one big update. I want lots of small updates. If we fail, we'll fail early and we'll know whether something works or doesn't. And it's easier to track through the changes.

**Comment by betanalpha** [comment]
That’s fine — I don’t want the interfaces to have to make
lots of small, unnecessary changes.  Hence the Stan3 branch.

**Pull request merged**
