### PR TITLE
Feature/2634 convert functions ref

### PR DESCRIPTION
**Pull request by mitzimorris**
#### Submission Checklist

- [ ] Run unit tests: `./runTests.py src/test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary
Converts Stan Functions Reference from latex to R markdown with build script to generate both HTML and pdf versions.

#### Intended Effect
Provide an HTML version of the Stan Functions Reference which is can be searched (when properly hosted), both directly and indirectly via search engines.

#### How to Verify
Run build script

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):  Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by mitzimorris** [comment]
@bob-carpenter this is ready for review.

**Comment by mitzimorris** [comment]
@bgoodri :  the .Rmd files contain html comments that have the function signatures,

e.g., https://github.com/stan-dev/stan/blob/6eb0348bda4b3c9e11a5a2a9cb1705b515ebb156/src/docs/functions/binary_distributions.Rmd#L53

the sed script in the `make/manual` is gone, but it could be replaced by something that scrapes the html comments out of the Rmd files.  please advise as to what you need here.

**Comment by mitzimorris** [comment]
@seantalts @bgoodri :  here are all the function signatures with templated type T as html comments in the Rmd code:

```
<!-- T[]; rep_array; (T x, int n); -->
<!-- T[,]; rep_array; (T x, int m, int n); -->
<!-- T[,,]; rep_array; (T x, int k, int m, int n); -->
<!-- T; append_array; (T x, T y); -->
<!-- T[]; head; (T[] sv, int n); -->
<!-- T[]; tail; (T[] sv, int n); -->
<!-- T[]; segment; (T[] sv, int i, int n); -->
```

**Comment by bgoodri** [comment]
I think @seantalts had a C++ function that would parse
function_signatures.h or something, but it would be better if it had an
option to use T and R and stuff instead of outputting many signatures for
every function that can be called with multiple types on input containers.

**Comment by mitzimorris** [comment]
> Is there a bookdown option to make a monolithic HTML version of the functions reference

yes.  in the "_output.yml" file `bookdown::gitbook`, option `split_by: "none"`

> that appends #foo onto the end of the URL in order to jump to the foo section

by default, all Rmd section headers (#, ##, ###, etc) are translated to div ids that do this.
e.g.  
```
## Negative Binomial Distribution (alternative parameterization) {#nbalt}
```
in generated HTML will be:
```
<div id="nbalt" class="section level2">
```
and URL + "#nbalt" will do what you want.

so yes, you can index into the sections.  indexing into subsections also possible.

**Pull request merged**
