### PR TITLE
Feature/issue 942 reorg common

### PR DESCRIPTION
**Pull request by betanalpha**
#### Summary:

Reorganized code currently in src/stan/common into src/stan/services (common code of which the interfaces can take advantage) and src/stan/interface (abstract virtual classes that the interfaces need to implement in order for those services to work).  Resolves Issue #942.

#### Intended Effect:

One set closer to no code duplication in the interfaces.

#### How to Verify:

No user-facing effects.

#### Side Effects:

The interfaces will have to be updated as they all use some code that was in src/stan/common.

#### Documentation:

Not user-facing.

#### Reviewer Suggestions:

Anyone.

### CODE REVIEW

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
Michael, there's a test in src/test/performance that you'll need to fix.

**Comment by syclik** [comment]
This failure is ok. We need to merge CmdStan for it to work. I'll review
later today.

**Comment by betanalpha** [comment]
Yup, see https://github.com/stan-dev/cmdstan/pull/58, which should be up-to-date with this branch.

**Comment by syclik** [comment]
A couple minor things: use angle brackets for includes just to be consistent. What's diagnose.hpp for?

**Pull request merged**
