### PR TITLE
Issue #2698 ADVI Add convergence diagnostic metrics to the diagnostic writer

### PR DESCRIPTION
**Pull request by lseffer**
#### Submission Checklist

- [x] Run unit tests: `./runTests.py src/test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary
Description in issue #2698 . 
#### Intended Effect
Add the convergence metrics `delta_ELBO_mean` and `delta_ELBO_med` to the diagnostics writer which will then end up in the csv diagnostics file, alongside existing `"iter,time_in_seconds,ELBO"` , produced by pystan model `vb()` call
#### How to Verify
Run the unit tests from `src/test/unit/variational` and `src/test/unit/callbacks`
#### Side Effects
None
#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by bob-carpenter** [comment]
@betanalpha should be the one to decide this as well as the issues that @avehtari and @yao-yl are also wanting to add.

**Comment by avehtari** [comment]
Oops, I had missed this even Bob had tagged me. More diagnostics is better and I'm interested in helping. I think we need @betanalpha's approval for changing the diagnostics writer.

> Add the convergence metrics `delta_ELBO_mean` and `delta_ELBO_med` to the diagnostics writer which will then end up in the csv diagnostics file, alongside existing `"iter,time_in_seconds,ELBO"` , produced by pystan model `vb()` call

This pull request is in stan repo, but @lseffer you mention here only pystan.  Can you clarify what is the effect of this pull request for CmdStan and RStan?

**Comment by lseffer** [comment]
Hey! Unfortunately I haven't tested what happens in RStan or CmdStan. Is there an easy way to run tests for all interfaces against a common stan?

**Comment by avehtari** [comment]
> Is there an easy way to run tests for all interfaces against a common stan?

Unfortunately currently no. I think it's easier to test with CmdStan than RStan, so I would start with CmdStan. Do you need help with that?

**Comment by lseffer** [comment]
I'll gladly take any help I can get :), I tested my PR originally with a Docker container but I was a bit unsure how to make PyStan use my specific stan branch. So that part in particular is what I'm unsure about how to automate or manage properly. 

I'm however quite busy this week so if you @avehtari or anyone else wants to run the tests feel free to do so :).

**Comment by betanalpha** [comment]
Let me know when there’s a working PR to evaluate —
in general adding new diagnostics within the scope of
a specific algorithm is fine.  The basic output, and the
interface readers, was meant to be flexible enough to 
accommodate algorithms having whatever diagnostic 
info they need.  Just make sure to use the __ annotation
as done in the HMC diagnostics.

**Comment by rok-cesnovar** [comment]
Closing stale stan-dev/stan pull requests. This one  has been stale for 2+ years and has some unresolved conflicts/comments. Feel free to reopen if you wish to continue on this.

**Pull request closed without merging**
