### PR TITLE
Var initial time and time vector for ODE solver

### PR DESCRIPTION
**Pull request by charlesm93**
Allow ts and t0 to be parameters, complete ode_test, and extend the integrate_ode_* stan models. See issue #2757 .

#### Submission Checklist

- [x] Run unit tests: `./runTests.py src/test/unit/lang/parser/ode_test.cpp`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary
Change parser to allow initial time and time vector to be passed as var (i.e. not restricted to real). This has applications, for example in pharmacology, when we deal with lag times. Also expand the unit tests: check every solver and make sure all solvers are being tested under every configuration.

#### How to Verify
Unit tests.

#### Side Effects
I didn't delete the bad models that are supposed to break when initial time or time is passed as a var. I simply don't call them in the tests. Could remove these tests.

#### Documentation
PR coming up.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Charles Margossian, Columbia University and Aalto University.

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by charlesm93** [comment]
For reviews tagging @yizhang-yiz and @wds15

**Comment by charlesm93** [comment]
The docs PR can be found here: https://github.com/stan-dev/docs/pull/68

**Comment by wds15** [comment]
@charlesm93 Thanks  for making this PR, will look into it tomorrow.

@serban-nicusor-toptal The windows machine seems to have issues - Jenkins complains about not finding `make`, which should be installed.

**Comment by serban-nicusor-toptal** [comment]
Tuned them off so the build can succeed.
Will look into it later today

**Comment by charlesm93** [comment]
Ok, dead code is removed.

**Pull request merged**
