### PR TITLE
[CI] Ensure mac unit and mac interface are running correctly on m1 instance

### PR DESCRIPTION
**Pull request by serban-nicusor-toptal**
…comment out part of Jenkinsfile for faster debug

#### Submission Checklist

- [ ] Run unit tests: `./runTests.py src/test/unit`
- [ ] Run cpplint: `make cpplint`
- [ ] Declare copyright holder and open-source license: see below

#### Summary

WRT https://github.com/stan-dev/ci-scripts/issues/24 we've got a new M1 instance that we need to test our CI on to ensure everything is working fine.

#### How to Verify
Results should be consistent with the older Mac Instance.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Toptal

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by WardBrian** [comment]
I think it is probably a newer version of clang which is emitting deprecation warnings. 

The right thing to do is probably have the quality gate ignore anything which is under `lib/` (meaning all of math, and math's dependencies)

**Comment by WardBrian** [comment]
Huh, it seems like the formatting of the output values is different (the numbers themselves look correct)

**Comment by serban-nicusor-toptal** [comment]
I think the cleanest solution would be to ignore the [category ](https://jenkins.flatironinstitute.org/job/Stan/job/Stan/job/PR-3166/2/pipeline_gcc4/category.-1656024045/),[excludeCategory](https://www.jenkins.io/doc/pipeline/steps/warnings-ng/).
Seems to be working fine.

**Comment by WardBrian** [comment]
I think we _would_ still this to fail if we are using deprecated functions in code we control, though. So using `excludeFile` (which claims it accepts a pattern, so maybe `./lib/**/*` will work?) or something else seems better

**Comment by serban-nicusor-toptal** [comment]
I don't know why I thought a pattern won't work in excludeFile -.- seems to work fine, thanks!
I'll uncomment to make this ready.

**Comment by WardBrian** [comment]
Is there any reason not to have the label request just be `osx` after this? In theory it would be fine for either the newer or older machine, no?

**Review by WardBrian — APPROVED** [review]
Thanks Nic!

**Pull request merged**
