### PR TITLE
Fix advi typo in manual

### PR DESCRIPTION
**Pull request by akucukelbir**
#### Summary:
This fixes a typo in the variational inference section of the manual. (Thanks to Bruno Jacobs for catching this one!)

#### Side Effects:
None

#### Documentation:
This only affects the documentation.

#### Reviewer Suggestions:
Anyone.

### CODE REVIEW

**Comment by syclik** [comment]
@akucukelbir, please undo the change to `lib/stan_math`. You're pointed at a commit that doesn't exist.

**Comment by akucukelbir** [comment]
how do i do that? (i don't understand submodules [yet?])

**Comment by syclik** [comment]
I think the easiest thing is for me to undo it... it's just harder to
explain than to do it.

For future reference, git tracks submodules as its commit hash. If you
change the stan math library, you'll see it in your git status as
lib/stan_math having changes. Don't git add unless you want to intend to
change the math library.

**Comment by akucukelbir** [comment]
roger that. thanks!

**Comment by bob-carpenter** [comment]
Thanks for fixing these things --- the details are important.

Whenever someone suggests a fix we implement, please thank
them in the acknowledgements chapter of the manual.  There's
a list for code and a list for doc.

- Bob

**Comment by bob-carpenter** [comment]
Also, you may find it easier to just comment on the ongoing
issue or open a branch matching whatever the next manual issue
currently is and fix it there.  Here's the current one for 2.8.0++
(they are always named with "next manual <current-release>++"):

  https://github.com/stan-dev/stan/issues/1617

I added an issue to thank Bruno Jacobs in the acknowledgements.

- Bob

**Comment by akucukelbir** [comment]
thanks bob!

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
@bob-carpenter, if you think this is ok, can you merge? I don't know if you migrated this to the manual issue.

**Comment by bob-carpenter** [comment]
Two issues with that, so I don't think it should go in as is:

* [ ] it uses \mathcal{N} for normals rather than \distro{Normal} we use elsewhere;  we should be consistent

* [ ] Andrew insists on no semicolons in conditional distriutions

If I fix the whole thing, will it conflict with other requests?

**Comment by akucukelbir** [comment]
fine on my end!

**Comment by syclik** [comment]
Bob, I don't understand your question. You can fix it here and it shouldn't
conflict. If it does, we'll figure it out.

**Comment by bob-carpenter** [comment]
Even easier --- I'll just update notation when I deal with the manual.

**Pull request merged**
