### PR TITLE
Bugfix/issue 2380 algebra solver references

### PR DESCRIPTION
**Pull request by charlesm93**
#### Submission Checklist

- [ ] Run unit tests: `./runTests.py src/test/unit` (NA)
- [x] Run cpplint: `make cpplint` (ran it, but I think it is NA)
- [x] Declare copyright holder and open-source license: see below

#### Summary
Add references regarding the implementation of the algebraic solver. Fix some errors in the doc.

#### Intended Effect
Help users use the solver and more advanced users investigate the algorithmic details of the solver.

#### How to Verify
Proofread the Stan reference manual.

#### Documentation
Stan manual

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Charles Margossian

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by charlesm93** [comment]
I edited all.bib using bibdesk, but this may have not been the right approach, seeing all the differences this seems to have created between the original and the new file. What method do you use to edit all.bib?

**Comment by bob-carpenter** [comment]
@charlesm93  GitHub.  Yes, please don't just change all the bib around because bibdesk has a different notion of formatting.  It'd probably be OK, but in general it's not good policy on a shared repo because of the potential for merge conflicts.

**Comment by betanalpha** [comment]
Bibdesk automatically adds a _ton_ of metadata to the .bib, hence
all the conflicts.  It helps if you export as “Minimal BibTex” but even
then the auto formatting will cause conflicts.  

What you want to do is edit the new references in Bibdesk, export
as “Minimal BibTex” and then cut and paste the exported text to
all.bib.

**Comment by charlesm93** [comment]
ok, the all.bib file should be fine now.

**Pull request merged**
