### PR TITLE
added tests for is_vector_like

### PR DESCRIPTION
**Pull request by syclik**
#### Summary:

Add tests for `is_vector_like`.

#### Intended Effect:

Verify `is_vector_like` behaves properly.

#### How to Verify:

See the additional test code.

#### Side Effects:

None. No code has changed.

#### Documentation:

None. Documentation should already be in place.

#### Reviewer Suggestions: 

Bob?

### CODE REVIEW

**Comment by bob-carpenter** [comment]
Shouldn't there be tests for VectorXd and RowVectorXd that succeed?  I saw there was one for MatrixXd that fails.

**Comment by syclik** [comment]
Yes. I'll add those. I started working in that too late local time.

**Comment by syclik** [comment]
Just added those tests. Looks like the template metaprograms work fine.

**Comment by syclik** [comment]
Bob, this good enough?

**Comment by bob-carpenter** [comment]
Good enough for me.

**Pull request merged**
