### PR TITLE
Cleanup grad_hess_log_prob so weird indexing is more obvious

### PR DESCRIPTION
**Pull request by SteveBronder**
#### Submission Checklist

- [x] Run unit tests: `./runTests.py src/test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary

1. There was some very weird indexing happening in model/grad_hess_log_prob.hpp where we would grab a reference to a 'row' in the vector representing the hessian. That was weird so I ripped it out and just did normal indexing. This also showed me that we have a very weird memory access pattern when we fill in that vector representing the hessian. I couldn't figure out a nicer access pattern but also don't know how much we use that particular function so I let it go. Also the diagonal is being incremented twice, idk if that's intended or not.

2. `half_epsilon * coefficients[i]` used in the 3rd for loop are both known at the beginning of the function so we move them up

#### Intended Effect

Just a little code cleanup, maybe the next person can figure out a better memory access pattern

#### How to Verify

Tests should run as normal

#### Side Effects

Hopefully none!

#### Documentation

Function was already doc'd

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Steve Bronder

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by SteveBronder** [comment]
@syclik would you mind if I tagged you on this? Looking at the git blame I think it's just you and I that have touched this file (me with the clang tidy stuff). Idk how much we use this things so if the answer is not much we can also just close this

**Comment by bob-carpenter** [comment]
Rather than accessing by row, you can access by column then transpose at the end.

**Comment by syclik** [comment]
Weird... I got an email notification with a comment from @bob-carpenter, but I don't see it here:
> Rather than accessing by row, you can access by column then transpose at the end.

**Comment by SteveBronder** [comment]
> Rather than accessing by row, you can access by column then transpose at the end

What was that in reference to? Would be nice to have better mem access here

**Comment by bob-carpenter** [comment]
> > Rather than accessing by row, you can access by column then transpose at the end

> What was that in reference to? Would be nice to have better mem access here

I think it might be more efficient in some cases of large `M` and `N` to fill in memory local order (by column)

Suppose we need to fill a large matrix elementwise

```
matrix b(M, N);
```

We can do that by column  so that the elements of `a` are visited in memory order.  

for (int  n = 0; n < N; ++n)
  for (int m = 0; m < M; ++m)
    do-something(a, m, n)
```

We can then transpose at the end using Eigen's block-based transposition function,


```
matrix b = a.transpose();
```

And it feels like we've filled `b` by row, whereas we really filled `a` by column and transposed.

**Pull request merged**
