### PR TITLE
Feature/make stan functions

### LINKED ISSUE #2740: stan-functions.txt is not created anymore
#### Summary:

The make target to create the stan-functions.txt file used in RStan and RStudio was eliminated when we went to the RMarkdown-based documentation.

#### Description:

The make target to create the stan-functions.txt file used in RStan and RStudio was eliminated when we went to the RMarkdown-based documentation.

#### Reproducible Steps:

```
find . -type f -name "stan-functions.txt" -print
```

#### Current Output:

Nothing

#### Expected Output:

Nothing but we used to create it

#### Additional Information:

None

#### Current Version:
v2.18.1

### PR DESCRIPTION
**Pull request by bgoodri**
#### Submission Checklist

- [ ] Run unit tests: `./runTests.py src/test/unit` Does not touch C++ code
- [X] Run cpplint: `make cpplint`
- [X] Declare copyright holder and open-source license: see below

#### Summary

Adds a `make` target to create the stan-functions.txt file that we had before the switch to RMarkdown-based documentation

#### Intended Effect

Fixes #2740

#### How to Verify

```
make manual
```

#### Side Effects

None

#### Documentation

None

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Trustees of Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by bob-carpenter** [comment]
I can approve this when the conflicts are resolved.

I thought an alternative was created to the earlier code, which is why I deleted it in an earlier PR.

**Comment by bgoodri** [comment]
Does this have to be moved into the docs repo now?

**Comment by bob-carpenter** [comment]
I'm not sure what the plan is.  Hopefully @mitzimorris or @seantalts will know.

**Comment by mitzimorris** [comment]
all functions signatures were converted into HTML comments in the .Rmd files.
in the docs repo, this command will get you the function sigs:
`grep '^<!--' src/functions-reference/*.Rmd`

there are 666 of them.

**Comment by bgoodri** [comment]
But we had 711 signatures in 2.18.x

**Comment by mitzimorris** [comment]
OK - looks like conversion didn't get all sigs for the built-in functions but did for the distributions.
will fix.

**Comment by mitzimorris** [comment]
https://github.com/stan-dev/docs/issues/42

**Pull request closed without merging**
