### PR TITLE
Maintenance/issue 2401 remove unnecessary standalone code try 2

### PR DESCRIPTION
**Pull request by sakrejda**
#### Submission Checklist

- [X] Run unit tests: `./runTests.py src/test/unit`
- [X] Run cpplint: `make cpplint`
- [X] Declare copyright holder and open-source license: see below

#### Summary

Issue #2401, there's some unnecessary code for getting standalone functions working in rstan.  Also changed how standalone functions are generated (matching PR in rstan) so that the functions are generated inside namespaces and a wrapper is generated _outside_ the namespace that calls the generated function with its fully qualified name.  Should reduce namespace pollution when using generated code.  Finally, I changed the comment tag that's generated for each function to be generic rather than Rcpp-specific since we have to do a little text-replacing in rstan anyway, as would any other interface that had to decide what to export.  The new tag for each wrapper function is:

```
// [[stan::function]]
```

Also thinned out some excessive includes.

#### Intended Effect

Remove unused generated code.  Make standalone functions easier to compile from rstan.

#### How to Verify

Run tests, they should all pass.  The rng helper is gone.

#### Side Effects

None, nobody relies on this code, AFAIK, outside of rstan which is getting a matching PR.

#### Documentation

NA

#### Copyright and Licensing

Krzysztof Sakrejda

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by sakrejda** [comment]
No idea why this passed locally.

**Comment by sakrejda** [comment]
@seantalts a test failed, I edited the test locally and pushed to the branch this PR is based on but the commit is not showing up here and the testing hasn't re-started.  What do I do to make the commit show up and restart testing?

**Comment by seantalts** [comment]
@sakrejda Github had a hiccup; I noticed it in my own testing. It seems to be working again.

**Comment by seantalts** [comment]
I actually think Github is still hiccupping... There's a big lag between my own `push` being accepted and the webhook triggering to Jenkins, and I think even between the push registering and the changes appearing live in the repo or on the pull requests, for example... I don't think there's much we can do about it besides wait, unfortunately - even manually triggering the jobs does not seem to pull the latest commit.

**Comment by seantalts** [comment]
https://status.github.com/messages

**Comment by sakrejda** [comment]
@seantalts ok, I get it now, thanks.

**Comment by sakrejda** [comment]
Jenkins retest this please

**Comment by sakrejda** [comment]
Wow, I think this would pass if I just put in the `ast.hpp` include but it's fascinating trying to resolve the specific includes required.

**Comment by sakrejda** [comment]
@mitzimorris this is ready to review, it goes with a PR in rstan but should be reviewed independently.  The goal was to get something more generic in here that could play better with Rcpp (and potentially any other C++ interface).  If you can suggest tests to make this easier to maintain into the future I can add some, previously it doesn't seem like there many but then again the component functions well tested. IDK.  I think it's either you or @bob-carpenter who need to review (?)

**Comment by sakrejda** [comment]
This PR is blocking rstan from deleting a whole bunch of hacks to implement standalone functions.  No idea when the next rstan release is happening but it would be great to get this in and reduce the frustration people have with using standalone functions.

**Comment by sakrejda** [comment]
Thanks Mitzi!

**Pull request merged**
