### PR TITLE
Feature/bounds no inf

### LINKED ISSUE #2994: Removing special inf behavior on lower/upper and lower+upper bounds
#### Summary:

There's a Math issue on this [here](https://github.com/stan-dev/math/issues/2291)

Previously we've made it so that a -inf lower bound is the same as an unconstrained variable.

There were two outstanding problems with this:
1. A varying lower bound that goes to -infinity is not differentiable from the finite-constrain to infinite-constrain transition. I guess that seems a bit silly to worry about, but we allow the bound to vary and this isn't correct (Math issue has more details)

2. The inf behavior was not coded in Math correctly for vectors -- if any element of the vector was -inf then the whole vector was left unconstrained

I removed the special inf behavior in Math [here](https://github.com/stan-dev/math/pull/2285) and so the tests need removed in Stan for upstream tests to pass there.

Edit: To be clear, the Math functions throw errors now so this should give a coherent error to anyone who is taking advantage of the behavior that `real<lower=-inf> a;` is the same as `real a;`.

#### Current Version:
v2.25.0

### PR DESCRIPTION
**Pull request by bbbales2**
#### Submission Checklist

- [x] Run unit tests: `./runTests.py src/test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary

Fix #2994

#### Side Effects

Infinite bounds are not okay any more

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by bbbales2** [comment]
@rok-cesnovar Ack, actually Rok this pull and [this](https://github.com/stan-dev/math/pull/2285) pull (Math) will needed synced. There's a test here that is tested expected behavior of the lower/upper bounds in Math, and I'm changing that behavior because it doesn't quite make sense (https://github.com/stan-dev/stan/issues/2994 and https://github.com/stan-dev/math/issues/2291).

What is the routine for something like this? I could just remove the tests here temporarily and add them back once Math is in (the functions are tested in Math).

**Comment by rok-cesnovar** [comment]
The routine is the math tests are started pointing to this PR in Jenkins which makes the problematic test pass.

And this PR should point to that Math. The Travis test will fail but we will ignore that.

Are both prs ready? If so I can handle Jenkins.

**Comment by bbbales2** [comment]
@rok-cesnovar not ready yet -- so I need to:

1. Point this at the proper Math
2. Get this reviewed
3. Get Math reviewed

And then ping you?

**Comment by rok-cesnovar** [comment]
The pointing happens in jenkins. The Stan PR should not touch the submodule. So just 2 & 3and the ping me.

**Comment by bbbales2** [comment]
Okay cool, thanks!

**Comment by SteveBronder** [comment]
For this could we just delete these infinity tests in one PR, then when the constrains PR is merged to math add the new ones?

**Review by rok-cesnovar — APPROVED** [review]
Good

**Pull request merged**
