### PR TITLE
fixes #1754 allowing empty indexes

### LINKED ISSUE #1754: Error: no member named 'deep_copy' in namespace 'stan::model'
I'm running rstan (Version 2.9.0, packaged: 2016-01-05 16:17:47 UTC, GitRev: 05c3d0058b6a) and R version 3.2.3 (2015-12-10) on Mac OS X.

With the simple test model:
````
data {
  matrix[5, 2] X;
}

transformed data {
  matrix[5, 2] Xt;

  Xt <- X;
  Xt[,2] <- Xt[,2] / sd(Xt[,2]);
}

parameters {
  real a;
}

model {
  to_vector(Xt) ~ normal(a, 1.0);
}
```

I'm getting the following error:
````
Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! file3ae4a3a3ab.cpp:74:38: error: no member named 'deep_copy' in namespace 'stan::model'
                        stan::model::deep_copy(divide(stan::model::rvalue(Xt, stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list())), "Xt"),sd(stan::model::rvalue(Xt, stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list())), "Xt")))), 
                        ~~~~~~~~~~~~~^
1 error generated.
make: *** [file3ae4a3a3ab.o] Error 1
````

My naive search of the repository for deep_copy.hpp in GitHub seems to indicate that 
`#include <stan/model/indexing/deep_copy.hpp>`
is only present in the test case for deep copying but nowhere else.

### PR DESCRIPTION
**Pull request by bob-carpenter**
#### Summary:

Allow empty indexes on LHS of assignments.

#### Intended Effect:

Complete the index slicing feature.

#### How to Verify:

New unit tests that fail in 2.9.0 but succeed now.  New integration test good model, which tests the models with empty indexes compile and that the deep-copy header is included as intended.

#### Side Effects:

None.

#### Documentation:

This brings code functionality up to doc, so doc is already done.

#### Reviewer Suggestions:

Anyone.

### CODE REVIEW

**Comment by bob-carpenter** [comment]
This looks like something unrelated to my pull request that's failing in the upstream test for CmdStan;  here's the relevant outtake:

```
In file included from src/cmdstan/main.cpp:1:
src/cmdstan/command.hpp:82:10: fatal error: 'stan/services/diagnose/diagnose.hpp' file not found
#include <stan/services/diagnose/diagnose.hpp>
         ^
1 error generated.
```

**Comment by syclik** [comment]
That's my fault. I'll retest it.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
Great! Thanks, Bob.

**Pull request merged**
