### PR TITLE
Put clang-format before linting (Issue #2966)

### LINKED ISSUE #2966: clang-format happens after lint
#### Summary:

The format happens after the linting and then it's too late.

Here's an example: https://jenkins.mc-stan.org/blue/organizations/jenkins/Stan/detail/PR-2894/6/pipeline/46

Had to get it to pass linting to get to formatting.

#### Current Version:
v2.24.0

### PR DESCRIPTION
**Pull request by bbbales2**
#### Submission Checklist

- [x] Run unit tests: `./runTests.py src/test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary

Fixes #2966 I hope

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Review by rok-cesnovar — APPROVED** [review]
Good call. Thanks!

**Comment by rok-cesnovar** [comment]
@serban-nicusor-toptal Nic, would you mind setting the parallel for AWS linux machine to something less then 18, lets try 12? It seems the instances run out of memory compiling 18 models in parallel and I don't think we need to make them beefier. Thanks!

This has nothing to do with this PR but a bunch of Stan tests have failed in the integration tests on Linux due to this.

**Comment by serban-nicusor-toptal** [comment]
@rok-cesnovar Sure! I'll change this later today as I need to wait for the queue to finish first.

**Comment by rok-cesnovar** [comment]
Sure, no problem. Though most of these will probably fail: https://jenkins.mc-stan.org/blue/organizations/jenkins/Stan/activity?branch=downstream_tests
So we might as well cancel them, fix this and restart them, I think.

**Comment by serban-nicusor-toptal** [comment]
Hmh I see okay, give me a few minutes.

**Comment by rok-cesnovar** [comment]
No rush on a Friday evening :)

**Pull request merged**
