### PR TITLE
Feature/issue 1222 autodiff reorg

### PR DESCRIPTION
**Pull request by rtrangucci**
#### Summary:

Reorganization of math library in order to break cross dependencies within headers and tests.

#### Intended Effect:

There are several intentions with the reorganization:

* Break interdependencies between headers and unit tests along two axes: container type, and scalar type
  * Allows C++ users access to primitive-only, reverse-mode-only, fwd-mode-only versions of Stan's math library
  * Allows C++ users access to Eigen-free and std::vector-free versions of Stan's math library    
* Allow for intuitive navigation of file directories
* Move each function to its own header file

Organization proceeded according to the map:

[scalar-type]/
  [container-type]/
    [functional specification]/

stan/
  math/
    fwd/
      arr/      
      mat/
      scal/
        err/
        fun/
        functor/
        meta/
        prob/
      
    rev/
    prim/

#### How to Verify:

`make test-math-dependencies | wc -l`

should return 72. The remaining math dependencies almost exclusively lie within stan/math/scal/meta/, where VectorView and OperandsAndPartials proved to be too complex to tear apart at this stage. However, this a major step in the right direction. 

#### Side Effects:

In the current branch, there are order dependencies in some of the template meta-programs that did not exist previously (which was function of how tangled the headers were, rather than a sign of scrupulous layout).

See issue #1312 

#### Documentation:

New doxygen doc needs to be written, however it will be handled in a separate issue.

#### Reviewer Suggestions:

Bob, Daniel, Rob

### CODE REVIEW

**Comment by rtrangucci** [comment]
Jenkins, retest this please!

**Comment by rtrangucci** [comment]
Jenkins, retest this please

**Comment by rtrangucci** [comment]
Jenkins, retest this please

**Comment by bob-carpenter** [comment]
Tests should automatically get kicked off when you merge.
I think the polite retest command is just to nudge Jenkins
after it goes down for some reason.  Daniel will know for sure.

**Comment by rtrangucci** [comment]
Absolutely, understood. The problem is that the workspace needs to be wiped out before testing a radical new reorg so the auto merge build is flawed and almost certainly will fail. Need to manually clear the workspace and kick off again.  

Rob

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
I have no idea what went wrong. It said it ran out of disk space. I'll just put it back on the testing queue. Hopefully it'll work next time.

**Pull request merged**
