### PR TITLE
Refactor indexing functions

### PR DESCRIPTION
**Pull request by t4c1**
#### Submission Checklist

- [ ] Run unit tests: `./runTests.py src/test/unit`
- [ ] Run cpplint: `make cpplint`
- [ ] Declare copyright holder and open-source license: see below

#### Summary

Refactors indexing functions to simplify them including:
 - renames `lvalue.hpp` to `assign.hpp` and `lvalue_varmat.hpp` to `assign_varmat.hpp` to match functions implemented in them
 - deletes unused `rvalue_return` metaprogram
 - changes signatures of `rvalue` and `assign` functions:
 - deletes unused argument depth
 - removes default value from name argument to allow for the next change
 - replaces `cons_index_list` structure with (possibly variadic) argument list of indices. This makes `cons_index_list` and related functions redundant so they are removed.

#### Intended Effect

The generated code that uses indexing is more readable.

#### How to Verify

The changes are tested by changed tests.

#### Side Effects

This changes the interface of indexing functions. So it needs to be merged together with changes in stanc that will generate code according to the new interface.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Tadej Ciglarič

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by SteveBronder** [comment]
Should we make a new set for functions like `subset` to keep backwards compatability?

**Comment by t4c1** [comment]
Do we need to be backwards compatible here? Is not this repo only used by stanc?

**Comment by rok-cesnovar** [comment]
I dont think this is required to be backwards compatible. These are only used in the generated C++ model and are just an helper function for use of Stac3 with Stan Math. This is not like the services or anything.

**Comment by t4c1** [comment]
Moved to original repo from the fork. New PR is #3011.

**Pull request closed without merging**
