### PR TITLE
Feature/issue 795 remove double underscore

### PR DESCRIPTION
**Pull request by syclik**
#### Submisison Checklist

- [x] Run unit tests: `./runTests.py src/test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary
Removes `__` from identifiers, which is reserved by the C++ spec.

This can't be merged until #1751.

#### How to Verify
Search Stan for `__`. It'll only be found for `lp__` and other header columns for the csv.

#### Side Effects
This technically breaks backwards compatibility, but isn't an issue in practice.

#### Documentation
None.

#### Reviewer Suggestions
Anyone.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by syclik** [comment]
No one needs to review this yet. We need to wait for #1751.

**Comment by bob-carpenter** [comment]
This won't work.  The double underscores are needed in the generated code unless we want to change the definition of variables in Stan (breaks backward compatibility) or add new reserved words (for all these double underscored variables).

So let's rethink the generated code vs. the Stan code and restrict this to just the original code.   If you're OK with that, I can deal with the merge.

**Comment by syclik** [comment]
I was actually going to remove my changes to the language portion just for that reason. I did the first pull request a long time ago when I was tired and didnt think through the implications. 

I couldn't figure out the git magic to make it work. I'll do that soon if you can't make it work.

**Comment by bob-carpenter** [comment]
If that's the only issue, just leave it and I'll
deal with it after the generator refactor merge.

- Bob

**Comment by bob-carpenter** [comment]
@syclik I'm closing this because it now has merge conflicts and you said there was more you wanted to do on it.

**Comment by syclik** [comment]
Yup. Thanks. Sorry, I should have closed it a while ago.

**Pull request closed without merging**
