### PR TITLE
Feature/issue 1387 reduce cpplint warnings

### PR DESCRIPTION
**Pull request by syclik**
#### Summary:

Reduces cpplint warnings by removing spaces at the end of lines.

#### Intended Effect:

Only spaces at the end of lines were deleted. This removes 6,178 end of line warnings from our cpplint output.

#### How to Verify:

See the changes.

#### Side Effects:

This will probably lead to some conflicts on 

#### Documentation:

None.

#### Reviewer Suggestions: 

Anyone, but if this is accepted, it's better getting in sooner rather than later.

### CODE REVIEW

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by bob-carpenter** [comment]
Looks OK to me, though I didn't review all 748 files.  I sure hope you scripted this one!

I have only two branches open now with fairly minimal changes, so I'm OK dealing with the conflicts.  You may want to check with everyone else.

**Comment by syclik** [comment]
I used an emacs macro, but I probably should have scripted it. I wanted to
make sure I opened each file that I changed individually to make sure there
weren't any weird gotchas.

I have about a third of the open branches and I'm willing to go through the
conflicts.

Anyone with trouble, I'll help. This should be an easy merge, if there are
any conflicts.

**Comment by bob-carpenter** [comment]
Daniel:

It's nice that you're offering to help, but the problem
is that you're not there at the point someone checks out 
a branch, does a pull, and sees merge conflicts.  Even
if they're easy, it's a pain to find all the <<< and whatnot
and inspect and then erase.

I can't believe you did that with an emacs macro!  You're
a madman.

- Bob

**Comment by syclik** [comment]
Understood. That's why I'm trying to get these pull requests that are
fairly safe, but disruptive reviewed and merged quickly. Hopefully the next
person that has to branch will have this already in their develop branch
before they start.

And if anyone has trouble merging, let me know. I'm volunteering to help
work out this merge conflict.


Daniel

**Comment by syclik** [comment]
I'll be proactive about this one. After this gets merged in, I'll work on updating all the active branches.

**Comment by bob-carpenter** [comment]
Now would be a good time for anyone else to chime in on
Daniel's plan to enforce CppLint on Jenkins for pull requests.

I, for one, will take Daniel up on his offer to proactively
fix the conflicts that his current suggested merge will cause. 
Let me know when the dust settles and I can get back to work
on stan-dev/stan.

Also, it looks like they want a space after every comma.
I can live with that, but it's a huge change in our code base.

If you're going to go through all the files and delint them, 
could you do the comma spacing while you're at it?  I'd 
rather take my lumps all at once than have these changes
come out one at a time. 

Is there some description of what those lint warnings
mean?  For instance, this line of generator.hpp
has a "whitespace comment" warning:

2630         << EOL; // resize 0 with var_resizing

Am I supposed to jam "//" and "resize" together?  I think
that's a very bad idea.

Can we perhaps get a description of the ones you want to
enforce and what we need to do to comply?

I hope that didn't sound too crabby.

- Bob

**Comment by syclik** [comment]
Now would be a good time for anyone else to chime in on
    Daniel's plan to enforce CppLint on Jenkins for pull requests.

Yes. Any objections to having a common style with mostly sensible rules that we can change in the future?


    I, for one, will take Daniel up on his offer to proactively
    fix the conflicts that his current suggested merge will cause. 
    Let me know when the dust settles and I can get back to work
    on stan-dev/stan.

Bob, I think you've convinced me to do a single sweep that kills more warnings. I'm going to untag this label and fix more of them before merging this pull request.

    Also, it looks like they want a space after every comma.
    I can live with that, but it's a huge change in our code base.

If this doesn't bother you, we can ignore this rule. We can walk through every single rule we've implemented and see if that makes sense.

    If you're going to go through all the files and delint them, 
    could you do the comma spacing while you're at it?  I'd 
    rather take my lumps all at once than have these changes
    come out one at a time. 

Sure. Feel free to work on whatever branch you're working on -- I'll try to update this pull request as soon as possible. It'll be harder to review, but it might be worth it if we can just do one bigger merge.

    Is there some description of what those lint warnings
    mean?  

Yes. See this page (hosted on google code, so who knows where it'll go):
http://google-styleguide.googlecode.com/svn/trunk/cppguide.html

The settings we use are in `make/test` and the relevant portion of the rules we ignore is in the filter argument:
--filter=-runtime/indentation_namespace,-readability/namespace,-legal/copyright,-whitespace/indent,-runtime/reference

    For instance, this line of generator.hpp
    has a "whitespace comment" warning:
    
    2630         << EOL; // resize 0 with var_resizing
    
    Am I supposed to jam "//" and "resize" together?  I think
    that's a very bad idea.

No, it wants you to put two spaces after `EOL;` instead of one. There's a description in the warning... it might take a few clicks to get there.
    
    Can we perhaps get a description of the ones you want to
    enforce and what we need to do to comply?

Do you want me to open up an email thread and we can discuss the ones we want to enforce? I thought we did that a while ago and there weren't objections then.

    I hope that didn't sound too crabby.

Not at all. I'm glad you brought up these things. They're important to keeping Stan up and running.

**Comment by bob-carpenter** [comment]
Could you give me some time to digest and comment on the
lint warnings?  Does Cpplint follow that guide?

And can we give everyone else some time to comment before
merging changes?  Getting rid of spaces before newline is
not going to bother anyone other than the merge conflicts.

Luckily for me, that style guide pretty much agrees with my
own preferences, such as 

  if(condition) {   // Bad - space missing after IF.
  if (condition){   // Bad - space missing before {.
  if(condition){    // Doubly bad.

And also with where to put braces.  

I've seen some really whacky formatting in Boost.  Check out
Boost Exceptions for an example:

void
g()
    {
    try
        {
        f();
        }
    catch(
    my_error & x )
        {
        if( int const * mi=boost::get_error_info<my_info>(x) )
            std::cerr << "My info: " << *mi;
        }
    }

Seriously, I couldn't make this up if I tried. 

http://www.boost.org/doc/libs/1_57_0/libs/exception/doc/tutorial_transporting_data.html

I guess that's what happens when people get creative and
there are no project-wide style guides.  

- Bob

**Comment by vladimir-ch** [comment]
Just a tiny, outsider's comment: As for formatting of C++ source code, I can't praise `clang-format` enough.

**Comment by syclik** [comment]
On Thu, Mar 19, 2015 at 1:40 AM, Bob Carpenter <notifications@github.com>
wrote:

> Could you give me some time to digest and comment on the
> lint warnings? Does Cpplint follow that guide?
>

Yes, of course. And yes, that's the C++ guide that's implemented in
cpplint. We can turn off any of those warnings across the board. We can
also annotate individual exceptions of cpplint rules through comments.


>
> And can we give everyone else some time to comment before
> merging changes? Getting rid of spaces before newline is
> not going to bother anyone other than the merge conflicts.
>

Absolutely. Should I just close this pull request and reopen it later?

Luckily for me, that style guide pretty much agrees with my
> own preferences, such as
>
> if(condition) { // Bad - space missing after IF.
> if (condition){ // Bad - space missing before {.
> if(condition){ // Doubly bad.
>
> And also with where to put braces.
>

It also agrees with my preferences. It would give you warnings about only
having a single space between code and the comment. It wants a minimum of
two spaces.



> I've seen some really whacky formatting in Boost. Check out
> Boost Exceptions for an example:
>
> void
> g()
> {
> try
> {
> f();
> }
> catch(
> my_error & x )
> {
> if( int const * mi=boost::get_error_info<my_info>(x) )
> std::cerr << "My info: " << *mi;
> }
> }
>
> Seriously, I couldn't make this up if I tried.
>
>
> http://www.boost.org/doc/libs/1_57_0/libs/exception/doc/tutorial_transporting_data.html
>
> I guess that's what happens when people get creative and
> there are no project-wide style guides.
>

**Comment by syclik** [comment]
Thanks! This is the first time I'm hearing of clang-format. I'll take a
look.

**Comment by betanalpha** [comment]
I’m for rigid formatting so long as we have the enforced
rules clearly listed on the Wiki somewhere so I know how
to whip up some scrips to fix any of my code.  Being
able to run cpplint locally is, of course, also needed.

**Comment by syclik** [comment]
I'm closing this pull request for now. I'll reopen later when we're ready.

**Pull request closed without merging**
