### PR TITLE
move semantics for stan::mcmc::sample

### PR DESCRIPTION
**Pull request by kedartal**
Added explicit default copy and move c'tor and assignment operator, and made the d'tor default (instead of an explicit no-op), to enable move semantics for stan::mcmc::sample

Addresses issue #2646.

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Tal Kedar
By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by kedartal** [comment]
Looks like the CI build failure is unrelated to the change, please advise.

**Comment by syclik** [comment]
@kedartal, sorry... it should clear up by tomorrow. For some explanation, see: https://discourse.mc-stan.org/t/makefiles-prs-about-to-go-in-for-math-stan-and-cmdstan/5757/7

**Comment by syclik** [comment]
(you've submitted your PR right when things are unstable across repos; if this was in Math, it would have been fine.)

**Comment by kedartal** [comment]
@syclik cool, thanks! I'll try again tomorrow.

**Comment by kedartal** [comment]
@syclik something like https://github.com/stan-dev/stan/issues/2646 ?

**Comment by kedartal** [comment]
@bob-carpenter @syclik Can you please merge when you have a second? I'm not privileged enough :)

**Pull request merged**
