### PR TITLE
Remove unused 'filename' param in stan::lang::parse

### PR DESCRIPTION
**Pull request by ariddell**
#### Summary:

This pull request removes the unused `filename` parameter for the function `parse` (in stan/lang/parser.hpp) and updates all locations where the function is called.

#### How to Verify:

Unit tests pass. Check (previous versions of) stan/lang/parser.hpp to verify that `filename` was unused.

#### Side Effects:

None. No interface uses the parameter.

#### Documentation:

NA

#### Reviewer Suggestions: 

Anyone.

### CODE REVIEW

**Comment by sakrejda** [comment]
@ariddell, I think you left some loose ends hanging in one of the tests.

**Comment by ariddell** [comment]
Thanks @sakrejda. I didn't notice the failure. I think it should be fixed now. I'm running the test suite locally now.

**Comment by bob-carpenter** [comment]
Thanks --- the code here looks good.  It's failing upstream in integration with CmdStan.

So I believe there needs to be a matching CmdStan pull request.  I'm not sure how Daniel wants those organized or what we do for automated testing.

**Comment by sakrejda** [comment]
Jenkins says:

 > /usr/bin/git rev-parse feature/issue-277-writer^{commit} # timeout=10
 > /usr/bin/git rev-parse refs/remotes/origin/feature/issue-277-writer^{commit} # timeout=10
 > /usr/bin/git rev-parse feature/issue-277-writer^{commit} # timeout=10
ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job.
Recording test results
ERROR: Step ‘Publish JUnit test result report’ failed: No test report files were found. Configuration error?
Finished: FAILURE

@syclik I'm happy to do the legwork for upstream pull requests but this makes it seem like might just be a Jenkins thing, any suggestions about next steps?

**Comment by sakrejda** [comment]
Shoot, never mind, that really is looking for a matched-by-name CmdStan pull request! (?) Why is that triggered when these changes are supposed to just be dead code? Still lost.

**Comment by ariddell** [comment]
I'm not sure it's cmdstan. cmdstan just uses stan directly. Here's the entirety of cmdstan's stanc.cpp

```
#include <stan/command/stanc_helper.hpp>

/** 
 * The Stan compiler (stanc).
 *
 * @param argc Number of arguments
 * @param argv Arguments
 * 
 * @return 0 for success, -1 for exception, -2 for parser failure, -3
 * for invalid arguments.
 */
int main(int argc, const char* argv[]) {
  return stanc_helper(argc,argv,&std::cout,&std::cerr);
}



```

**Comment by ariddell** [comment]
@syclik What's needed here? Do we need an empty PR in cmdstan?

**Comment by syclik** [comment]
We just need to get the commits into the stan-dev/stan repo. (Don't need to redo anything, just checkout the branch and push to a remote branch.) I can do this later.

We test upstream now to make sure we don't run into integration problems.

**Comment by ariddell** [comment]
pushed it to branch feature/issue-1752-remove-parse-filename

**Comment by syclik** [comment]
thanks.

**Comment by ariddell** [comment]
@syclik So the following branches are aligned

- ariddell/stan/feature/remove-parse-filename
- stan-dev/feature/issue-1752-remove-parse-filename

Was calling them different things a mistake?

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
thanks.

no, there's no issue with the name. we just need the commits to exist on the public repo.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Pull request merged**
