### PR TITLE
Feature/issue 1526 manual 2.8.0

### PR DESCRIPTION
**Pull request by bob-carpenter**
#### Summary:

Fix all known issues with manual for 2.8.0.

#### Intended Effect:

See summary.

#### How to Verify:

Check all those checkboxes.

#### Side Effects:

no

#### Documentation:

yes

#### Reviewer Suggestions:

anyone

### CODE REVIEW

**Comment by jgabry** [comment]
Did you remove all mc-stan.org email addresses (if there were any)? That
checkbox is still unchecked.

**Comment by bob-carpenter** [comment]
I thought I had, but it looks from grep like I missed one.

Fixed and pushed.

- Bob

**Comment by syclik** [comment]
@bob-carpenter, I'm going to leave this pull request open until we're ready to go.

**Comment by bob-carpenter** [comment]
Sounds good.  I don't have any more things to add, but you
never know what'll turn up.

- Bob

**Pull request merged**
