### PR TITLE
Bugfix/issue 1476 lkj corr cholesky fvar

### PR DESCRIPTION
**Pull request by rtrangucci**
#### Summary:

Allows for fvar instantiation of lkj_corr_cholesky.

#### Intended Effect:

Admits higher-order autodiff of lkj_corr_cholesky density

#### How to Verify:

./runTests.py test/unit/math/mix/mat/prob/lkj_corr_test.cpp

#### Side Effects:

None.

#### Documentation:

None.

#### Reviewer Suggestions:

Anyone

### CODE REVIEW

**Comment by rtrangucci** [comment]
@syclik Should I move this over to math?

**Comment by syclik** [comment]
Yes, please. And thank you.

**Comment by rtrangucci** [comment]
@syclik When I tried to checkout develop of stan-dev/math and run the following:

`./runTests.py test/unit/math/fwd/scal/fun/acos_test.cpp `

I get this:

```
------------------------------------------------------------
make generate-tests -s
test/prob/generate_tests.cpp:9:10: fatal error: 'boost/algorithm/string.hpp' file not found
#include <boost/algorithm/string.hpp>
         ^
1 error generated.
make: *** [test/prob/generate_tests] Error 1
make generate-tests -s failed
exit now (07/05/15 18:06:50 EDT)
```

**Comment by syclik** [comment]
Yeah -- so once the math library is sitting inside Stan, we won't have this
problem. I just added instructions to the top level readme in the math
library. You need to set the STANAPI_HOME make variable in the math
library's make/local file.

**Comment by syclik** [comment]
This has been moved to pull request: stan-dev/math#15

**Pull request closed without merging**
