### PR TITLE
Bugfix/2119 abs fabs vec

### PR DESCRIPTION
**Pull request by bob-carpenter**
#### Submisison Checklist

- [x] Run unit tests: `./runTests.py src/test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary

Remove abs vectorization and restore its original signatures; add fabs and lgamma vectorization. 

#### Intended Effect

Not break backward compatibility for abs and add vectorization for remaining functions.

#### How to Verify

Unit tests.

#### Side Effects

No.

#### Documentation

Yes, in manual.

#### Reviewer Suggestions

anyone

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by bob-carpenter** [comment]
This pull request depends on the math lib pull request: https://github.com/stan-dev/math/pull/438

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by bob-carpenter** [comment]
I think it's blocking on the available of fabs, which should be in the matching stan-dev/math patch.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Pull request merged**
