### PR TITLE
update tests to use = instead of <- for assignment in the example tests

### PR DESCRIPTION
**Pull request by SteveBronder**
#### Submission Checklist

- [x] Run unit tests: `./runTests.py src/test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary

If you look at the output of the Jenkins pipeline there's like a million lines of warning messages like 

```
Warning: deprecated language construct used in 'src/test/test-models/good/function-signatures/distributions/univariate/continuous/pareto_type_2/pareto_type_2_cdf_log_1.stan', line 1719, column 26:
   -------------------------------------------------
  1717:    transformed_param_real <- pareto_type_2_cdf_log(d_real_array, d_real, d_int, d_row_vector);
  1718:    transformed_param_real <- pareto_type_2_cdf_log(d_real_array, d_real, d_int, p_real);
  1719:    transformed_param_real <- pareto_type_2_cdf_log(d_real_array, d_real, d_int, p_real_array);
                                   ^
  1720:    transformed_param_real <- pareto_type_2_cdf_log(d_real_array, d_real, d_int, p_vector);
  1721:    transformed_param_real <- pareto_type_2_cdf_log(d_real_array, d_real, d_int, p_row_vector);
   -------------------------------------------------

assignment operator <- is deprecated in the Stan language; use = instead.
```

This just does a find replace in the test stan files for `<-` by replacing them with `=`

#### Intended Effect

Reduce the size of the pipeline's log message

#### Side Effects

Hopefully smaller pipeline.log file

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Steve Bronder

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by SteveBronder** [comment]
lol I just downloaded the log file and it's almost half a gig in size

**Comment by SteveBronder** [comment]
Is this cool to merge?

**Comment by mitzimorris** [comment]
> This just does a find replace in the test stan files for <- by replacing them with =

the only files affected are `.stan` files under directory `test/test-models/good` ?
I see no reason why this shouldn't be merged.

**Review by rok-cesnovar — APPROVED** [review]
Looks good. The deprecation warnings for "<-" are tested in stanc3. These test models will eventually get replaced by stanc3 test models but no harm in having these fixed in the meantime.

**Pull request merged**
