### PR TITLE
Feature/issue 1389 gradient file split

### PR DESCRIPTION
**Pull request by rtrangucci**
#### Summary:

Address #1389 

#### Intended Effect:

Allows for uses of rev/mat/functor/gradient.hpp in other functors defined in rev/mat/ 

#### How to Verify:

Run src/test/unit/math/mix/mat/functor/autodiff_test.cpp

#### Side Effects:

If anyone's branch currently relies on using src/math/mix/mat/functor/gradient.hpp, the branch will need to update the include path to either:

src/math/fwd/mat/functor/gradient.hpp
src/math/rev/mat/functor/gradient.hpp

#### Documentation:

None.

#### Reviewer Suggestions: 

@syclik or @bob-carpenter

### CODE REVIEW

**Comment by syclik** [comment]
@rtrangucci, let's split out the gradient tests since we're splitting out the header. We should have one rev and one fwd test (the tests are there -- we just need to split out the test into two files.)

**Comment by rtrangucci** [comment]
Jenkins, retest this please!

**Comment by syclik** [comment]
Thanks. Looks good.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Pull request merged**
