### PR TITLE
Move JSON parser from CmdStan to Stan/io

### PR DESCRIPTION
**Pull request by WardBrian**
#### Submission Checklist

- [x] Run unit tests: `./runTests.py src/test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary

This is the first half of #3142 and undoes #2803 

#### Intended Effect

Move the JSON parser code from `cmdstan` to this repo. Tests are also moved. 

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Simons Foundation

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by bob-carpenter** [comment]
I can review this when it's ready as long as that's today or early tomorrow or some time later this week.

**Comment by WardBrian** [comment]
@bob-carpenter this should be ready as-is; it's just a copy-paste job with some renaming of namespaces.

**Review by bob-carpenter — APPROVED** [review]
thanks.  the renaming and updates to make all look good.

**Comment by rok-cesnovar** [comment]
The upstream tests fail because the CmdStan PR was merged, but since all other tests pass feel free to merge.

**Comment by rok-cesnovar** [comment]
I think it should be fine. The test that failed doesnt run on develop I believe.

**Pull request merged**
