### PR TITLE
Fixes #2364 - add C++11 support by including it from math's makefiles.

### LINKED ISSUE #2364: C++11 support
#### Summary:
use new downstream math library makefiles to enable C++11 in Stan code.

### PR DESCRIPTION
**Pull request by seantalts**
#### Submisison Checklist

- [x] Run unit tests: `./runTests.py src/test/unit`
- [x] Declare copyright holder and open-source license: see below

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by syclik** [comment]
@seantalts, this isn't high priority, right? It looks like it breaks the Windows tests. I'll need to log in to get to the bottom of it, I think.

**Comment by seantalts** [comment]
It's not high priority from my perspective.

Interesting error message... Don't immediately see the connection. Hm.

**Comment by seantalts** [comment]
Oh wait, I thought this was the one on the Math repo. This needs the math repo one first! I'll mark it WIP while it's waiting on that.

**Comment by seantalts** [comment]
Jenkins, retest this please.

**Comment by seantalts** [comment]
So this appears to be failing on g++ on Travis because the compiler runs out of memory (in the Travis logs it just says it hit an internal compiler bug, but when testing on my local Trusty VM it tells me that it's because it ran out of memory). 

Anyone know what to do about this? This has seemingly only changed with the addition of the `--std=c++1y` flag.

**Comment by seantalts** [comment]
@syclik I think this is ready for review (will trigger Jenkins tests again - was focusing on fixing travis the past few times so I'd been killing the Jenkins ones). The one worrying thing is that I had to turn down the parallelism on a bunch of these tests because GCC was taking more memory than the Travis VMs had available.

Jenkins, retest this please.

**Comment by syclik** [comment]
All the changes look straightforward.

Thanks for dealing with Travis. It's tricky and time-consuming. Glad you worked it out.

**Pull request merged**
