### PR TITLE
Feature/issue 1616 move services

### PR DESCRIPTION
**Pull request by syclik**
#### Summary:

Moves a handful of the services to different locations and updates namespaces.
Also renames a couple functions.

#### Intended Effect:

Gets closer to us fixing things for #1361.

#### How to Verify:

All Stan tests should pass with these changes.
None of the behavior changed with this pull request. (I could have just moved things and changed function names later, but I did it in one step. If anyone has a problem with it, I can back it out and do it in multiple steps.)

#### Side Effects:

Affects CmdStan, RStan, and PyStan.
I have a fix for CmdStan.
I will appropriately update RStan and PyStan.

#### Documentation:

None. Please indicate if more doc needs to be written (this is for both me and @betanalpha).

#### Reviewer Suggestions: 

@betanalpha.

### CODE REVIEW

**Comment by betanalpha** [comment]
It’s _really_ hard to guarantee anything given how much you’re ripping
this apart.  This _looks_ fine but there’s no way to tell until it’s all been
translated.

I still don’t see how all of these incremental changes are going to make
broken API routes in the interfaces any better integrated.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
This passes all tests except for the upstream test, so it's good to go. 

(The performance tests failed because I hadn't installed R on the machine yet.)

**Pull request merged**
