### PR TITLE
Feature/issue 1601 remove writer

### PR DESCRIPTION
**Pull request by syclik**
#### Summary:

Removing writer elements that are not common across the different interfaces. This is a refactor -- no behavior has changed within Stan.

#### Intended Effect:

Part of Michael's refactor.

#### How to Verify:

See that only files have been removed. All tests should pass.

#### Side Effects:

CmdStan will have to be updated. stan-dev/cmdstan#151. 
RStan will have to be updated. stan-dev/rstan#197.
PyStan will have to be updated. stan-dev/pystan#174.

I have fixes for CmdStan and RStan. I'll set up PyStan by the time this is reviewed and ready to be merged.

#### Documentation:

None.

#### Reviewer Suggestions: 

@betanalpha or @bob-carpenter.

### CODE REVIEW

**Comment by syclik** [comment]
I also have a branch for PyStan ready to go.

**Comment by betanalpha** [comment]
:thumbsup:

I’ll sign off on the interfaces as soon as they come out.

**Comment by betanalpha** [comment]
How has this not been merged yet?

**Comment by syclik** [comment]
cause you wanted to wait until 2.8.0 was out. and... it wasn't labeled as reviewed so I forgot about it.

**Comment by syclik** [comment]
and... it looks like not all tests passed, so I'll need to fix it too.

**Pull request merged**
