### PR TITLE
Remove JSON parser code from Stan

### PR DESCRIPTION
**Pull request by rok-cesnovar**
#### Summary

Removes the files that were moved to cmdstan in https://github.com/stan-dev/cmdstan/pull/726

This should be merged after the cmdstan PR is merged.

#### How to Verify

/

#### Side Effects

/

#### Documentation

/

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Rok Češnovar, University of Ljubljana

### CODE REVIEW

**Comment by seantalts** [comment]
Would you mind resolving the conflicts?

**Comment by rok-cesnovar** [comment]
Done, thank you for notifying me.

**Comment by rok-cesnovar** [comment]
The move was done on `cmdstan` end so these files can now safely be removed.

**Comment by rok-cesnovar** [comment]
Bumping this one, if anyone has time to review. This just removes 2500 lines by deleting the unused parser.

**Comment by SteveBronder** [comment]
I'm not supposed to approve stuff here but @seantalts do you mind if I slam this one in? (Or just do it when you read this)

**Comment by rok-cesnovar** [comment]
Not that huge of a hurry, but would like if it gets in 2.21.

**Pull request merged**
