### PR TITLE
Bugfix/issue 1230 fix checks extra vars

### PR DESCRIPTION
**Pull request by rtrangucci**
#### Summary:

Addresses #1230  

#### Intended Effect:

check_finite, check_semi_definite, check_not_nan no longer pass vars to boost::isfinite and boost::isnan, but rather pass var.val() to these functions using value_of_rec in pull request #1247 

#### How to Verify:

```
#include <iostream>
#include <stan/agrad/rev.hpp>
#include <stan/prob/distributions.hpp>

int main ()
{
  using stan::agrad::var;

  double lambda = 1.15;
  double mu = 1.1;
  double y = 1.5;

  var v_y(y);
  var v_mu(mu);
  var v_lambda(lambda);

  std::cout << "Instantiate 3 vars: y, mu, sigma \n" << std::endl;

  stan::agrad::print_stack(std::cout);

  std::cout << "Calling normal_log\n" << std::endl;

  var lp = stan::prob::normal_log(v_y, v_mu, v_lambda); 

  std::cout << "Called normal_log \n" << std::endl;

  stan::agrad::print_stack(std::cout);

  std::cout << "Calling pareto_log\n" << std::endl;

  var lp2 = stan::prob::pareto_log(v_y, v_mu, v_lambda); 

  std::cout << "Called pareto_log \n" << std::endl;

  stan::agrad::print_stack(std::cout);

  std::cout << "Calling exponential_log\n" << std::endl;

  var lp3 = stan::prob::exponential_log(v_y, v_mu); 

  std::cout << "Called exponential_log \n" << std::endl;

  stan::agrad::print_stack(std::cout);

  return 0;
}
```

This program should create 3 vars, and create only 1 var upon each subsequent call to a log-density. The final stack size should be 6.

#### Side Effects:

None.

#### Documentation:

None.

#### Reviewer Suggestions: 

Anyone.

### CODE REVIEW

**Comment by syclik** [comment]
@rtrangucci, this failed:
http://d1m1s1b1.stat.columbia.edu:8080/job/Stan%20Pull%20Request%20-%20Tests%20-%20Unit/153/console

**Comment by rtrangucci** [comment]
@syclik this depends on pr #1247 that @bob-carpenter is reviewing, so this should pass once I merge this with #1247

**Comment by syclik** [comment]
@rtrangucci, the code looks ok, but there aren't any tests that either:
1. show this behavior works or
2. prevent us from inadvertently making this mistake in the future

I think we should go through and add checks to all the error handling functions on the agrad side to make sure we're not adding more to our autodiff stack.

**Comment by rtrangucci** [comment]
@syclik thanks for looking over the code. I can write the tests today to check the size of the stack after calling each of the error handling functions on vars.

**Comment by syclik** [comment]
Cool. I can help out if you want. If you write one to show how to test it,
we can divvy up the tests.

**Comment by rtrangucci** [comment]
That would be great. I'll write a new test for check_not_nan, and we can
divvy up the tests this afternoon.


Rob

**Comment by syclik** [comment]
@rtrangucci, looks good. It looks like the matrix versions don't have the same tests, but I don't think that should hold us up.

**Comment by rtrangucci** [comment]
@syclik Thanks for looking this over. I debated adding the matrix tests, but I figured that fixing all the univariate bugs and the one matrix bug (check_pos_semidefinite) was sufficient for this release. I'll create a new pull request to add var tests for all the matrix checks.

**Comment by bob-carpenter** [comment]
I'll add it to the release notes :-)

Even a 5% speedup is fantastic.  The reduction in
memory may be even greater though, which is also a big
win.

- Bob

**Comment by syclik** [comment]
Awesome. Bob, can you add it to the zombie branch? I'll merge it tomorrow,
after this branch gets merged.

**Comment by bob-carpenter** [comment]
I already added the release note and pushed to the zombie.

- Bob

**Comment by syclik** [comment]
Awesome.

**Pull request merged**
