### PR TITLE
Bugfix/issue 1337 var ctor

### PR DESCRIPTION
**Pull request by bob-carpenter**
#### Summary:

Going back to explicitly typed var constructors to make the implicit promotions all work without ambiguity.  Requires an ifdef for `_WIN64` to add `var(size_t)` 

#### Intended Effect:

Allow all our models and tests to compile without C++11.

#### How to Verify:

Run tests.

#### Side Effects:

None.

#### Documentation:

Nothing user facing here.

#### Reviewer Suggestions:

Anyone.

### CODE REVIEW

**Comment by bob-carpenter** [comment]
As far as reviewing goes, this version has the same `var()` implementations as before, but without `long long` for Mac/Linux.   I don't think we need `long long`.

**Comment by syclik** [comment]
Looks good. Hopefully this doesn't wreak havoc on Windows 32 bit machines, but we'll take care of that if users have issues.

**Comment by bob-carpenter** [comment]
It shouldn't be a problem for Win32.  (More
famous last words.)

In Win32, size_t is unsigned int and ptrdiff_t is
int, so we already have that covered in the basic
constructors. 

- Bob

**Comment by syclik** [comment]
Great.

Want me to put that on a plaque and put it up in our office?

**Comment by bob-carpenter** [comment]
Too bad we don't have one of those brutalist buildings
beloved of computer science departments --- then we could
just carve it into our cinder block walls.

- Bob

**Pull request merged**
