### PR TITLE
Create FUNDING.yml

### PR DESCRIPTION
**Pull request by Dr-G**
add NumFOCUS github sponsors button (recurring donations only)

This feature launched today at GitHub Universe!

Also add the custom link to point to the donation form for Stan.

#### Summary
Add a Sponsor button to the Stan repo.

#### Intended Effect
Give users the ability to donate NumFOCUS, either the all-projects fund or the Stan-designated fund.

#### How to Verify
Should show you how it will look in the preview. See also here: https://help.github.com/en/github/building-a-strong-community/displaying-a-sponsor-button-in-your-repository

#### Side Effects
Mo' money, mo' problems.

#### Copyright and Licensing

---

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

NumFOCUS

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by Dr-G** [comment]
cc @syclik

**Comment by bob-carpenter** [comment]
Thanks for submitting the PR, @Dr-G.  

If followed the link, but didn't see an example of how the repo looks with a sponsor button.  Is there an example somewhere of what this does?

**Comment by bob-carpenter** [comment]
@Dr-G and @syclik:  We typically require an open-access license on any contributions.  This PR went around our usual form so doesn't have that.  I'm not sure how to rectify.  We're trying to keep our IP clean with contributors owning their IP and licensing it to the world.

**Comment by Dr-G** [comment]
You can see an example here: https://github.com/pandas-dev/pandas

Sorry if I didn't do the PR correctly. You can certainly just reject it and make the edit yourselves; I have no problem with that.

**Comment by bob-carpenter** [comment]
Thanks for the link.  Looks great and I think we should add such a button to our page.

We have a form that pops up from branch-generated PRs, but presumably you just did a direct edit and submit and didn't see it.

If you wouldn't mind editing the body of the PR to include the following (including copyright holder's name), I'd be happy to merge.

```
#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

[YOUR OR YOUR COMPANY'S NAME HERE]

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)
```

I would do it for you, but I can't assign your copyright.

If that's too much hassle, I can just add a PR myself.  We prefer to get outside contributions wherever possible to encourage a sense of openness.

Thanks, and sorry again for the hassle around this.

**Comment by Dr-G** [comment]
@bob-carpenter did that work?

**Comment by bob-carpenter** [comment]
@Dr-G Thanks!

**Comment by bob-carpenter** [comment]
@Dr-G  It doesn't seem to have done anything on the GitHub page.  I thought the link button was supposed to be there now.  Maybe it takes a while to get updated.

**Comment by Dr-G** [comment]
@bob-carpenter you may have to turn something on in "settings"

I'd double-check the [instructions doc](https://help.github.com/en/github/building-a-strong-community/displaying-a-sponsor-button-in-your-repository), too.

**Comment by Dr-G** [comment]
If that doesn't work, I can reach out to our GH contact for help.

**Comment by bob-carpenter** [comment]
I looked at the source behind the link on pandas:

```
custom: https://pandas.pydata.org/donate.html
github: [numfocus]
tidelift: pypi/pandas
```

whereas ours now has

```
github: numfocus
custom: https://numfocus.org/donate-to-stan
```

They bracketed `numfocus`.  I have no idea what `tidelift` is.

From: https://github.com/pandas-dev/pandas/blob/master/.github/FUNDING.yml

**Comment by Dr-G** [comment]
I wrote that code; at first I thought the brackets were necessary, but turns out it's really only if you're going to put more than one object (probably the wrong term) within the brackets.

Tidelift is a for-profit company that is working to support open source maintainers on a different business model: https://tidelift.com/about

**Pull request merged**
