### PR TITLE
Fixes variational eta argument

### PR DESCRIPTION
**Pull request by syclik**
Fixes argument bug introduced with #1638.

### CODE REVIEW

**Comment by dustinvtran** [comment]
I approve!

**Comment by syclik** [comment]
(I don't know what we should do to test these things... it wasn't clear
that this would break CmdStan [seg fault], but it did.)

**Comment by dustinvtran** [comment]
I'm writing unit tests in the `advi/internal-changes` branch, which will eventually be a pull request when I am finished. It's a complete overhaul of the ADVI code and current unit tests, as it was somewhat vague what each test was even testing for.

I'm not sure how to test the arguments themselves though.

**Comment by syclik** [comment]
cool. off topic and no response required: can you create an issue and name
the branch "feature/issue-#-description" so we have a hope of tracking
changes for releases?

**Comment by syclik** [comment]
This passed the Stan tests. We still don't have a good way to specify upstream branches.

**Comment by betanalpha** [comment]
https://github.com/stan-dev/cmdstan/blob/develop/src/test/interface/services/argument_configuration_test.cpp

tries to run every combinatorial combination of arguments — all combinations
of good values are expected to pass, any bad value is expected to cause a
failure.  The good/bad values are defined in the arguments themselves.

**Comment by syclik** [comment]
that test didn't fail on this branch.

in CmdStan, there's a cast to real_argument from string_argument that was
causing a seg fault.

**Comment by betanalpha** [comment]
Create an issue — my best guess is that the seg fault is short circuiting
the test which causes it not to fail.

**Comment by ariddell** [comment]
Is there anything I can do to help with this (i.e., this future pointer-less argument refactor mentioned by @syclik on the list)? Is there a branch working on this or is this on the backburner?

**Pull request merged**
