### PR TITLE
Bugfix/issue 1379

### LINKED ISSUE #1379: extra semicolons
I'm on it
```
goodrich@T540p:/opt/stan$ grep -F "warning:" /tmp/travis.txt | sort | uniq | sed 's@/usr/local/lib/R/site-library/StanHeaders/include@src@g'
src/stan/lang/grammars/functions_grammar_def.hpp:40:2244: warning: extra ';' outside of a function is a C++11 extension [-Wc++11-extra-semi]
src/stan/lang/grammars/statement_grammar_def.hpp:48:1773: warning: extra ';' outside of a function is a C++11 extension [-Wc++11-extra-semi]
src/stan/lang/grammars/statement_grammar_def.hpp:52:1767: warning: extra ';' outside of a function is a C++11 extension [-Wc++11-extra-semi]
src/stan/lang/grammars/statement_grammar_def.hpp:56:2312: warning: extra ';' outside of a function is a C++11 extension [-Wc++11-extra-semi]
src/stan/lang/grammars/statement_grammar_def.hpp:61:1273: warning: extra ';' outside of a function is a C++11 extension [-Wc++11-extra-semi]
src/stan/lang/grammars/statement_grammar_def.hpp:64:1273: warning: extra ';' outside of a function is a C++11 extension [-Wc++11-extra-semi]
src/stan/lang/grammars/statement_grammar_def.hpp:67:1281: warning: extra ';' outside of a function is a C++11 extension [-Wc++11-extra-semi]
src/stan/lang/grammars/statement_grammar_def.hpp:70:1361: warning: extra ';' outside of a function is a C++11 extension [-Wc++11-extra-semi]
src/stan/lang/grammars/statement_grammar_def.hpp:73:2234: warning: extra ';' outside of a function is a C++11 extension [-Wc++11-extra-semi]
src/stan/lang/grammars/statement_grammar_def.hpp:78:1788: warning: extra ';' outside of a function is a C++11 extension [-Wc++11-extra-semi]
src/stan/lang/grammars/term_grammar_def.hpp:53:4468: warning: extra ';' outside of a function is a C++11 extension [-Wc++11-extra-semi]
src/stan/lang/grammars/term_grammar_def.hpp:66:1729: warning: extra ';' outside of a function is a C++11 extension [-Wc++11-extra-semi]
src/stan/lang/grammars/term_grammar_def.hpp:70:1762: warning: extra ';' outside of a function is a C++11 extension [-Wc++11-extra-semi]
src/stan/lang/grammars/bare_type_grammar_def.hpp:28:1737: warning: extra ';' outside of a function is a C++11 extension [-Wc++11-extra-semi]
src/stan/lang/grammars/functions_grammar_def.hpp:34:2925: warning: extra ';' outside of a function is a C++11 extension [-Wc++11-extra-semi]
src/stan/lang/grammars/statement_grammar_def.hpp:44:1752: warning: extra ';' outside of a function is a C++11 extension [-Wc++11-extra-semi]
src/stan/lang/grammars/term_grammar_def.hpp:48:1750: warning: extra ';' outside of a function is a C++11 extension [-Wc++11-extra-semi]
src/stan/lang/grammars/term_grammar_def.hpp:62:1673: warning: extra ';' outside of a function is a C++11 extension [-Wc++11-extra-semi]

```

### PR DESCRIPTION
**Pull request by bgoodri**
Fixes #1379 

There are extra semicolons in these files which are technically a C++11 extension

### CODE REVIEW

**Comment by bob-carpenter** [comment]
Looks good to me.  Sorry for dropping them in --- it's just reflexive, but clearly this macro didn't need them.

**Comment by syclik** [comment]
I'll find out what's going on.

**Comment by syclik** [comment]
I have no idea -- maybe the machine ran out of memory.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
wtf? it tripped again. I'll figure it out. @bgoodri, you shouldn't need to
take any actions.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Pull request merged**
