### PR TITLE
PR Template warning

### PR DESCRIPTION
**Pull request by betanalpha**
#### Intended Effect:

Adds a friendly warning to check unit and cpplint tests in the PR template.

#### Reviewer Suggestions: 

Anyone.

### CODE REVIEW

**Comment by syclik** [comment]
Looks good! Would you be opposed to a checklist that we can leave at the top?

If not, I can update (I'm almost at the office now).

**Comment by betanalpha** [comment]
I have no objections to a checklist.

**Comment by syclik** [comment]
@bob-carpenter, is the licensing clear?
@betanalpha, I didn't add any to the checklist, even though I thought about it. I don't mind that our continuous integration server catches it. (although I'll have to dig through Jenkins config right now to see what's going on.)

**Comment by syclik** [comment]
thanks @betanalpha @bob-carpenter

**Pull request merged**
