### PR TITLE
Issue/3208 pathfinder typo

### PR DESCRIPTION
**Pull request by mitzimorris**
#### Submission Checklist

- [x] Run unit tests: `./runTests.py src/test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary

Fix typo.

#### Intended Effect

Improve console output .

#### How to Verify

Will be verified from CmdStan

#### Side Effects

N/A

#### Documentation

Console output in CmdStan guide, which is spell-checked.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by mitzimorris** [comment]
https://github.com/stan-dev/stan/issues/3208

**Review by SteveBronder — APPROVED** [review]
lgtm ty!

**Comment by mitzimorris** [comment]
I think this PR was subsumed by #3210

**Comment by WardBrian** [comment]
It was

**Pull request closed without merging**
