### PR TITLE
Feature/issue 1886 integrate ode

### PR DESCRIPTION
**Pull request by bob-carpenter**
#### Submisison Checklist

- [x] Run unit tests: `./runTests.py src/test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary

Add `integrate_ode_rk45` and `integrate_ode_bdf` functions with and without control arguments.  Deprecate unmarked `integrate_ode`.

#### Intended Effect

Enable stiff ODE solving, call out names of solvers in functions, and allow for user-specified control parameters.

#### How to Verify

Unit tests for integrators and for the language components.

#### Side Effects

* deprecation messages for old version, `integrate_ode()`

* interfaces must add `-DFUSION_MAX_VECTOR_SIZE=12` to makefile `CFLAGS` 

#### Documentation

ODE chapter rewritten in manual with clarifications on signatures and discussion of stiffnes.  New ODE chapter in function signatures reference manual.

#### Reviewer Suggestions

Anyone.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by bob-carpenter** [comment]
This won't pass integration tests until https://github.com/stan-dev/math/pull/294 is merged from math.

**Comment by syclik** [comment]
It should pass tests now. I've updated the submodule on this branch with the pull request updating math.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
woo hoo! This is finally passing tests. CmdStan not passing is due to needing to update the makefile there.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by bob-carpenter** [comment]
I still had quite a few edits that I hadn't pushed
for this branch.  None of them are major, though, so
it's OK by me to go with it as it was.

What's the best way for me to deal with edits on
a branch that just got committed for a future refactoring
patch?

- Bob

**Comment by syclik** [comment]
Bob, please push to the branch when you get a chance if you're ready. If
it'll take a few more days, I can go ahead and merge once tests are done.

Edits on branches that have been merged -- that's easy. Just keep working
on the branch. If you create a pull request, it'll know that the branch was
merged into develop, so there isn't an issue. If someone rebases
everything, it gets much trickier.

**Comment by bob-carpenter** [comment]
Cool.  Thanks.  That's easier than I thought it would be.

**Pull request merged**
