### PR TITLE
CI to use python3 on the mac instances

### PR DESCRIPTION
**Pull request by serban-nicusor-toptal**
#### Submission Checklist

- [ ] Run unit tests: `./runTests.py src/test/unit`
- [ ] Run cpplint: `make cpplint`
- [ ] Declare copyright holder and open-source license: see below

#### Summary

See: https://github.com/stan-dev/performance-tests-cmdstan/pull/41

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by WardBrian** [comment]
I don’t believe so, only the performance tests have changed

**Review by rok-cesnovar — APPROVED** [review]
Assuming things pass this looks 👍🏻

**Comment by WardBrian** [comment]
It looks like Jenkins isn't queuing new jobs pending a restart, but the currently running Math/develop job is preventing it from restarting. Do we want to kill the math develop job and restart it later, or let Jenkins queue for a day?

**Comment by serban-nicusor-toptal** [comment]
Jenkins is going to shut down for maintenance at Flatiron so I think the queued jobs will not be executed until it's back online anyway.

**Comment by WardBrian** [comment]
The relevant tests are now passing. The failure was due to a merge in stanc before math had a chance to percolate up (math also had some weird CI failures)

**Pull request merged**
