### PR TITLE
Fixes Windows tests; squashes all warnings

### PR DESCRIPTION
**Pull request by syclik**
#### Summary:

Fixes tests on Windows.
Squashes all warnings.

#### Intended Effect:

Get to 0 compiler warnings.

#### How to Verify:

Let Jenkins run all tests. There should be 0 compiler warnings.

#### Side Effects:

Added `-Wsign-compare` to clang++ build on mac, so we'll see the same warning messages.

#### Documentation:

None required.

#### Reviewer Suggestions: 

Anyone.

### CODE REVIEW

**Comment by syclik** [comment]
Jenkins, test this please.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
My fault. I verified that everything built on that machine, including the
distribution tests. Looks like it ran into permissions problems, but the
tests are fine.

Can someone take a look? Should be quick. There are a couple makefile
fixes, but the bulk is using init or size_t appropriately.

Rib, I checked. This will merge into your branch without a problem.

**Comment by syclik** [comment]
I stopped the build. I just changed some settings to make it run faster.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by bob-carpenter** [comment]
Looks great.  Thanks so much for doing all of this.

**Pull request merged**
