### PR TITLE
Feature/issue 1787 compound assign

### PR DESCRIPTION
**Pull request by bob-carpenter**
#### Summary:

Add `=` as alternative to `<-` for assignment; deprecate `<-`.

#### Intended Effect:

Make Stan look more like other programming languages and pave way for new `+=` syntax.

#### How to Verify:

Unit tests.

#### Side Effects:

Deprecation warnings now come up for `<-` with message indicating it should be replaced with `=`

#### Documentation:

The manual was updated to reflect the new assignment operator `=` and a note was included in the language reference chapter indicating that `<-` was the old assignment syntax.  As usual, we're not maintaining doc in parallel on both the old way and the new way.

#### Reviewer Suggestions: 

Anyone.

### CODE REVIEW

**Comment by bob-carpenter** [comment]
Actually, hang on.  I'll do the doc while I'm at it.

**Comment by bob-carpenter** [comment]
OK, ready to be reviewed now.

**Comment by syclik** [comment]
Cool! Thanks!

**Comment by bob-carpenter** [comment]
Let's make sure at the meeting it's what everyone wants
before merging!

**Comment by syclik** [comment]
Sure!

**Comment by bgoodri** [comment]
@bob-carpenter The next time you do a PR for the language, can you add "in the Stan language" after deprecated to the deprecation message about `<-`. It is a bit jarring to see in R that
```
posterior <- stan("foo.stan")
Warning (non-fatal): assignment operator <- deprecated; use = instead.
```
because it could be interpreted (particularly if using a package that auto-generates Stan code) that R has deprecated `<-`.

**Comment by syclik** [comment]
Hi Ben,

Can you open up a new issue? Can you add the exact wording you want for the message?


Daniel

**Pull request merged**
