### PR TITLE
[Jenkins] Integration tests are always essentially make-only.

### PR DESCRIPTION
**Pull request by seantalts**
#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by syclik** [comment]
What does the make only flag do?

And yes, these will fail to compile when something is wrong. The output of google test just confirms that it has indeed compiled correctly.

**Comment by seantalts** [comment]
I will give you 3 guesses 😂

**Comment by syclik** [comment]
My hope: it runs make without actually running the test executable. 

My fear: it just prints the output of make without running make. 

My third guess: it turns on a makerbot in the office.

**Comment by seantalts** [comment]
Hahahaha. Those were great. The hope was correct! But I realized that the
integration tests are both .PHONY targets that mostly just make sure the
models can be compiled, so they don't need to have a separate `--make-only`
step (and the one I had added was causing things to take twice as long in
this stage because the target was .PHONY and always runs).

**Pull request merged**
