### PR TITLE
[WIP] Add `using std::pow` to model code generator (Issue #1809 in math)

### PR DESCRIPTION
**Pull request by bbbales2**
#### Submission Checklist

- [ ] Run unit tests: `./runTests.py src/test/unit`
- [ ] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary

This is an alternate fix to https://github.com/stan-dev/math/pull/1810.

Work in progress, don't merge. It shouldn't work with mingw as it is anyway.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by bbbales2** [comment]
Hahahahaha well this took me a while to figure out why this didn't bring in a copy of ```std::pow```:

```
generate_using("std::log", o);
```

Oof, take 2.

**Comment by SteveBronder** [comment]
Do the tests here use the old or new compiler?

**Comment by bbbales2** [comment]
This is testing against the math in develop. So it has a pow implementation only for mingw.

**Comment by bbbales2** [comment]
(So we'd expect the tests here to pass everywhere but Windows)

**Comment by rok-cesnovar** [comment]
Can we merge this?

**Comment by bbbales2** [comment]
I think this is the way to go, but let's wait and see if there are any disagreements (https://discourse.mc-stan.org/t/using-std-pow-inside-stan-math-namespace/13975/14).

If I get nothing back by tonight I'll merge this, put up a math pull to remove the mingw pow stuff, ping you to check out how to do this in stanc3, and set up some time in the future for us all to talk through the interaction of the std and stan::math namespaces.

**Comment by rok-cesnovar** [comment]
Cool beans!

**Pull request merged**
