### PR TITLE
Cleanup the use of find in makefiles

### PR DESCRIPTION
**Pull request by rok-cesnovar**
#### Submission Checklist

- [x] Run unit tests: `./runTests.py src/test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary

Continuing the work in https://github.com/stan-dev/math/pull/1567 to close https://github.com/stan-dev/cmdstan/issues/786

The issue is that our makefiles rely on the gnu find command that is not available on Windows.

https://github.com/stan-dev/math/pull/1567 introduced a findfiles function that is a recursive version of the makefiles wildcard function. 

This PR uses that in stan-dev/stan

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Rok Češnovar

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by mitzimorris** [comment]
please note that `findfiles` function for CmdStan makefile is slightly problematic in that the console output contains extra linefeeds - this is an issue for cleanup commands.
https://github.com/stan-dev/cmdstan/pull/844

**Comment by rok-cesnovar** [comment]
Ready for another look now that the issue was fixed in Math.

**Comment by rok-cesnovar** [comment]
With the move of Jenkins workers to RTools 4.0 that does not come with the find gnu tool (Rtools 3.5 did come with it but you had to add a separate directory) we are finally forced to fix this immediately.

See develop tests that failed: https://jenkins.mc-stan.org/blue/rest/organizations/jenkins/pipelines/Stan/branches/develop/runs/600/nodes/93/steps/115/log/?start=0
a bunch of file not found 

and see this branch: https://jenkins.mc-stan.org/blue/organizations/jenkins/Stan/detail/PR-2902/9/pipeline

Develop is broken until we merge this.

**Comment by rok-cesnovar** [comment]
Restarted tests which should now pass with cmdstan fixed. Ready for review.

**Comment by rok-cesnovar** [comment]
Math and cmdstan moved to using findiles which is our custom function, in the previous release. 

Stan PR did not make it in. Windows does not have find natively, so this improves things for Windows users (those that want to run tests).

**Comment by rok-cesnovar** [comment]
@mitzimorris you were right, there was another one added in https://github.com/stan-dev/stan/pull/2916

Cleaned up now.

**Comment by rok-cesnovar** [comment]
Thanks!

**Pull request merged**
