### PR TITLE
enhanced include syntax, fixes #2358

### LINKED ISSUE #2358: allow space before # in includes
#### Summary:

Title says it all.  They will still be first thing on the line.  

Should the extra whitespace on the line go into the output?

This will actually match the doc as written and the existing RStan behavior.

#### Current Version:

v2.16.0

### PR DESCRIPTION
**Pull request by bob-carpenter**
#### Submission Checklist

- [x] Run unit tests: `./runTests.py src/test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary

Enhance include syntax to allow:

* space on the same line as an include
* quoted paths to allow internal spaces
* line comments after includes

It also fixes another issue, 

* no longer require paths from interfaces to end in `/` or `\`

#### How to Verify

Unit tests.

#### Side Effects

No.

#### Documentation

Updated include chapter in the reference manual.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by seantalts** [comment]
[Need to fix something with Windows tests](https://github.com/stan-dev/math/pull/946) before these will pass - sorry about that!

**Comment by seantalts** [comment]
It has a new error that is also my fault - as part of the compiler upgrade discussion I had to upgrade one of the Macs to high Sierra, which apparently broke the latex install. I want to move that to circleCI also. I will fix it soon, sorry.

**Comment by bob-carpenter** [comment]
No worries---there's no rush on this as nothing will depend on it until 2.19.

**Comment by seantalts** [comment]
Tests are passing.

**Pull request merged**
