### PR TITLE
Fix tests for stan-dev/math#933.

### PR DESCRIPTION
**Pull request by seantalts**
#### Submission Checklist

- [x] Run unit tests: `./runTests.py src/test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary
Fixes the compiler to work with the corrected signature of integrate_1d from stan-dev/math#933.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
These tests will only pass if ran with #1409 as math branch. I restarted the tests with the math submodule pointing to that PR. Not sure what would be the best order of merges to develop then.

**Comment by seantalts** [comment]
Oh right, thank you :)

**Comment by seantalts** [comment]
Yeah, I think no matter how we merge it there will be one build failure in develop.

Maybe a good procedure going forwards would be to check in the math submodule pointing at the math commit with the right code for the tests to run against? Then these Stan tests would run correctly and pass when merged to develop and then the Math tests will pass and we can merge that one too, and the submodule update job should also just keep working.

**Comment by rok-cesnovar** [comment]
Yeah, that is probably the only way to avoid develop failing. I restarted the math tests with upstream pointing to this Stan PR.

**Comment by seantalts** [comment]
Thanks :D

**Comment by rok-cesnovar** [comment]
Dont merge until https://github.com/stan-dev/math/pull/1409 passes otherwise we need to restart those tests.

**Comment by seantalts** [comment]
Okay, those passed, so I think the right thing now is to merge this and then immediately merge that. I will kill the first Stan develop job that starts as it will fail; the next one should be triggered by Math develop passing and then that one should pass. Thanks!

**Pull request merged**
