### PR TITLE
_rng functions in transformed data block

### PR DESCRIPTION
**Pull request by bob-carpenter**
#### Submisison Checklist

- [x] Run unit tests: `./runTests.py src/test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary

Allow functions ending in `_rng` to be called in the transformed data block.

#### Intended Effect

Allow simple data simulations.

#### How to Verify

Unit tests for legal and illegal contexts.

#### Side Effects

No.

#### Documentation

Updated manual to reflect change; added new section to BNF on `_rng` placement.

#### Reviewer Suggestions

Anyone.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by syclik** [comment]
Looks like a test failed with new compiler warnings: http://d1m1s1b1.stat.columbia.edu:8080/job/Stan%20Pull%20Request%20-%20Tests%20-%20Integration/892/

I'm going to try to recreate locally.

**Comment by syclik** [comment]
@bob-carpenter, I'm seeing a test failure. From the Stan branch, if you run this, you'll see that the generated code is producing code that's not compilable:

```
> make src/test/test-models/good/rng_loc.hpp-test
...
src/test/test-models/good/rng_loc.hpp:81:51: error: use of undeclared identifier 'base_rng__'
            stan::math::assign(y, normal_rng(0,1, base_rng__));
```

**Comment by bob-carpenter** [comment]
Thanks --- fixed it and have just been running more tests
to make sure it works now.

It's going to require all the interfaces to start passing
an RNG to the constructor.  For now, I made it work by adding
a second constructor that creates its own RNG for the constructor,
and it'll lead to reproducible results, but it'll be the same
results every time.

- Bob

**Comment by bob-carpenter** [comment]
I can't see what went wrong with the travis-ci/pr.  There aren't any errors when I click through and the badge seems to say passing even though it's highlighted in red.

**Comment by syclik** [comment]
Travis isn't 100% reliable.

I restarted the job. Just in case you're wondering how -- if you're
authenticated through GitHub, you can click through the broken travis
project all the way to the job that failed. In this case, it's this one:
https://travis-ci.org/stan-dev/stan/jobs/145956598

When it's not running, there's a circular arrow in the top right with a
hover-over tool tip, "restart job." When it is running, there's an X icon
in its place.

Once you click that, it'll restart the job.

**Comment by bob-carpenter** [comment]
Thanks.  Looks like the restart thing goes away if it passes.

**Comment by syclik** [comment]
Great. I think we can address the overall design goals of the model class at some point, but this works.

**Pull request merged**
