### PR TITLE
Fixes #2045. Making includes to the math library consistent

### LINKED ISSUE #2045: Clean up includes to the math library
#### Summary:
The includes to the math library should be limited to `stan/math/{prim, rev, fwd, mix}/{scal, arr, mat}.hpp` from the Stan library. 

#### Description:
Including other headers may cause problems with instantiating traits in the correct order. 

#### Additional Information:
stan-dev/math#375 depends on this issue. 

#### Current Version:
v2.11.0

### PR DESCRIPTION
**Pull request by syclik**
#### Submisison Checklist

- [x] Run unit tests: `./runTests.py src/test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary
I replaced the individual includes to the math library with a single include.

#### Intended Effect
This will ensure the traits get instantiated correctly.

#### How to Verify
Look at code.

#### Side Effects
This might include a few more files, but from each of our interfaces, this shouldn't have an effect.

#### Documentation
None necessary.

#### Reviewer Suggestions
Anyone.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by bob-carpenter** [comment]
Don't we want to go in exactly the opposite direction to have files include only what they use?  The problem I'm finding with these include-the-world things is that they cause the unit tests to all need to be recompiled.  And they're going to slow down compilation times (though I don't know by how much).  

The other thing we really want to do is avoid circular includes.  But it looks like you ordered things here so that you only included top-level math headers outside of math (obviously, as this is in stan-dev/stan, not in stan-dev/math).

**Comment by bob-carpenter** [comment]
Also, by the same logic as the `is_inf` refactor, shouldn't we be including one of our headers rather than `<Eigen/Dense>` so we can have better control of what gets included (particularly adding more if we need to, like our own traits files).

**Comment by bob-carpenter** [comment]
Otherwise, though, this looks OK.

**Comment by bob-carpenter** [comment]
So merge it if you think this is the right way to go.

**Comment by syclik** [comment]
For includes to the math library, we should include the most restrictive thing we can include, which I think I do for these changes. We should be including those in order to keep the traits instantiated in the correct order.

Regarding the changes to include Eigen directly: I did that for those files because they don't use the math library at all. They just use Eigen. Nothing from the `stan::math` namespace is used, so I just included the Eigen header directly.

**Comment by bob-carpenter** [comment]
OK, we can do that for now and if it's only double instantiations, that's all we should need going forward.

**Pull request merged**
