### PR TITLE
feature/issue 2736 add gp covfun to lang

### PR DESCRIPTION
**Pull request by drezap**
#### Submission Checklist

- [x] Run unit tests: `make ......./gp_regression_test.stan`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary

Add the GP covariance functions to the language (primitives of some popular materns, a dot product, and the periodic)

#### Intended Effect
New covariance functions.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Copyright 2019 Andre Zapico

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by drezap** [comment]
Can I have a review please?

**Comment by drezap** [comment]
This has been sitting here a while. The bugs in the last merged and reverted (PR #2739) were fixed in `stan-dev/math` (PR #1176).

If there's any doubt that this won't compile one can clone and run: `make test/test-models/good/function-signatures/math/matrix/gp_regression_test`

**Comment by drezap** [comment]
Heeyyy are we ever going go release this?

**Comment by bob-carpenter** [comment]
Sorry this languished.  We need to be better at getting PRs through.  Feel free to ping one or more relevant people via email as not reviewing something this simple is usually just an oversight.

**Comment by drezap** [comment]
Got it, I'll look at doing docs this weekend. Thanks

**Pull request merged**
