### PR TITLE
Remove support for ~/.config makefile inclusion

### PR DESCRIPTION
**Pull request by WardBrian**
#### Submission Checklist

- [x] Run unit tests: `./runTests.py src/test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary

Counterpart to https://github.com/stan-dev/math/pull/3090

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by wds15** [comment]
How come you want to remove this functionality? I have used this a few times to set things from my home dir as I am not allowed on my cluster to edit the cmdstan install dir. So how can users set stan makefile matters in the future from a user writable directory (meaning their home)? I do have to use the cmdstan installed into the system for compliance reasons.

**Comment by WardBrian** [comment]
Hi @wds15 -

Some explanation was given in https://github.com/stan-dev/math/issues/3088, but in short there are 3 main reasons:

- This 'feature' is almost completely undocumented. There were ~two mentions of it in the math developer documentation, none in the users guides.
- It [causes issues on Windows machines](https://discourse.mc-stan.org/t/cmdstan-path-has-not-been-set-yet-windows-cmdstanr-0-8/35398/7?u=wardbrian)
- Global config is in general hard to debug and having only one place that users can include special variables makes it easier to find config issues when they arise


If you are in a situation, as you describe, where the HOME folder behavior is desirable, you should ask the system administrators to add a `make/local` which defers to user's folders. For example, just adding the line this PR removes:

```make
-include $(HOME)/.config/stan/make.local 
```

to the global installation's `make/local` would opt back in to this behavior while not requiring the project as a whole to support it.

**Comment by wds15** [comment]
I see. Thanks for the explanation and the workaround to get the old behaviour.

Could the workaround be added to the example make/local which is distributed possibly? If not enabled, then at least in a commented out variant?

I consider it standard behaviour that programs respect config files residing it in users home directories...but you are right in that this specific option was not documented and I took it from the source.

**Review by mitzimorris — APPROVED** [review]
lgtm!

**Pull request merged**
