### PR TITLE
Fixes #2308. Moving license file to top level.

### LINKED ISSUE #2308: Add top level LICENSE file.
#### Summary:
Move the repo license to the top level.

#### Description:
See: https://help.github.com/articles/adding-a-license-to-a-repository/

This will have GitHub automatically display the license information on the repo website.

### PR DESCRIPTION
**Pull request by syclik**
#### Submission Checklist

- [x] Declare copyright holder and open-source license: see below

#### Summary

Moved `licenses/stan-license.txt` to `LICENSE.md` so GitHub will display the license information at the top of the project.

#### Intended Effect

Makes it easier to tell the project is new BSD licensed.

#### How to Verify

Look at the diff in the license files.

#### Side Effects

Two minor changes:
1. I updated the years on the copyright line.
2. In the third clause, I changed it back to the original language of the license. If it's necessary to highlight "Columbia University," then happy to revert that line back to what we had in the license file.

#### Reviewer Suggestions

@bob-carpenter 

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Stan Group

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by syclik** [comment]
@seantalts, looks like we're having Jenkins problems. Looks like the new boxes may not have latex installed?

**Comment by seantalts** [comment]
Woops. Installed it on the new box. Anything else besides doxygen you know it needs off the top of your head?

Jenkins, retest this please.

**Comment by syclik** [comment]
It should be:
- make
- find
- latex
- mklatex (I think it's shipped with latex these days)
- c++ compiler
- doxygen
- some more linux utils like grep

I think that should be it.

**Comment by seantalts** [comment]
Jenkins, retest this please.

Sorry, the Linux Jenkins node has been having networking issues. I took it offline for now.

**Pull request merged**
